// Architecture-only Drizzle sketch. Deliberately not imported by production schema.
import { pgTable, text, varchar, timestamp, integer, real, jsonb, index, uniqueIndex } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

const id = (name: string) => varchar(name).default(sql`gen_random_uuid()`).notNull();
export const municipalities = pgTable("municipalities", { id: id("id").primaryKey(), name: text("name").notNull(), parentId: varchar("parent_id"), province: text("province").notNull(), geometryWkt: text("geometry_wkt") });
export const entitlementSources = pgTable("entitlement_sources", { id: id("id").primaryKey(), municipalityId: varchar("municipality_id").notNull(), sourceType: text("source_type").notNull(), url: text("url").notNull(), adapterVersion: text("adapter_version").notNull(), licenseStatus: text("license_status").notNull() });
export const sourceSnapshots = pgTable("source_snapshots", { id: id("id").primaryKey(), sourceId: varchar("source_id").notNull(), sha256: text("sha256").notNull(), retrievedAt: timestamp("retrieved_at", { withTimezone: true }).notNull(), rawObjectKey: text("raw_object_key") }, t => [uniqueIndex("source_snapshot_hash_uq").on(t.sourceId, t.sha256)]);
export const landSites = pgTable("land_sites", { id: id("id").primaryKey(), municipalityId: varchar("municipality_id").notNull(), tier: text("tier").notNull(), displayAddress: text("display_address"), geometryWkt: text("geometry_wkt"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, t => [index("land_sites_municipality_idx").on(t.municipalityId)]);
export const siteIdentifiers = pgTable("site_identifiers", { id: id("id").primaryKey(), siteId: varchar("site_id").notNull(), kind: text("kind").notNull(), normalizedValue: text("normalized_value").notNull(), sourceId: varchar("source_id") }, t => [uniqueIndex("site_identifier_uq").on(t.kind, t.normalizedValue, t.sourceId)]);
export const approvalTracks = pgTable("approval_tracks", { id: id("id").primaryKey(), siteId: varchar("site_id").notNull(), trackType: text("track_type").notNull(), externalApplicationNumber: text("external_application_number") });
export const entitlementEvents = pgTable("entitlement_events", { id: id("id").primaryKey(), trackId: varchar("track_id").notNull(), stage: text("stage").notNull(), effectiveDate: timestamp("effective_date", { withTimezone: true }), observedAt: timestamp("observed_at", { withTimezone: true }).notNull(), snapshotId: varchar("snapshot_id").notNull(), confidence: real("confidence").notNull(), supersedesEventId: varchar("supersedes_event_id"), payload: jsonb("payload") });
export const fieldProvenance = pgTable("field_provenance", { id: id("id").primaryKey(), entityType: text("entity_type").notNull(), entityId: varchar("entity_id").notNull(), canonicalField: text("canonical_field").notNull(), snapshotId: varchar("snapshot_id").notNull(), rawPointer: text("raw_pointer").notNull() });
export const matchQuarantine = pgTable("match_quarantine", { id: id("id").primaryKey(), refreshRunId: varchar("refresh_run_id").notNull(), candidateJson: jsonb("candidate_json").notNull(), possibleSiteId: varchar("possible_site_id"), score: real("score").notNull(), status: text("status").default("pending").notNull() });
export const refreshRuns = pgTable("refresh_runs", { id: id("id").primaryKey(), sourceId: varchar("source_id").notNull(), startedAt: timestamp("started_at", { withTimezone: true }).notNull(), finishedAt: timestamp("finished_at", { withTimezone: true }), status: text("status").notNull(), fetched: integer("fetched").default(0), changed: integer("changed").default(0), quarantined: integer("quarantined").default(0), errored: integer("errored").default(0), warnings: jsonb("warnings") });
export const modelAssumptions = pgTable("model_assumptions", { id: id("id").primaryKey(), key: text("key").notNull(), value: real("value").notNull(), unit: text("unit").notNull(), effectiveDate: timestamp("effective_date", { withTimezone: true }).notNull(), sourceLink: text("source_link"), scenario: text("scenario").notNull(), modelVersion: text("model_version").notNull() });
