import type { Source } from './model';
export interface BarrieFeed { key:string; item:string; itemUrl:string; expectedItemType:string; expectedAccessInformation:string|null; rootUrl:string; url:string; child:number; expectedItemTitle:string; expectedLayerName:string; geometry:string; oid:string; where:string; expectedRootServiceItem:string|null; expectedServiceItem:string|null; expectedRootCopyright:string; expectedCopyright:string; rootDescriptionHash:string; descriptionHash:string; itemDescriptionHash:string; termsHash:string; fields:Record<string,string>; fieldTypes:Record<string,string>; dates:string[]; matchField?:string; nearbyRadiusM?:number; note:string; source:Source; }
export const BARRIE_GRANT={
  "site": "7c5a1ebb6eb648e0be1e7bf1ff4f2e94",
  "siteTitle": "City Of Barrie Open Data",
  "owner": "BarrieGIS",
  "org": "C964zBpHgJUpj4d0",
  "siteUrl": "https://opendata.barrie.ca",
  "defaultHostname": "public-barrie.opendata.arcgis.com",
  "customHostname": "opendata.barrie.ca",
  "group": "3ea69cc64836464a9b0e24064ca19e11",
  "groupTitle": "City Of Barrie Open Data Content",
  "catalogueGroups": [
    "a11c96895c544153a8a0d94a27c71fc1",
    "3ea69cc64836464a9b0e24064ca19e11"
  ],
  "licenceUrl": "https://www.barrie.ca/Online%20Services/PublishingImages/OpenData_Images/COB_DataLicense.pdf",
  "pdfHash": "d23050c0c893d2d08328d63c7ed21cb8964e4deeae18a96ae960f231fa991bbd",
  "offerHash": "7a2b3a3b0534751cf6bbdb4f4770b6237f509c3137b376c3562e5e8901a4c677"
};
export const BARRIE_FEEDS:BarrieFeed[]=[
  {
    "key": "municipality",
    "item": "18ab33558c764594a8b59e34e9474bea",
    "itemUrl": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/AdministrativeArea/MapServer/1",
    "expectedItemType": "Feature Service",
    "expectedAccessInformation": "City of Barrie",
    "rootUrl": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/AdministrativeArea/MapServer",
    "url": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/AdministrativeArea/MapServer/1",
    "child": 1,
    "expectedItemTitle": "City Boundary",
    "expectedLayerName": "City Boundary",
    "geometry": "esriGeometryPolygon",
    "oid": "OBJECTID",
    "where": "1=1",
    "expectedRootServiceItem": null,
    "expectedServiceItem": null,
    "expectedRootCopyright": "",
    "expectedCopyright": "",
    "rootDescriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "descriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "itemDescriptionHash": "9ad5a05f4382acfcea4a7db6fe22793a3d958685080192b564edb2c19db69e57",
    "termsHash": "f6b904a8a41ed5e7b1f7c6f4466a63c13c23659687b83215413897ddfa3c863f",
    "fields": {
      "OBJECTID": "recordId"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID"
    },
    "dates": [],
    "note": "Published City boundary reference only. Current legal boundary and January 2026 annex coverage are unverified; no-match does not establish that land is outside present-day Barrie.",
    "source": {
      "id": "barrie:municipality",
      "name": "Barrie — City Boundary",
      "url": "https://www.arcgis.com/home/item.html?id=18ab33558c764594a8b59e34e9474bea",
      "licence": "Open Government Licence – Barrie 1.0",
      "licenceUrl": "https://www.barrie.ca/Online%20Services/PublishingImages/OpenData_Images/COB_DataLicense.pdf",
      "attribution": "Contains information licensed under the Open Government Licence – Barrie."
    }
  },
  {
    "key": "permits",
    "item": "2a33295b41df4d2e87fda301fff140cc",
    "itemUrl": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/APLI/MapServer/1",
    "expectedItemType": "Feature Service",
    "expectedAccessInformation": "City of Barrie",
    "rootUrl": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/APLI/MapServer",
    "url": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/APLI/MapServer/1",
    "child": 1,
    "expectedItemTitle": "Active Issued Permits 2018 to Present",
    "expectedLayerName": "Issued Building Permits 2018 - Present",
    "geometry": "esriGeometryPoint",
    "oid": "OBJECTID",
    "where": "1=1",
    "expectedRootServiceItem": null,
    "expectedServiceItem": null,
    "expectedRootCopyright": "City of Barrie",
    "expectedCopyright": "",
    "rootDescriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "descriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "itemDescriptionHash": "4f621d90dc143a139bbaf3cdf05df9891b72da88c6be87178171093f575256fb",
    "termsHash": "f6b904a8a41ed5e7b1f7c6f4466a63c13c23659687b83215413897ddfa3c863f",
    "fields": {
      "OBJECTID": "recordId",
      "RECORD_ID": "publishedRecordId",
      "Full_Address": "publishedAddress",
      "Sub_Type": "publishedSubtype",
      "PARENT_RECORD_ID": "publishedParentRecordId",
      "RECORD_STATUS": "publishedStatus",
      "Date_Status": "publishedStatusDateRaw"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "RECORD_ID": "esriFieldTypeString",
      "Full_Address": "esriFieldTypeString",
      "Sub_Type": "esriFieldTypeString",
      "PARENT_RECORD_ID": "esriFieldTypeString",
      "RECORD_STATUS": "esriFieldTypeString",
      "Date_Status": "esriFieldTypeString"
    },
    "dates": [],
    "matchField": "Full_Address",
    "note": "Exact building-address active issued-permit observations opened from 2018 onward. Published status dates are raw text; record IDs and parent record IDs are retained. This excludes complete historical/closed permit scope and does not establish final inspection, occupancy, unit legality or present-day permit status.",
    "source": {
      "id": "barrie:permits",
      "name": "Barrie — Active Issued Permits 2018 to Present",
      "url": "https://www.arcgis.com/home/item.html?id=2a33295b41df4d2e87fda301fff140cc",
      "licence": "Open Government Licence – Barrie 1.0",
      "licenceUrl": "https://www.barrie.ca/Online%20Services/PublishingImages/OpenData_Images/COB_DataLicense.pdf",
      "attribution": "Contains information licensed under the Open Government Licence – Barrie."
    }
  },
  {
    "key": "nearbyPermitApplications",
    "item": "36129fd1cbad4fc6a003cec10dd01c56",
    "itemUrl": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/APLI/MapServer/0",
    "expectedItemType": "Feature Service",
    "expectedAccessInformation": "City of Barrie",
    "rootUrl": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/APLI/MapServer",
    "url": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/APLI/MapServer/0",
    "child": 0,
    "expectedItemTitle": "Active Permit Applications 2018 to Present",
    "expectedLayerName": "Active Building Permits 2018 - Present",
    "geometry": "esriGeometryPoint",
    "oid": "OBJECTID",
    "where": "1=1",
    "expectedRootServiceItem": null,
    "expectedServiceItem": null,
    "expectedRootCopyright": "City of Barrie",
    "expectedCopyright": "",
    "rootDescriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "descriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "itemDescriptionHash": "81afa09db7c3a44925caf08ee9dfabeb9e816e3e00242dbc29e426f7d31306df",
    "termsHash": "f6b904a8a41ed5e7b1f7c6f4466a63c13c23659687b83215413897ddfa3c863f",
    "fields": {
      "OBJECTID": "recordId",
      "Sub_Type": "publishedSubtype",
      "RECORD_STATUS": "publishedStatus",
      "Date_Opened": "publishedOpenedDateRaw"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "Sub_Type": "esriFieldTypeString",
      "RECORD_STATUS": "esriFieldTypeString",
      "Date_Opened": "esriFieldTypeString"
    },
    "dates": [],
    "nearbyRadiusM": 100,
    "note": "Nearby published active application-point observations opened from 2018 onward, within a 100 m straight-line screen. The feed publishes neither civic addresses nor file numbers; these are not assigned to the subject property. OBJECTID is a GIS row identifier. Date-opened text remains raw and geometry accuracy is unverified.",
    "source": {
      "id": "barrie:nearbyPermitApplications",
      "name": "Barrie — Active Permit Applications 2018 to Present",
      "url": "https://www.arcgis.com/home/item.html?id=36129fd1cbad4fc6a003cec10dd01c56",
      "licence": "Open Government Licence – Barrie 1.0",
      "licenceUrl": "https://www.barrie.ca/Online%20Services/PublishingImages/OpenData_Images/COB_DataLicense.pdf",
      "attribution": "Contains information licensed under the Open Government Licence – Barrie."
    }
  },
  {
    "key": "additionalUnits",
    "item": "1da609ba85a247f5ae3a20286a34a168",
    "itemUrl": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/Planning/MapServer/3",
    "expectedItemType": "Feature Service",
    "expectedAccessInformation": "City of Barrie",
    "rootUrl": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/Planning/MapServer",
    "url": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/Planning/MapServer/3",
    "child": 3,
    "expectedItemTitle": "Registered Two Unit Houses",
    "expectedLayerName": "Registered Two Unit Houses",
    "geometry": "esriGeometryPoint",
    "oid": "OBJECTID",
    "where": "1=1",
    "expectedRootServiceItem": null,
    "expectedServiceItem": null,
    "expectedRootCopyright": "",
    "expectedCopyright": "",
    "rootDescriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "descriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "itemDescriptionHash": "f431a7487df6536f770ee44c40f6c2aef1e1608f5ae4cae7c29c66cf042c49f0",
    "termsHash": "a3625ef98b973bf5d26eb83f28fb581f0fed39fcbf8da66582c1ddeb922231fb",
    "fields": {
      "OBJECTID": "recordId",
      "ADDR_FULL_LINE_BARRIE": "publishedAddress",
      "UNIT_TYPE": "publishedUnitType",
      "UNIT_NUMBER": "publishedUnitNumber",
      "REGISTRATION_STATUS": "publishedRegistrationStatus"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "ADDR_FULL_LINE_BARRIE": "esriFieldTypeString",
      "UNIT_TYPE": "esriFieldTypeString",
      "UNIT_NUMBER": "esriFieldTypeString",
      "REGISTRATION_STATUS": "esriFieldTypeString"
    },
    "dates": [],
    "matchField": "ADDR_FULL_LINE_BARRIE",
    "note": "Exact building-address two-unit registration observations. Preserve registration status, published unit type and number without assuming current legality, licence, final inspection, occupancy, unit identity or total legal unit count.",
    "source": {
      "id": "barrie:additionalUnits",
      "name": "Barrie — Registered Two Unit Houses",
      "url": "https://www.arcgis.com/home/item.html?id=1da609ba85a247f5ae3a20286a34a168",
      "licence": "Open Government Licence – Barrie 1.0",
      "licenceUrl": "https://www.barrie.ca/Online%20Services/PublishingImages/OpenData_Images/COB_DataLicense.pdf",
      "attribution": "Contains information licensed under the Open Government Licence – Barrie."
    }
  },
  {
    "key": "zoning",
    "item": "136f398c5e4a4dc18538b046c447a93a",
    "itemUrl": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/Planning/MapServer/0",
    "expectedItemType": "Feature Service",
    "expectedAccessInformation": "City of Barrie",
    "rootUrl": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/Planning/MapServer",
    "url": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/Planning/MapServer/0",
    "child": 0,
    "expectedItemTitle": "Zoning By-Law",
    "expectedLayerName": "In Force Zoning By-Law",
    "geometry": "esriGeometryPolygon",
    "oid": "OBJECTID",
    "where": "1=1",
    "expectedRootServiceItem": null,
    "expectedServiceItem": null,
    "expectedRootCopyright": "",
    "expectedCopyright": "",
    "rootDescriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "descriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "itemDescriptionHash": "1ef80c65db13b242ade1ecb4f508a0a0fe05e6b045df0111a3aa191389c0cd46",
    "termsHash": "f6b904a8a41ed5e7b1f7c6f4466a63c13c23659687b83215413897ddfa3c863f",
    "fields": {
      "OBJECTID": "recordId",
      "ZONING": "publishedZone",
      "SPECIAL": "publishedSpecialProvision",
      "HOLD": "publishedHold",
      "BYLAWNO": "publishedBylaw",
      "DESCRIPT": "publishedDescription",
      "LABEL": "publishedLabel",
      "LASTUPDATE": "publishedRecordEditDate"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "ZONING": "esriFieldTypeString",
      "SPECIAL": "esriFieldTypeString",
      "HOLD": "esriFieldTypeString",
      "BYLAWNO": "esriFieldTypeString",
      "DESCRIPT": "esriFieldTypeString",
      "LABEL": "esriFieldTypeString",
      "LASTUPDATE": "esriFieldTypeDate"
    },
    "dates": [
      "LASTUPDATE"
    ],
    "note": "Published In Force Zoning By-Law GIS reference, including zone, exception, hold, label and bylaw fields. Current legal applicability is unverified: Allandale CPPS replaces 2009-141 inside its area; former Innisfil 054-04, Springwater 5000 and Oro-Medonte 97-95 regimes also apply in parts of Barrie. Verify current instruments, amendments, appeals and parcel-wide coverage.",
    "source": {
      "id": "barrie:zoning",
      "name": "Barrie — Zoning By-Law",
      "url": "https://www.arcgis.com/home/item.html?id=136f398c5e4a4dc18538b046c447a93a",
      "licence": "Open Government Licence – Barrie 1.0",
      "licenceUrl": "https://www.barrie.ca/Online%20Services/PublishingImages/OpenData_Images/COB_DataLicense.pdf",
      "attribution": "Contains information licensed under the Open Government Licence – Barrie."
    }
  },
  {
    "key": "sitePlanControl",
    "item": "317554088034468cb0f2dac771a0393b",
    "itemUrl": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/Planning/MapServer/1",
    "expectedItemType": "Feature Service",
    "expectedAccessInformation": "City of Barrie",
    "rootUrl": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/Planning/MapServer",
    "url": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/Planning/MapServer/1",
    "child": 1,
    "expectedItemTitle": "Site Plan Control",
    "expectedLayerName": "Site Plan Control",
    "geometry": "esriGeometryPolygon",
    "oid": "OBJECTID",
    "where": "1=1",
    "expectedRootServiceItem": null,
    "expectedServiceItem": null,
    "expectedRootCopyright": "",
    "expectedCopyright": "",
    "rootDescriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "descriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "itemDescriptionHash": "e02ea974af37fae1320116eb69dfe2338ae459d0b060df491abc805b0e816ab3",
    "termsHash": "f6b904a8a41ed5e7b1f7c6f4466a63c13c23659687b83215413897ddfa3c863f",
    "fields": {
      "OBJECTID": "recordId",
      "TYPE": "publishedType",
      "BYLAWNO": "publishedBylaw",
      "REFERENCE": "publishedReference",
      "LASTUPDATE": "publishedRecordEditDate"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "TYPE": "esriFieldTypeString",
      "BYLAWNO": "esriFieldTypeString",
      "REFERENCE": "esriFieldTypeString",
      "LASTUPDATE": "esriFieldTypeDate"
    },
    "dates": [
      "LASTUPDATE"
    ],
    "note": "Published site-plan-control policy reference. This is not a site-plan application or approval. Allandale CPPS applicability, current exemptions, instruments and parcel-wide requirements remain unverified.",
    "source": {
      "id": "barrie:sitePlanControl",
      "name": "Barrie — Site Plan Control",
      "url": "https://www.arcgis.com/home/item.html?id=317554088034468cb0f2dac771a0393b",
      "licence": "Open Government Licence – Barrie 1.0",
      "licenceUrl": "https://www.barrie.ca/Online%20Services/PublishingImages/OpenData_Images/COB_DataLicense.pdf",
      "attribution": "Contains information licensed under the Open Government Licence – Barrie."
    }
  },
  {
    "key": "planningApplications",
    "item": "5f3a817276b643949fff4579cb5c566b",
    "itemUrl": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/Planning/MapServer/4",
    "expectedItemType": "Feature Service",
    "expectedAccessInformation": "City of Barrie",
    "rootUrl": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/Planning/MapServer",
    "url": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/Planning/MapServer/4",
    "child": 4,
    "expectedItemTitle": "Planning Applications",
    "expectedLayerName": "Planning Applications",
    "geometry": "esriGeometryPolygon",
    "oid": "OBJECTID",
    "where": "1=1",
    "expectedRootServiceItem": null,
    "expectedServiceItem": null,
    "expectedRootCopyright": "",
    "expectedCopyright": "",
    "rootDescriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "descriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "itemDescriptionHash": "27ebd3bda7ee4594f20b9828b4a4663c1f9e2c0199cfc40d4d17b0f69fd33b92",
    "termsHash": "fe852d54a1c43effb0b430f8983b40b68ac95306125b5ca8c1f4179f3f26bf53",
    "fields": {
      "OBJECTID": "recordId",
      "File_No": "publishedFileNumber",
      "Phase": "publishedPhase",
      "Application_Type": "publishedApplicationType",
      "Status": "publishedStatus",
      "Address_Location": "publishedLocation",
      "Landuse": "publishedLandUse",
      "Landuse_Changed_To": "publishedProposedLandUse",
      "Date_Application_Received": "publishedReceivedDate",
      "Approval_Date": "publishedApprovalDate",
      "ByLaw_No_Bill_No_Motion_No": "publishedBylawBillMotion",
      "LPAT_Appeal": "publishedAppealField",
      "Registration_Date": "publishedRegistrationDate",
      "Total_Residential_Units": "publishedResidentialUnits",
      "Total_ICI_Units": "publishedIciUnitsRaw",
      "URL": "publishedUrl"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "File_No": "esriFieldTypeString",
      "Phase": "esriFieldTypeString",
      "Application_Type": "esriFieldTypeString",
      "Status": "esriFieldTypeString",
      "Address_Location": "esriFieldTypeString",
      "Landuse": "esriFieldTypeString",
      "Landuse_Changed_To": "esriFieldTypeString",
      "Date_Application_Received": "esriFieldTypeDate",
      "Approval_Date": "esriFieldTypeDate",
      "ByLaw_No_Bill_No_Motion_No": "esriFieldTypeString",
      "LPAT_Appeal": "esriFieldTypeString",
      "Registration_Date": "esriFieldTypeDate",
      "Total_Residential_Units": "esriFieldTypeInteger",
      "Total_ICI_Units": "esriFieldTypeString",
      "URL": "esriFieldTypeString"
    },
    "dates": [
      "Date_Application_Received",
      "Approval_Date",
      "Registration_Date"
    ],
    "note": "Published subject-point planning-application polygons, including raw phase/status, received/approval/registration dates, appeal field and proposed unit totals. Status and dated approval fields do not prove current approval, conditions, resolved appeals, final inspection or permission. Plans/reports linked by City development pages have separate viewing-only copyright terms and are not copied.",
    "source": {
      "id": "barrie:planningApplications",
      "name": "Barrie — Planning Applications",
      "url": "https://www.arcgis.com/home/item.html?id=5f3a817276b643949fff4579cb5c566b",
      "licence": "Open Government Licence – Barrie 1.0",
      "licenceUrl": "https://www.barrie.ca/Online%20Services/PublishingImages/OpenData_Images/COB_DataLicense.pdf",
      "attribution": "Contains information licensed under the Open Government Licence – Barrie."
    }
  },
  {
    "key": "officialPlanReference",
    "item": "99586ad698ef42e78230ce6866286f30",
    "itemUrl": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/LandUsePlanning_OfficialPlan/MapServer/10",
    "expectedItemType": "Feature Service",
    "expectedAccessInformation": "City of Barrie",
    "rootUrl": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/LandUsePlanning_OfficialPlan/MapServer",
    "url": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/LandUsePlanning_OfficialPlan/MapServer/10",
    "child": 10,
    "expectedItemTitle": "Official Plan -  Map 2 - Land Use - Land Use",
    "expectedLayerName": "Land Use",
    "geometry": "esriGeometryPolygon",
    "oid": "OBJECTID",
    "where": "1=1",
    "expectedRootServiceItem": null,
    "expectedServiceItem": null,
    "expectedRootCopyright": "",
    "expectedCopyright": "",
    "rootDescriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "descriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "itemDescriptionHash": "d57f7c6ed0c849995670b9920ad992b6ab56b3cd691fe202176f07ab953baa20",
    "termsHash": "fe852d54a1c43effb0b430f8983b40b68ac95306125b5ca8c1f4179f3f26bf53",
    "fields": {
      "OBJECTID": "recordId",
      "TYPE": "publishedType",
      "SUBTYPE": "publishedSubtype",
      "OPDESG": "publishedDesignation",
      "LOCATION": "publishedLocation",
      "DOC_URL": "publishedDocumentUrl",
      "LABEL": "publishedLabel",
      "COMMUNITY_STRUCTURE": "publishedCommunityStructure",
      "OP_SECTION": "publishedPlanSection"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "TYPE": "esriFieldTypeString",
      "SUBTYPE": "esriFieldTypeString",
      "OPDESG": "esriFieldTypeString",
      "LOCATION": "esriFieldTypeString",
      "DOC_URL": "esriFieldTypeString",
      "LABEL": "esriFieldTypeString",
      "COMMUNITY_STRUCTURE": "esriFieldTypeString",
      "OP_SECTION": "esriFieldTypeString"
    },
    "dates": [],
    "note": "Published land-use GIS reference only. Current legal Official Plan schedules and amendments are unverified; the City lists July 31, 2026 consolidation and OPA1–8 including annexation, PPS2024 and Allandale CPPS. Do not infer development permission from a GIS label.",
    "source": {
      "id": "barrie:officialPlanReference",
      "name": "Barrie — Official Plan -  Map 2 - Land Use - Land Use",
      "url": "https://www.arcgis.com/home/item.html?id=99586ad698ef42e78230ce6866286f30",
      "licence": "Open Government Licence – Barrie 1.0",
      "licenceUrl": "https://www.barrie.ca/Online%20Services/PublishingImages/OpenData_Images/COB_DataLicense.pdf",
      "attribution": "Contains information licensed under the Open Government Licence – Barrie."
    }
  },
  {
    "key": "majorTransitStationArea",
    "item": "9916e4a860b24f0ebb6e7f62692a7ad6",
    "itemUrl": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/LandUsePlanning_OfficialPlan/MapServer/4",
    "expectedItemType": "Feature Service",
    "expectedAccessInformation": "City of Barrie",
    "rootUrl": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/LandUsePlanning_OfficialPlan/MapServer",
    "url": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/LandUsePlanning_OfficialPlan/MapServer/4",
    "child": 4,
    "expectedItemTitle": "Official Plan -  Map 1 - Community Structure - Major Transit Station Area",
    "expectedLayerName": "Major Transit Station Area",
    "geometry": "esriGeometryPolygon",
    "oid": "OBJECTID",
    "where": "1=1",
    "expectedRootServiceItem": null,
    "expectedServiceItem": null,
    "expectedRootCopyright": "",
    "expectedCopyright": "",
    "rootDescriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "descriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "itemDescriptionHash": "858f9694b2802a8eed9e13c77358a836086956e9e6d158f1c9a56cafcdf184a6",
    "termsHash": "f6b904a8a41ed5e7b1f7c6f4466a63c13c23659687b83215413897ddfa3c863f",
    "fields": {
      "OBJECTID": "recordId",
      "NAME": "publishedName",
      "TYPE": "publishedType",
      "SUBTYPE": "publishedSubtype",
      "DESCRIPT": "publishedDescription",
      "STATUS": "publishedStatus",
      "REFERENCE": "publishedReference",
      "DOC_URL": "publishedDocumentUrl",
      "LABEL": "publishedLabel"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "NAME": "esriFieldTypeString",
      "TYPE": "esriFieldTypeString",
      "SUBTYPE": "esriFieldTypeString",
      "DESCRIPT": "esriFieldTypeString",
      "STATUS": "esriFieldTypeString",
      "REFERENCE": "esriFieldTypeString",
      "DOC_URL": "esriFieldTypeString",
      "LABEL": "esriFieldTypeString"
    },
    "dates": [],
    "note": "Published MTSA reference; raw Official Plan 2022/Approved fields are preserved as source text. Current legal schedules, CPPS limits/districts and permissions are unverified. Allandale CPPS is in effect, but this MTSA polygon is not a verified CPP district map.",
    "source": {
      "id": "barrie:majorTransitStationArea",
      "name": "Barrie — Official Plan -  Map 1 - Community Structure - Major Transit Station Area",
      "url": "https://www.arcgis.com/home/item.html?id=9916e4a860b24f0ebb6e7f62692a7ad6",
      "licence": "Open Government Licence – Barrie 1.0",
      "licenceUrl": "https://www.barrie.ca/Online%20Services/PublishingImages/OpenData_Images/COB_DataLicense.pdf",
      "attribution": "Contains information licensed under the Open Government Licence – Barrie."
    }
  },
  {
    "key": "culturalHeritage",
    "item": "8bd5c5bc1baa443684adcd687cac8ccc",
    "itemUrl": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/FacilitiesStreets/MapServer/0",
    "expectedItemType": "Feature Service",
    "expectedAccessInformation": "City of Barrie",
    "rootUrl": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/FacilitiesStreets/MapServer",
    "url": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/FacilitiesStreets/MapServer/0",
    "child": 0,
    "expectedItemTitle": "Cultural Heritage",
    "expectedLayerName": "Cultural Heritage",
    "geometry": "esriGeometryPoint",
    "oid": "OBJECTID",
    "where": "1=1",
    "expectedRootServiceItem": null,
    "expectedServiceItem": null,
    "expectedRootCopyright": "City of Barrie",
    "expectedCopyright": "",
    "rootDescriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "descriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "itemDescriptionHash": "5f1ea4944b0dddc7578208e0ce6e317e0b4289b12a33b375a553e39e37470992",
    "termsHash": "f6b904a8a41ed5e7b1f7c6f4466a63c13c23659687b83215413897ddfa3c863f",
    "fields": {
      "OBJECTID": "recordId",
      "TYPE": "publishedType",
      "DESCRIPT": "publishedDescription",
      "TITLE": "publishedTitle",
      "YEARBUILT": "publishedFeatureYearBuiltRaw",
      "TOUR": "publishedTour",
      "TOURID": "publishedTourId",
      "URL": "publishedUrl",
      "LOCATION": "publishedLocation",
      "LABEL": "publishedLabel",
      "STATUS": "publishedStatus",
      "LASTUPDATE": "publishedRecordEditDate"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "TYPE": "esriFieldTypeString",
      "DESCRIPT": "esriFieldTypeString",
      "TITLE": "esriFieldTypeString",
      "YEARBUILT": "esriFieldTypeString",
      "TOUR": "esriFieldTypeString",
      "TOURID": "esriFieldTypeString",
      "URL": "esriFieldTypeString",
      "LOCATION": "esriFieldTypeString",
      "LABEL": "esriFieldTypeString",
      "STATUS": "esriFieldTypeString",
      "LASTUPDATE": "esriFieldTypeDate"
    },
    "dates": [
      "LASTUPDATE"
    ],
    "nearbyRadiusM": 100,
    "note": "Nearby City cultural-landmark/monument/art inventory within 100 m; this is not a complete municipal heritage register or an individual property designation screen. Raw year-built text refers to the published cultural feature and is not the subject building construction year. Geometry accuracy is unverified.",
    "source": {
      "id": "barrie:culturalHeritage",
      "name": "Barrie — Cultural Heritage",
      "url": "https://www.arcgis.com/home/item.html?id=8bd5c5bc1baa443684adcd687cac8ccc",
      "licence": "Open Government Licence – Barrie 1.0",
      "licenceUrl": "https://www.barrie.ca/Online%20Services/PublishingImages/OpenData_Images/COB_DataLicense.pdf",
      "attribution": "Contains information licensed under the Open Government Licence – Barrie."
    }
  },
  {
    "key": "urbanGrowthCentre",
    "item": "ea480a4522194a30ade7cb14dac7b9c4",
    "itemUrl": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/LandUsePlanning_OfficialPlan/MapServer/6",
    "expectedItemType": "Feature Service",
    "expectedAccessInformation": "City of Barrie",
    "rootUrl": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/LandUsePlanning_OfficialPlan/MapServer",
    "url": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/LandUsePlanning_OfficialPlan/MapServer/6",
    "child": 6,
    "expectedItemTitle": "Official Plan -  Map 1 - Community Structure - Urban Growth Centre",
    "expectedLayerName": "Urban Growth Centre",
    "geometry": "esriGeometryPolygon",
    "oid": "OBJECTID",
    "where": "1=1",
    "expectedRootServiceItem": null,
    "expectedServiceItem": null,
    "expectedRootCopyright": "",
    "expectedCopyright": "",
    "rootDescriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "descriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "itemDescriptionHash": "97af2202f3bedbd0b1b0f17a43d89c0f63717068568d6945faf7562859d1cd42",
    "termsHash": "f6b904a8a41ed5e7b1f7c6f4466a63c13c23659687b83215413897ddfa3c863f",
    "fields": {
      "OBJECTID": "recordId",
      "NAME": "publishedName",
      "TYPE": "publishedType",
      "SUBTYPE": "publishedSubtype",
      "DESCRIPT": "publishedDescription",
      "STATUS": "publishedStatus",
      "REFERENCE": "publishedReference",
      "DOC_URL": "publishedDocumentUrl",
      "LABEL": "publishedLabel"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "NAME": "esriFieldTypeString",
      "TYPE": "esriFieldTypeString",
      "SUBTYPE": "esriFieldTypeString",
      "DESCRIPT": "esriFieldTypeString",
      "STATUS": "esriFieldTypeString",
      "REFERENCE": "esriFieldTypeString",
      "DOC_URL": "esriFieldTypeString",
      "LABEL": "esriFieldTypeString"
    },
    "dates": [],
    "note": "Published urban-growth-centre reference with raw Official Plan 2022/Approved text; current legal schedules, amendments and permissions remain unverified.",
    "source": {
      "id": "barrie:urbanGrowthCentre",
      "name": "Barrie — Official Plan -  Map 1 - Community Structure - Urban Growth Centre",
      "url": "https://www.arcgis.com/home/item.html?id=ea480a4522194a30ade7cb14dac7b9c4",
      "licence": "Open Government Licence – Barrie 1.0",
      "licenceUrl": "https://www.barrie.ca/Online%20Services/PublishingImages/OpenData_Images/COB_DataLicense.pdf",
      "attribution": "Contains information licensed under the Open Government Licence – Barrie."
    }
  },
  {
    "key": "builtUpArea",
    "item": "0f5f63b39c0e449098574c5076cfd299",
    "itemUrl": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/LandUsePlanning_OfficialPlan/MapServer/1",
    "expectedItemType": "Feature Service",
    "expectedAccessInformation": "City of Barrie",
    "rootUrl": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/LandUsePlanning_OfficialPlan/MapServer",
    "url": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/LandUsePlanning_OfficialPlan/MapServer/1",
    "child": 1,
    "expectedItemTitle": "Official Plan -  Map 1 - Community Structure - Built-up Area",
    "expectedLayerName": "Built Up Area",
    "geometry": "esriGeometryPolygon",
    "oid": "OBJECTID",
    "where": "1=1",
    "expectedRootServiceItem": null,
    "expectedServiceItem": null,
    "expectedRootCopyright": "",
    "expectedCopyright": "",
    "rootDescriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "descriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "itemDescriptionHash": "9702c99a2bb7fbf75cb110e789246ab6031a1f74eb5ccba2e017d92bb49326d3",
    "termsHash": "f6b904a8a41ed5e7b1f7c6f4466a63c13c23659687b83215413897ddfa3c863f",
    "fields": {
      "OBJECTID": "recordId",
      "NAME": "publishedName",
      "TYPE": "publishedType",
      "SUBTYPE": "publishedSubtype",
      "DESCRIPT": "publishedDescription",
      "STATUS": "publishedStatus",
      "REFERENCE": "publishedReference",
      "DOC_URL": "publishedDocumentUrl"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "NAME": "esriFieldTypeString",
      "TYPE": "esriFieldTypeString",
      "SUBTYPE": "esriFieldTypeString",
      "DESCRIPT": "esriFieldTypeString",
      "STATUS": "esriFieldTypeString",
      "REFERENCE": "esriFieldTypeString",
      "DOC_URL": "esriFieldTypeString"
    },
    "dates": [],
    "note": "Historical built-up-boundary reference described as the area in 2008; raw source reference is preserved. This does not establish current urban limits, current policy or development permission.",
    "source": {
      "id": "barrie:builtUpArea",
      "name": "Barrie — Official Plan -  Map 1 - Community Structure - Built-up Area",
      "url": "https://www.arcgis.com/home/item.html?id=0f5f63b39c0e449098574c5076cfd299",
      "licence": "Open Government Licence – Barrie 1.0",
      "licenceUrl": "https://www.barrie.ca/Online%20Services/PublishingImages/OpenData_Images/COB_DataLicense.pdf",
      "attribution": "Contains information licensed under the Open Government Licence – Barrie."
    }
  },
  {
    "key": "addresses",
    "item": "4902c7fd1aff42fb892a9d4e51428b95",
    "itemUrl": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/AddressVW/MapServer",
    "expectedItemType": "Map Service",
    "expectedAccessInformation": "City of Barrie",
    "rootUrl": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/AddressVW/MapServer",
    "url": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/AddressVW/MapServer/0",
    "child": 0,
    "expectedItemTitle": "Address Points",
    "expectedLayerName": "Address VW",
    "geometry": "esriGeometryPoint",
    "oid": "OBJECTID",
    "where": "STATUS = 'Current'",
    "expectedRootServiceItem": null,
    "expectedServiceItem": null,
    "expectedRootCopyright": "City of Barrie",
    "expectedCopyright": "",
    "rootDescriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "descriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "itemDescriptionHash": "bfd482c937f447b57edf5b4e4d6824cd96a8d6ab673a99ffa7e576780db8bcf7",
    "termsHash": "f6b904a8a41ed5e7b1f7c6f4466a63c13c23659687b83215413897ddfa3c863f",
    "fields": {
      "OBJECTID": "recordId",
      "ADDRESSID": "publishedAddressId",
      "STATUS": "publishedStatus",
      "ADDRNUMBER": "publishedCivicNumber",
      "SSTRNAME": "publishedStreetName",
      "SSTRSUFF": "publishedStreetType",
      "SSTRDIR": "publishedStreetDirection",
      "FULLADDR": "publishedAddress",
      "UNITNUMBER": "publishedCivicUnit",
      "LASTUPDATE": "publishedRecordEditDate"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "ADDRESSID": "esriFieldTypeInteger",
      "STATUS": "esriFieldTypeString",
      "ADDRNUMBER": "esriFieldTypeString",
      "SSTRNAME": "esriFieldTypeString",
      "SSTRSUFF": "esriFieldTypeString",
      "SSTRDIR": "esriFieldTypeString",
      "FULLADDR": "esriFieldTypeString",
      "UNITNUMBER": "esriFieldTypeString",
      "LASTUPDATE": "esriFieldTypeDate"
    },
    "dates": [
      "LASTUPDATE"
    ],
    "matchField": "FULLADDR",
    "note": "Current civic attributes only; full address, number, street type/direction and blank unit must agree. Generic source metadata does not establish building/GPS accuracy or cadastral lineage, so City point/parcel geometry is not reused as precise identity.",
    "source": {
      "id": "barrie:addresses",
      "name": "Barrie — Address Points",
      "url": "https://www.arcgis.com/home/item.html?id=4902c7fd1aff42fb892a9d4e51428b95",
      "licence": "Open Government Licence – Barrie 1.0",
      "licenceUrl": "https://www.barrie.ca/Online%20Services/PublishingImages/OpenData_Images/COB_DataLicense.pdf",
      "attribution": "Contains information licensed under the Open Government Licence – Barrie."
    }
  },
  {
    "key": "ward",
    "item": "5fa5e6a45cff494592cc0ff99924833f",
    "itemUrl": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/AdministrativeArea/MapServer/0",
    "expectedItemType": "Feature Service",
    "expectedAccessInformation": "City of Barrie",
    "rootUrl": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/AdministrativeArea/MapServer",
    "url": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/AdministrativeArea/MapServer/0",
    "child": 0,
    "expectedItemTitle": "Wards",
    "expectedLayerName": "Wards",
    "geometry": "esriGeometryPolygon",
    "oid": "OBJECTID",
    "where": "1=1",
    "expectedRootServiceItem": null,
    "expectedServiceItem": null,
    "expectedRootCopyright": "",
    "expectedCopyright": "",
    "rootDescriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "descriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "itemDescriptionHash": "b47fe75dd83d260fba3243d298fbca2a8576d9ee922c6cd81ba625bea08cbbf1",
    "termsHash": "f6b904a8a41ed5e7b1f7c6f4466a63c13c23659687b83215413897ddfa3c863f",
    "fields": {
      "OBJECTID": "recordId",
      "WARD_NO": "publishedWardNumber"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "WARD_NO": "esriFieldTypeInteger"
    },
    "dates": [],
    "note": "Published ward reference. Current legal election boundaries and councillor identity are not verified; elected-person fields are excluded.",
    "source": {
      "id": "barrie:ward",
      "name": "Barrie — Wards",
      "url": "https://www.arcgis.com/home/item.html?id=5fa5e6a45cff494592cc0ff99924833f",
      "licence": "Open Government Licence – Barrie 1.0",
      "licenceUrl": "https://www.barrie.ca/Online%20Services/PublishingImages/OpenData_Images/COB_DataLicense.pdf",
      "attribution": "Contains information licensed under the Open Government Licence – Barrie."
    }
  },
  {
    "key": "futureWard2026",
    "item": "7780d93fcff74a82900e0f0c35d08aff",
    "itemUrl": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/AdministrativeArea/MapServer/3",
    "expectedItemType": "Feature Service",
    "expectedAccessInformation": "City of Barrie",
    "rootUrl": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/AdministrativeArea/MapServer",
    "url": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/AdministrativeArea/MapServer/3",
    "child": 3,
    "expectedItemTitle": "Wards (Nov 2026)",
    "expectedLayerName": "Wards (Nov 2026)",
    "geometry": "esriGeometryPolygon",
    "oid": "OBJECTID",
    "where": "1=1",
    "expectedRootServiceItem": null,
    "expectedServiceItem": null,
    "expectedRootCopyright": "",
    "expectedCopyright": "",
    "rootDescriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "descriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "itemDescriptionHash": "d0f544f9e9d0d7835944f3a8eed9fbdfe1a5d6c29ebe5b5a18bc3bc5a4d6eb96",
    "termsHash": "f6b904a8a41ed5e7b1f7c6f4466a63c13c23659687b83215413897ddfa3c863f",
    "fields": {
      "OBJECTID": "recordId",
      "WARD_NO": "publishedWardNumber",
      "LASTUPDATE": "publishedRecordEditDate"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "WARD_NO": "esriFieldTypeInteger",
      "LASTUPDATE": "esriFieldTypeDate"
    },
    "dates": [
      "LASTUPDATE"
    ],
    "note": "Separately published Wards (Nov 2026) reference. It is not silently substituted for the current ward map; effective election/legal boundary applicability remains unverified. Elected-person fields are excluded.",
    "source": {
      "id": "barrie:futureWard2026",
      "name": "Barrie — Wards (Nov 2026)",
      "url": "https://www.arcgis.com/home/item.html?id=7780d93fcff74a82900e0f0c35d08aff",
      "licence": "Open Government Licence – Barrie 1.0",
      "licenceUrl": "https://www.barrie.ca/Online%20Services/PublishingImages/OpenData_Images/COB_DataLicense.pdf",
      "attribution": "Contains information licensed under the Open Government Licence – Barrie."
    }
  },
  {
    "key": "specialPolicyArea",
    "item": "acf91149b807424582a3084b238ed251",
    "itemUrl": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/LandUsePlanning_OfficialPlan/MapServer/13",
    "expectedItemType": "Feature Service",
    "expectedAccessInformation": null,
    "rootUrl": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/LandUsePlanning_OfficialPlan/MapServer",
    "url": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/LandUsePlanning_OfficialPlan/MapServer/13",
    "child": 13,
    "expectedItemTitle": "Official Plan - Map 3 - Natural Heritage Protection Overlays - Special Policy Area",
    "expectedLayerName": "Special Policy Area",
    "geometry": "esriGeometryPolygon",
    "oid": "OBJECTID",
    "where": "1=1",
    "expectedRootServiceItem": null,
    "expectedServiceItem": null,
    "expectedRootCopyright": "",
    "expectedCopyright": "",
    "rootDescriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "descriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "itemDescriptionHash": "21d8fe0c65f1209870fe68fc95dd311d29dafb9b8aabc75889a7cd11c707d5e3",
    "termsHash": "a3625ef98b973bf5d26eb83f28fb581f0fed39fcbf8da66582c1ddeb922231fb",
    "fields": {
      "OBJECTID": "recordId",
      "TYPE": "publishedType",
      "SUBTYPE": "publishedSubtype",
      "OP_SECTION": "publishedPlanSection",
      "DESCRIPT": "publishedDescription",
      "ADDRESS": "publishedAddress",
      "LOCATION": "publishedLocation",
      "LABEL": "publishedLabel"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "TYPE": "esriFieldTypeString",
      "SUBTYPE": "esriFieldTypeString",
      "OP_SECTION": "esriFieldTypeString",
      "DESCRIPT": "esriFieldTypeString",
      "ADDRESS": "esriFieldTypeString",
      "LOCATION": "esriFieldTypeString",
      "LABEL": "esriFieldTypeString"
    },
    "dates": [],
    "note": "Published City Official Plan special environmental policy reference. Current legal schedule/text, third-party conservation regulation, studies and parcel-wide requirements remain unverified; no environmental clearance is established.",
    "source": {
      "id": "barrie:specialPolicyArea",
      "name": "Barrie — Official Plan - Map 3 - Natural Heritage Protection Overlays - Special Policy Area",
      "url": "https://www.arcgis.com/home/item.html?id=acf91149b807424582a3084b238ed251",
      "licence": "Open Government Licence – Barrie 1.0",
      "licenceUrl": "https://www.barrie.ca/Online%20Services/PublishingImages/OpenData_Images/COB_DataLicense.pdf",
      "attribution": "Contains information licensed under the Open Government Licence – Barrie."
    }
  },
  {
    "key": "historicNeighbourhood",
    "item": "1cbdd10524d84fd7ab3a713eaadde682",
    "itemUrl": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/LandUsePlanning_OfficialPlan/MapServer/45",
    "expectedItemType": "Feature Service",
    "expectedAccessInformation": null,
    "rootUrl": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/LandUsePlanning_OfficialPlan/MapServer",
    "url": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/LandUsePlanning_OfficialPlan/MapServer/45",
    "child": 45,
    "expectedItemTitle": "Official Plan - Map 8 - Cultural City Features - Historic Neighbourhood Boundary",
    "expectedLayerName": "Historic Neighbourhood Boundary",
    "geometry": "esriGeometryPolygon",
    "oid": "OBJECTID",
    "where": "1=1",
    "expectedRootServiceItem": null,
    "expectedServiceItem": null,
    "expectedRootCopyright": "",
    "expectedCopyright": "",
    "rootDescriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "descriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "itemDescriptionHash": "ea50488f5e670f997fe72b71d4e8ebbcf6b05bfb40c0df159d0ada19d0fb640e",
    "termsHash": "a3625ef98b973bf5d26eb83f28fb581f0fed39fcbf8da66582c1ddeb922231fb",
    "fields": {
      "OBJECTID": "recordId",
      "NAME": "publishedName",
      "TYPE": "publishedType",
      "SUBTYPE": "publishedSubtype",
      "DESCRIPT": "publishedDescription",
      "STATUS": "publishedStatus",
      "DOC_URL": "publishedDocumentUrl",
      "LABEL": "publishedLabel"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "NAME": "esriFieldTypeString",
      "TYPE": "esriFieldTypeString",
      "SUBTYPE": "esriFieldTypeString",
      "DESCRIPT": "esriFieldTypeString",
      "STATUS": "esriFieldTypeString",
      "DOC_URL": "esriFieldTypeString",
      "LABEL": "esriFieldTypeString"
    },
    "dates": [],
    "note": "Published historic-neighbourhood strategy area. Raw strategy status is distinct from individual/district heritage designation, current instruments and alteration requirements.",
    "source": {
      "id": "barrie:historicNeighbourhood",
      "name": "Barrie — Official Plan - Map 8 - Cultural City Features - Historic Neighbourhood Boundary",
      "url": "https://www.arcgis.com/home/item.html?id=1cbdd10524d84fd7ab3a713eaadde682",
      "licence": "Open Government Licence – Barrie 1.0",
      "licenceUrl": "https://www.barrie.ca/Online%20Services/PublishingImages/OpenData_Images/COB_DataLicense.pdf",
      "attribution": "Contains information licensed under the Open Government Licence – Barrie."
    }
  },
  {
    "key": "employmentArea",
    "item": "455dabaa98564ac7b91e11a2f5f5f35a",
    "itemUrl": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/LandUsePlanning_OfficialPlan/MapServer/47",
    "expectedItemType": "Feature Service",
    "expectedAccessInformation": null,
    "rootUrl": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/LandUsePlanning_OfficialPlan/MapServer",
    "url": "https://gispublic.barrie.ca/arcgis/rest/services/Open_Data/LandUsePlanning_OfficialPlan/MapServer/47",
    "child": 47,
    "expectedItemTitle": "Official Plan - Map 1 - Community Structure - Employment Area",
    "expectedLayerName": "Employment Area",
    "geometry": "esriGeometryPolygon",
    "oid": "OBJECTID",
    "where": "1=1",
    "expectedRootServiceItem": null,
    "expectedServiceItem": null,
    "expectedRootCopyright": "",
    "expectedCopyright": "",
    "rootDescriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "descriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "itemDescriptionHash": "3d0618cdc17214e71664043884a45c883f83f5c667a62c63ab99784e9aabaf96",
    "termsHash": "a3625ef98b973bf5d26eb83f28fb581f0fed39fcbf8da66582c1ddeb922231fb",
    "fields": {
      "OBJECTID": "recordId",
      "TYPE": "publishedType",
      "SUBTYPE": "publishedSubtype",
      "OPDESG": "publishedDesignation",
      "LOCATION": "publishedLocation",
      "DOC_URL": "publishedDocumentUrl",
      "LABEL": "publishedLabel",
      "LASTUPDATE": "publishedRecordEditDate",
      "COMMUNITY_STRUCTURE": "publishedCommunityStructure",
      "OP_SECTION": "publishedPlanSection"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "TYPE": "esriFieldTypeString",
      "SUBTYPE": "esriFieldTypeString",
      "OPDESG": "esriFieldTypeString",
      "LOCATION": "esriFieldTypeString",
      "DOC_URL": "esriFieldTypeString",
      "LABEL": "esriFieldTypeString",
      "LASTUPDATE": "esriFieldTypeDate",
      "COMMUNITY_STRUCTURE": "esriFieldTypeString",
      "OP_SECTION": "esriFieldTypeString"
    },
    "dates": [
      "LASTUPDATE"
    ],
    "note": "Published employment-policy reference; the inspected feed returned zero rows. Empty results do not establish absence of employment policy. Current legal designations, OPA3 applicability, amendments and permissions remain unverified.",
    "source": {
      "id": "barrie:employmentArea",
      "name": "Barrie — Official Plan - Map 1 - Community Structure - Employment Area",
      "url": "https://www.arcgis.com/home/item.html?id=455dabaa98564ac7b91e11a2f5f5f35a",
      "licence": "Open Government Licence – Barrie 1.0",
      "licenceUrl": "https://www.barrie.ca/Online%20Services/PublishingImages/OpenData_Images/COB_DataLicense.pdf",
      "attribution": "Contains information licensed under the Open Government Licence – Barrie."
    }
  }
];
export const BARRIE_WITHHELD=[
  {
    "layer": "municipalAddressGeometry",
    "url": "https://www.arcgis.com/home/item.html?id=4902c7fd1aff42fb892a9d4e51428b95",
    "reason": "Generic City address geometry accuracy and cadastral lineage are unverified; civic attributes are licensed separately and geometry is not reused as precise identity."
  },
  {
    "layer": "currentMunicipalBoundary",
    "url": "https://www.arcgis.com/home/item.html?id=7f9262ee06ce41adbb6b8c577db75428",
    "reason": "CITY_BOUNDARY_2025 is outside both inspected official open-data curation groups and has no verified full reuse grant; January 2026 legal annex coverage is unverified. No records/counts from this separate feed are queried."
  },
  {
    "layer": "communityPlanningPermit",
    "url": "https://www.barrie.ca/services-payments/permits-licences-applications/community-planning-permit-system-allandale-major-transit-station-area",
    "reason": "Allandale CPP bylaw was adopted June17,2026 and the City reports CPPS in effect. Current exact CPP district geometry has no verified reusable catalogue binding and is not queried; current applicability, variations, conditions and parcel-wide permissions require City confirmation."
  },
  {
    "layer": "completePermitHistory",
    "url": "https://eservices.barrie.ca/APLI/Cap/CapHome.aspx?globalsearch=true&module=Permits",
    "reason": "Licensed issued feed covers active permits opened since2018; complete earlier/closed permit history, inspections, completion and occupancy are not connected. APLI public access is separate from commercial reuse of plans and record files."
  },
  {
    "layer": "permitApplicationAddressIdentity",
    "url": "https://www.arcgis.com/home/item.html?id=36129fd1cbad4fc6a003cec10dd01c56",
    "reason": "The licensed active-application GIS feed publishes no address or file number. Only separately labelled nearby observations are returned; no exact-property application history or identity join is established."
  },
  {
    "layer": "sitePlans",
    "url": "https://www.arcgis.com/home/item.html?id=d2dd810c8688431f85578435428f36f5",
    "reason": "The discovered Site Plans child is not in either inspected official open-data curation group. Its general copyright notice does not establish the complete commercial grant binding; no records or counts are queried."
  },
  {
    "layer": "heritage",
    "url": "https://storymaps.arcgis.com/stories/ee54f35808b24733a19fa766630ad9f6",
    "reason": "Current individual/designated/listed municipal heritage register geometry and instruments have no verified reusable catalogue binding. Cultural monuments and historic-neighbourhood strategy areas are separate references and do not complete the register."
  },
  {
    "layer": "variance",
    "url": "https://www.barrie.ca/services-payments/permits-licences-applications",
    "reason": "No licensed complete minor-variance decisions, conditions and appeal history has been verified in this catalogue audit; Allandale CPPS replaces that process within its area."
  },
  {
    "layer": "parcel",
    "url": "https://www.arcgis.com/home/item.html?id=5b753358b2ef41029195f81440331af7",
    "reason": "Current cadastral geometry, third-party parcel rights, surveyed lot area and legal identifiers have not been verified for reuse; maps that display parcels do not supply that grant."
  },
  {
    "layer": "buildingFootprints",
    "url": "https://opendata.barrie.ca",
    "reason": "No complete reusable building-footprint/height/area source and aerial/supplier lineage was verified in this audit."
  },
  {
    "layer": "barrieConservationRegulation",
    "url": "https://www.barrie.ca/government-news/adopted-strategies-plans/official-plan",
    "reason": "Current LSRCA/NVCA parcel-wide regulation, floodplain and source-water originating rights/current schedules are unverified; existing scientific watershed screens are separate from regulation. Blended natural-heritage/water-protection feeds remain unqueried pending their originating rights and current instrument audit."
  },
  {
    "layer": "currentPlanningInstruments",
    "url": "https://www.barrie.ca/government/policies-laws/laws-listing/zoning-law",
    "reason": "Published zoning and plan GIS references do not verify current 2009-141, Allandale CPP, former Innisfil054-04, Springwater5000 or Oro-Medonte97-95 applicability, written exceptions/holds, amendments, OPA1–8, appeal outcomes or development permissions."
  }
];
