import type { Source } from './model';
export interface BramptonFeed { key:string; item:string; itemUrl:string; expectedItemType:string; expectedItemTitle:string; expectedAccessInformation:string|null; rootUrl:string; url:string; child:number; expectedLayerName:string; childType:string; geometry:string|null; oid:string; expectedRootServiceItem:string|null; expectedServiceItem:string|null; expectedRootCopyright:string; expectedCopyright:string; rootDescriptionHash:string; descriptionHash:string; itemDescriptionHash:string; termsHash:string; fields:Record<string,string>; fieldTypes:Record<string,string>; dates:string[]; matchField?:string; planningApplication?:boolean; licenceParent?:string; note:string; source:Source; }
export const BRAMPTON_GRANT={
  "site": "05c59502187b44d288f00b2aa43fc5d1",
  "siteType": "Web Mapping Application",
  "siteTitle": "Bramptons GeoHub",
  "siteUrl": "https://geohub-brampton.opendata.arcgis.com",
  "owner": "BramptonMaps",
  "org": "rl7ACuZkiFsmDA2g",
  "defaultHostname": "geohub-brampton.opendata.arcgis.com",
  "customHostname": "geohub.brampton.ca",
  "catalogueGroups": [
    "a4f2e37cdb4846f8b240e2af717851f7",
    "8cfebb20725c43d0b7be6963f98daa3a",
    "2554645265d44df48b6ef386100bd9cc",
    "b47c0ccf02044f059e6d9ebbaa21ad93",
    "0d1813a89f1b4dd98dacdeafdd9fd26b"
  ],
  "group": "a4f2e37cdb4846f8b240e2af717851f7",
  "groupTitle": "Brampton Open Data",
  "licenceUrl": "https://creativecommons.org/licenses/by/4.0/",
  "legalCodeUrl": "https://creativecommons.org/licenses/by/4.0/legalcode.en",
  "planningParent": "6b38d99be0484aada17668992f51e3c7",
  "planningParentTitle": "Planning_Land_Use_Development",
  "planningParentUrl": "https://services3.arcgis.com/rl7ACuZkiFsmDA2g/arcgis/rest/services/Planning_Land_Use_Development/FeatureServer",
  "planningParentTermsHash": "e8c08134a28d7780f0cc693b70826ce9d79c4d3d4dcab60a6792045d07635b80"
};
export const BRAMPTON_FEEDS:BramptonFeed[]=[
  {
    "key": "municipalAddresses",
    "item": "56bd6b5ac117445db5e64d14b72e061e",
    "itemUrl": "https://maps1.brampton.ca/arcgis/rest/services/COB/OpenData_Address_Points/MapServer/14",
    "expectedItemType": "Map Service",
    "expectedItemTitle": "Address Points",
    "expectedAccessInformation": "City of Brampton",
    "rootUrl": "https://maps1.brampton.ca/arcgis/rest/services/COB/OpenData_Address_Points/MapServer",
    "url": "https://maps1.brampton.ca/arcgis/rest/services/COB/OpenData_Address_Points/MapServer/14",
    "child": 14,
    "expectedLayerName": "Address Points",
    "childType": "Feature Layer",
    "geometry": "esriGeometryPoint",
    "oid": "OBJECTID",
    "expectedRootServiceItem": "",
    "expectedServiceItem": "",
    "expectedRootCopyright": "City of Brampton",
    "expectedCopyright": "City of Brampton",
    "rootDescriptionHash": "e58c9046a1b37aa5c9a7e134b70fb15b8ad7b32f072e25b8cc8f22d1d3b95f6a",
    "descriptionHash": "c168f312b6551e0d8cdfca3a97b7cd9e4ac47bb12c9402245d67d80aa15e9ddc",
    "itemDescriptionHash": "c2f34c1ad18bc05189bc6fc835bbf746246251c7c1b5482f044e5ff92c85dbdd",
    "termsHash": "9169c5aaa73aac3884f693dd6b6d7552b69be7aadc6a142697ac82f806e714e2",
    "fields": {
      "OBJECTID": "recordId",
      "FULL_ADDRESS": "publishedAddress",
      "UNIT_NO": "publishedUnit",
      "CIVIC_NUMBER": "publishedCivicNumber",
      "STREET_NAME": "publishedStreetName",
      "STREET_TYPE": "publishedStreetType",
      "STREET_DIRECTION": "publishedStreetDirection",
      "CITY": "publishedCity",
      "PROVINCE": "publishedProvince",
      "POSTAL_CODE": "publishedPostalCode",
      "ADDRESS_TYPE": "publishedAddressType",
      "ADDRESS_ID": "publishedAddressId"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "FULL_ADDRESS": "esriFieldTypeString",
      "UNIT_NO": "esriFieldTypeString",
      "CIVIC_NUMBER": "esriFieldTypeString",
      "STREET_NAME": "esriFieldTypeString",
      "STREET_TYPE": "esriFieldTypeString",
      "STREET_DIRECTION": "esriFieldTypeString",
      "CITY": "esriFieldTypeString",
      "PROVINCE": "esriFieldTypeString",
      "POSTAL_CODE": "esriFieldTypeString",
      "ADDRESS_TYPE": "esriFieldTypeString",
      "ADDRESS_ID": "esriFieldTypeDouble"
    },
    "dates": [],
    "matchField": "FULL_ADDRESS",
    "note": "Strict civic attributes only: building address, components, blank unit, City and province must agree. Municipal point geometry has no verified building/GPS accuracy and is never reused as precise identity.",
    "source": {
      "id": "brampton:municipalAddresses",
      "name": "Brampton — Address Points",
      "url": "https://www.arcgis.com/home/item.html?id=56bd6b5ac117445db5e64d14b72e061e",
      "licence": "CC BY 4.0",
      "licenceUrl": "https://creativecommons.org/licenses/by/4.0/",
      "attribution": "City of Brampton. Contains information licensed under CC BY 4.0; selected attributes are renamed and dates reformatted by Homies / Realist. No City endorsement."
    }
  },
  {
    "key": "municipality",
    "item": "d837bf1134444bf1b22d69257480dfd0",
    "itemUrl": "https://maps1.brampton.ca/arcgis/rest/services/COB/Common/MapServer/2",
    "expectedItemType": "Feature Service",
    "expectedItemTitle": "City Limit",
    "expectedAccessInformation": "City of Brampton",
    "rootUrl": "https://maps1.brampton.ca/arcgis/rest/services/COB/Common/MapServer",
    "url": "https://maps1.brampton.ca/arcgis/rest/services/COB/Common/MapServer/2",
    "child": 2,
    "expectedLayerName": "City Limit",
    "childType": "Feature Layer",
    "geometry": "esriGeometryPolygon",
    "oid": "OBJECTID",
    "expectedRootServiceItem": null,
    "expectedServiceItem": null,
    "expectedRootCopyright": "City of Brampton",
    "expectedCopyright": "City of Brampton",
    "rootDescriptionHash": "7f58596127201c06d503072adc118a920d9852560f55d8344408c0f8a83dc657",
    "descriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "itemDescriptionHash": "5820f9a5e36a1d9d755e5caa18c071b47d87965cc1607563febd6417a94e38b0",
    "termsHash": "9169c5aaa73aac3884f693dd6b6d7552b69be7aadc6a142697ac82f806e714e2",
    "fields": {
      "OBJECTID": "recordId"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID"
    },
    "dates": [],
    "note": "Published City Limit reference, not surveyed parcels or verification of the current legal municipal boundary.",
    "source": {
      "id": "brampton:municipality",
      "name": "Brampton — City Limit",
      "url": "https://www.arcgis.com/home/item.html?id=d837bf1134444bf1b22d69257480dfd0",
      "licence": "CC BY 4.0",
      "licenceUrl": "https://creativecommons.org/licenses/by/4.0/",
      "attribution": "City of Brampton. Contains information licensed under CC BY 4.0; selected attributes are renamed and dates reformatted by Homies / Realist. No City endorsement."
    }
  },
  {
    "key": "permits",
    "item": "f1c647c68b0f429a8575f200a803bce8",
    "itemUrl": "https://maps1.brampton.ca/arcgis/rest/services/BuildingPermit/Building_Permits/MapServer/0",
    "expectedItemType": "Feature Service",
    "expectedItemTitle": "Building Permits",
    "expectedAccessInformation": "City of Brampton",
    "rootUrl": "https://maps1.brampton.ca/arcgis/rest/services/BuildingPermit/Building_Permits/MapServer",
    "url": "https://maps1.brampton.ca/arcgis/rest/services/BuildingPermit/Building_Permits/MapServer/0",
    "child": 0,
    "expectedLayerName": "Building Permits",
    "childType": "Feature Layer",
    "geometry": "esriGeometryPoint",
    "oid": "OBJECTID",
    "expectedRootServiceItem": null,
    "expectedServiceItem": null,
    "expectedRootCopyright": "",
    "expectedCopyright": "City of Brampton",
    "rootDescriptionHash": "a972fff3e8442a80c501e66838fb6714bc1dea2f66ee5f8c7c20dd971eb2d616",
    "descriptionHash": "b29f09e8e072403575446c1d895b60169962bf97fe7f44eaa79eeefdf8b1d591",
    "itemDescriptionHash": "b29f09e8e072403575446c1d895b60169962bf97fe7f44eaa79eeefdf8b1d591",
    "termsHash": "9169c5aaa73aac3884f693dd6b6d7552b69be7aadc6a142697ac82f806e714e2",
    "fields": {
      "OBJECTID": "recordId",
      "ADDRESS": "publishedAddress",
      "FOLDERRSN": "publishedFolderId",
      "PERMITNUMBER": "publishedPermitNumber",
      "SUBDESC": "publishedSubtype",
      "WORKDESC": "publishedWork",
      "ISSUEDATE": "publishedIssuedDate",
      "INDATE": "publishedInputDate",
      "STATUSDESC": "publishedStatus",
      "PROCESSDATE": "publishedProcessDate",
      "EXPIRYDATE": "publishedExpiryDate",
      "GFA": "publishedGrossFloorAreaRaw",
      "SECOND_UNIT": "publishedSecondUnitRaw",
      "BEDROOMS": "publishedBedroomsRaw",
      "STOREYS": "publishedStoreysRaw",
      "DWELLINGS": "publishedDwellingsRaw"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "ADDRESS": "esriFieldTypeString",
      "FOLDERRSN": "esriFieldTypeDouble",
      "PERMITNUMBER": "esriFieldTypeString",
      "SUBDESC": "esriFieldTypeString",
      "WORKDESC": "esriFieldTypeString",
      "ISSUEDATE": "esriFieldTypeDate",
      "INDATE": "esriFieldTypeDate",
      "STATUSDESC": "esriFieldTypeString",
      "PROCESSDATE": "esriFieldTypeDate",
      "EXPIRYDATE": "esriFieldTypeDate",
      "GFA": "esriFieldTypeString",
      "SECOND_UNIT": "esriFieldTypeString",
      "BEDROOMS": "esriFieldTypeString",
      "STOREYS": "esriFieldTypeString",
      "DWELLINGS": "esriFieldTypeString"
    },
    "dates": [
      "ISSUEDATE",
      "INDATE",
      "PROCESSDATE",
      "EXPIRYDATE"
    ],
    "matchField": "ADDRESS",
    "note": "Exact civic-address permit observations. Preserve permit/folder IDs, raw status, work and separate issue/input/process/expiry dates. Raw GFA, bedroom, storey, dwelling and second-unit fields are unverified strings, not measured building facts or current legal unit counts. Full history, final inspection and occupancy are unverified.",
    "source": {
      "id": "brampton:permits",
      "name": "Brampton — Building Permits",
      "url": "https://www.arcgis.com/home/item.html?id=f1c647c68b0f429a8575f200a803bce8",
      "licence": "CC BY 4.0",
      "licenceUrl": "https://creativecommons.org/licenses/by/4.0/",
      "attribution": "City of Brampton. Contains information licensed under CC BY 4.0; selected attributes are renamed and dates reformatted by Homies / Realist. No City endorsement."
    }
  },
  {
    "key": "permitActivities",
    "item": "e655e590937a487aab54ff6a4091a8a4",
    "itemUrl": "https://maps1.brampton.ca/arcgis/rest/services/BuildingPermit/Building_Permits/MapServer/1",
    "expectedItemType": "Feature Service",
    "expectedItemTitle": "Building Permit Activities",
    "expectedAccessInformation": "City of Brampton",
    "rootUrl": "https://maps1.brampton.ca/arcgis/rest/services/BuildingPermit/Building_Permits/MapServer",
    "url": "https://maps1.brampton.ca/arcgis/rest/services/BuildingPermit/Building_Permits/MapServer/1",
    "child": 1,
    "expectedLayerName": "Building Permits Activity",
    "childType": "Table",
    "geometry": null,
    "oid": "OBJECTID",
    "expectedRootServiceItem": null,
    "expectedServiceItem": null,
    "expectedRootCopyright": "",
    "expectedCopyright": "",
    "rootDescriptionHash": "a972fff3e8442a80c501e66838fb6714bc1dea2f66ee5f8c7c20dd971eb2d616",
    "descriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "itemDescriptionHash": "7fe8ff4c07e2064ea272b1403de4ab092356a625fab0cfa3c992920679658626",
    "termsHash": "9169c5aaa73aac3884f693dd6b6d7552b69be7aadc6a142697ac82f806e714e2",
    "fields": {
      "OBJECTID": "recordId",
      "FOLDERRSN": "publishedFolderId",
      "DISPLAYORDER": "publishedDisplayOrder",
      "PROCESSRSN": "publishedProcessId",
      "PROCESSDESC": "publishedProcess",
      "STATUSDESC": "publishedStatus",
      "ACTIVITYDATE": "publishedActivityDate"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "FOLDERRSN": "esriFieldTypeDouble",
      "DISPLAYORDER": "esriFieldTypeInteger",
      "PROCESSRSN": "esriFieldTypeInteger",
      "PROCESSDESC": "esriFieldTypeString",
      "STATUSDESC": "esriFieldTypeString",
      "ACTIVITYDATE": "esriFieldTypeDate"
    },
    "dates": [
      "ACTIVITYDATE"
    ],
    "note": "Published activity rows joined only by exact safe-integer FOLDERRSN from a complete exact-address permit result. Preserve all dated process/status observations and conflicting/repeated rows. An activity labelled completed is not verified final inspection, occupancy or current permission.",
    "source": {
      "id": "brampton:permitActivities",
      "name": "Brampton — Building Permit Activities",
      "url": "https://www.arcgis.com/home/item.html?id=e655e590937a487aab54ff6a4091a8a4",
      "licence": "CC BY 4.0",
      "licenceUrl": "https://creativecommons.org/licenses/by/4.0/",
      "attribution": "City of Brampton. Contains information licensed under CC BY 4.0; selected attributes are renamed and dates reformatted by Homies / Realist. No City endorsement."
    }
  },
  {
    "key": "heritageDetails",
    "item": "6a4c6f9af0104e12941d67251e20ab8b",
    "itemUrl": "https://services3.arcgis.com/rl7ACuZkiFsmDA2g/arcgis/rest/services/Planning_Local_Government/FeatureServer/2",
    "expectedItemType": "Feature Service",
    "expectedItemTitle": "Heritage Points",
    "expectedAccessInformation": "City of Brampton",
    "rootUrl": "https://services3.arcgis.com/rl7ACuZkiFsmDA2g/arcgis/rest/services/Planning_Local_Government/FeatureServer",
    "url": "https://services3.arcgis.com/rl7ACuZkiFsmDA2g/arcgis/rest/services/Planning_Local_Government/FeatureServer/2",
    "child": 2,
    "expectedLayerName": "Heritage Points",
    "childType": "Feature Layer",
    "geometry": "esriGeometryPoint",
    "oid": "OBJECTID",
    "expectedRootServiceItem": "584b6af140ff4db3a52382d999c1ad65",
    "expectedServiceItem": "584b6af140ff4db3a52382d999c1ad65",
    "expectedRootCopyright": "City of Brampton",
    "expectedCopyright": "",
    "rootDescriptionHash": "4165000a06cd47b8a700d72381dc5fd39f477963a3af68568e2bec5eae46dbe1",
    "descriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "itemDescriptionHash": "6d12075f2936c8875a2969fe905a1de5d42619f5cd97f9e2005e957e5c92d654",
    "termsHash": "9169c5aaa73aac3884f693dd6b6d7552b69be7aadc6a142697ac82f806e714e2",
    "fields": {
      "OBJECTID": "recordId",
      "ADDRESS": "publishedAddress",
      "HERITAGE_STATUS": "publishedHeritageStatus",
      "DATE_OF_DESIGNATION": "publishedDesignationDate",
      "BYLAW_NUMBER": "publishedBylawNumber",
      "BUILT_HERITAGE": "publishedBuiltHeritage",
      "NATURAL_HERITAGE": "publishedNaturalHeritage",
      "CULTURAL_HERITAGE_LANDSCAPE": "publishedCulturalHeritageLandscape",
      "ONT_HERITAGE_ACT": "publishedHeritageActReference",
      "ARCHITECTURE_STYLE": "publishedArchitectureStyle",
      "CONSTRUCTION_DATE": "publishedConstructionDateRaw"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "ADDRESS": "esriFieldTypeString",
      "HERITAGE_STATUS": "esriFieldTypeString",
      "DATE_OF_DESIGNATION": "esriFieldTypeDate",
      "BYLAW_NUMBER": "esriFieldTypeString",
      "BUILT_HERITAGE": "esriFieldTypeString",
      "NATURAL_HERITAGE": "esriFieldTypeString",
      "CULTURAL_HERITAGE_LANDSCAPE": "esriFieldTypeString",
      "ONT_HERITAGE_ACT": "esriFieldTypeString",
      "ARCHITECTURE_STYLE": "esriFieldTypeString",
      "CONSTRUCTION_DATE": "esriFieldTypeString"
    },
    "dates": [
      "DATE_OF_DESIGNATION"
    ],
    "matchField": "ADDRESS",
    "note": "Exact-address heritage detail observations, separate from the existing refreshed heritage-property snapshot. Preserve raw listed/designated status, bylaw/date/Act references and construction-date text; current designation, demolition/alteration obligations and building age require City instruments.",
    "source": {
      "id": "brampton:heritageDetails",
      "name": "Brampton — Heritage Points",
      "url": "https://www.arcgis.com/home/item.html?id=6a4c6f9af0104e12941d67251e20ab8b",
      "licence": "CC BY 4.0",
      "licenceUrl": "https://creativecommons.org/licenses/by/4.0/",
      "attribution": "City of Brampton. Contains information licensed under CC BY 4.0; selected attributes are renamed and dates reformatted by Homies / Realist. No City endorsement."
    }
  },
  {
    "key": "ward",
    "item": "61b3e12fb4d74d078a15512dc3baf568",
    "itemUrl": "https://services3.arcgis.com/rl7ACuZkiFsmDA2g/arcgis/rest/services/Planning_Local_Government/FeatureServer/3",
    "expectedItemType": "Feature Service",
    "expectedItemTitle": "Ward Boundaries",
    "expectedAccessInformation": "City of Brampton",
    "rootUrl": "https://services3.arcgis.com/rl7ACuZkiFsmDA2g/arcgis/rest/services/Planning_Local_Government/FeatureServer",
    "url": "https://services3.arcgis.com/rl7ACuZkiFsmDA2g/arcgis/rest/services/Planning_Local_Government/FeatureServer/3",
    "child": 3,
    "expectedLayerName": "Ward Boundaries",
    "childType": "Feature Layer",
    "geometry": "esriGeometryPolygon",
    "oid": "OBJECTID",
    "expectedRootServiceItem": "584b6af140ff4db3a52382d999c1ad65",
    "expectedServiceItem": "584b6af140ff4db3a52382d999c1ad65",
    "expectedRootCopyright": "City of Brampton",
    "expectedCopyright": "City of Brampton",
    "rootDescriptionHash": "4165000a06cd47b8a700d72381dc5fd39f477963a3af68568e2bec5eae46dbe1",
    "descriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "itemDescriptionHash": "c0af192bb0504dad43c47426252b04b470caf030f9886c215e01e8bde5b65138",
    "termsHash": "9169c5aaa73aac3884f693dd6b6d7552b69be7aadc6a142697ac82f806e714e2",
    "fields": {
      "OBJECTID": "recordId",
      "WARD": "publishedWard",
      "ELECTORAL_AREA": "publishedElectoralArea"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "WARD": "esriFieldTypeString",
      "ELECTORAL_AREA": "esriFieldTypeString"
    },
    "dates": [],
    "note": "Published ward reference described as boundaries from December 1, 2014. Current election/legal boundaries and councillor identity are unverified.",
    "source": {
      "id": "brampton:ward",
      "name": "Brampton — Ward Boundaries",
      "url": "https://www.arcgis.com/home/item.html?id=61b3e12fb4d74d078a15512dc3baf568",
      "licence": "CC BY 4.0",
      "licenceUrl": "https://creativecommons.org/licenses/by/4.0/",
      "attribution": "City of Brampton. Contains information licensed under CC BY 4.0; selected attributes are renamed and dates reformatted by Homies / Realist. No City endorsement."
    }
  },
  {
    "key": "consentToSever",
    "item": "a9bc9e70bd7c4587bcfe6400a9f2f138",
    "itemUrl": "https://services3.arcgis.com/rl7ACuZkiFsmDA2g/arcgis/rest/services/Planning_Land_Use_Development/FeatureServer/5",
    "expectedItemType": "Feature Service",
    "expectedItemTitle": "Consent to Sever",
    "expectedAccessInformation": "City of Brampton",
    "rootUrl": "https://services3.arcgis.com/rl7ACuZkiFsmDA2g/arcgis/rest/services/Planning_Land_Use_Development/FeatureServer",
    "url": "https://services3.arcgis.com/rl7ACuZkiFsmDA2g/arcgis/rest/services/Planning_Land_Use_Development/FeatureServer/5",
    "child": 5,
    "expectedLayerName": "Consent to Sever",
    "childType": "Feature Layer",
    "geometry": "esriGeometryPolygon",
    "oid": "POLY_ID",
    "expectedRootServiceItem": "6b38d99be0484aada17668992f51e3c7",
    "expectedServiceItem": "6b38d99be0484aada17668992f51e3c7",
    "expectedRootCopyright": "City of Brampton",
    "expectedCopyright": "City of Brampton",
    "rootDescriptionHash": "b987ca29a703714de13a849f69bcdf644204d5dc6578755b6e66275e52e4889b",
    "descriptionHash": "039fa68d74cdf815a42da566de42ef6bea2c61960bb526d915cb820327f68718",
    "itemDescriptionHash": "3416865e5d0297c76f9cd06e2f35adc434bd8a460b701d4f1f528dbc6bc04019",
    "termsHash": "9169c5aaa73aac3884f693dd6b6d7552b69be7aadc6a142697ac82f806e714e2",
    "fields": {
      "POLY_ID": "recordId",
      "FILE_NUMBER": "publishedFileNumber",
      "REGIONAL_NUMBER": "publishedRegionalFileNumber",
      "LOCATION": "publishedLocation",
      "DATE_RECEIVED": "publishedReceivedDate",
      "APPLICATION_TYPE": "publishedApplicationType",
      "STATUS": "publishedStatus",
      "WARD": "publishedWard"
    },
    "fieldTypes": {
      "POLY_ID": "esriFieldTypeOID",
      "FILE_NUMBER": "esriFieldTypeString",
      "REGIONAL_NUMBER": "esriFieldTypeString",
      "LOCATION": "esriFieldTypeString",
      "DATE_RECEIVED": "esriFieldTypeDate",
      "APPLICATION_TYPE": "esriFieldTypeString",
      "STATUS": "esriFieldTypeString",
      "WARD": "esriFieldTypeString"
    },
    "dates": [
      "DATE_RECEIVED"
    ],
    "planningApplication": true,
    "licenceParent": "6b38d99be0484aada17668992f51e3c7",
    "note": "Published consent to sever polygons intersecting the screened point. Keep file number, location, received date, application type and raw status separate. GIS row IDs are not parcel identity; approval labels do not establish current decisions, cleared conditions/appeals, legal severance, registration, final inspection or development permission.",
    "source": {
      "id": "brampton:consentToSever",
      "name": "Brampton — Consent to Sever",
      "url": "https://www.arcgis.com/home/item.html?id=a9bc9e70bd7c4587bcfe6400a9f2f138",
      "licence": "CC BY 4.0",
      "licenceUrl": "https://creativecommons.org/licenses/by/4.0/",
      "attribution": "City of Brampton. Contains information licensed under CC BY 4.0; selected attributes are renamed and dates reformatted by Homies / Realist. No City endorsement."
    }
  },
  {
    "key": "developmentPermitApplications",
    "item": "6a47cf8918ca4b83b74980372ab7a4e6",
    "itemUrl": "https://services3.arcgis.com/rl7ACuZkiFsmDA2g/arcgis/rest/services/Planning_Land_Use_Development/FeatureServer/6",
    "expectedItemType": "Feature Service",
    "expectedItemTitle": "Development Permit System",
    "expectedAccessInformation": "City of Brampton",
    "rootUrl": "https://services3.arcgis.com/rl7ACuZkiFsmDA2g/arcgis/rest/services/Planning_Land_Use_Development/FeatureServer",
    "url": "https://services3.arcgis.com/rl7ACuZkiFsmDA2g/arcgis/rest/services/Planning_Land_Use_Development/FeatureServer/6",
    "child": 6,
    "expectedLayerName": "Development Permit System",
    "childType": "Feature Layer",
    "geometry": "esriGeometryPolygon",
    "oid": "POLY_ID",
    "expectedRootServiceItem": "6b38d99be0484aada17668992f51e3c7",
    "expectedServiceItem": "6b38d99be0484aada17668992f51e3c7",
    "expectedRootCopyright": "City of Brampton",
    "expectedCopyright": "City of Brampton",
    "rootDescriptionHash": "b987ca29a703714de13a849f69bcdf644204d5dc6578755b6e66275e52e4889b",
    "descriptionHash": "76f9ba0f8c5f5ab3139285aba5d5696fe0c91ee8c862b579bb4bd55f575b6430",
    "itemDescriptionHash": "9d260c0162f0ae5a4d5cb35e5bf488a7907f6e607c2699a6148006d6a37f5f0b",
    "termsHash": "9169c5aaa73aac3884f693dd6b6d7552b69be7aadc6a142697ac82f806e714e2",
    "fields": {
      "POLY_ID": "recordId",
      "FILE_NUMBER": "publishedFileNumber",
      "REGIONAL_NUMBER": "publishedRegionalFileNumber",
      "LOCATION": "publishedLocation",
      "DATE_RECEIVED": "publishedReceivedDate",
      "APPLICATION_TYPE": "publishedApplicationType",
      "STATUS": "publishedStatus",
      "WARD": "publishedWard"
    },
    "fieldTypes": {
      "POLY_ID": "esriFieldTypeOID",
      "FILE_NUMBER": "esriFieldTypeString",
      "REGIONAL_NUMBER": "esriFieldTypeString",
      "LOCATION": "esriFieldTypeString",
      "DATE_RECEIVED": "esriFieldTypeDate",
      "APPLICATION_TYPE": "esriFieldTypeString",
      "STATUS": "esriFieldTypeString",
      "WARD": "esriFieldTypeString"
    },
    "dates": [
      "DATE_RECEIVED"
    ],
    "planningApplication": true,
    "licenceParent": "6b38d99be0484aada17668992f51e3c7",
    "note": "Published development permit applications polygons intersecting the screened point. Keep file number, location, received date, application type and raw status separate. GIS row IDs are not parcel identity; approval labels do not establish current decisions, cleared conditions/appeals, legal severance, registration, final inspection or development permission.",
    "source": {
      "id": "brampton:developmentPermitApplications",
      "name": "Brampton — Development Permit System",
      "url": "https://www.arcgis.com/home/item.html?id=6a47cf8918ca4b83b74980372ab7a4e6",
      "licence": "CC BY 4.0",
      "licenceUrl": "https://creativecommons.org/licenses/by/4.0/",
      "attribution": "City of Brampton. Contains information licensed under CC BY 4.0; selected attributes are renamed and dates reformatted by Homies / Realist. No City endorsement."
    }
  },
  {
    "key": "draftCondominiumApplications",
    "item": "d7de0f885829431f839d3b4624366158",
    "itemUrl": "https://services3.arcgis.com/rl7ACuZkiFsmDA2g/ArcGIS/rest/services/Planning_Land_Use_Development/FeatureServer/7",
    "expectedItemType": "Feature Service",
    "expectedItemTitle": "Draft Plan of Condominium",
    "expectedAccessInformation": "City of Brampton",
    "rootUrl": "https://services3.arcgis.com/rl7ACuZkiFsmDA2g/ArcGIS/rest/services/Planning_Land_Use_Development/FeatureServer",
    "url": "https://services3.arcgis.com/rl7ACuZkiFsmDA2g/ArcGIS/rest/services/Planning_Land_Use_Development/FeatureServer/7",
    "child": 7,
    "expectedLayerName": "Draft Plan of Condo",
    "childType": "Feature Layer",
    "geometry": "esriGeometryPolygon",
    "oid": "POLY_ID",
    "expectedRootServiceItem": "6b38d99be0484aada17668992f51e3c7",
    "expectedServiceItem": "6b38d99be0484aada17668992f51e3c7",
    "expectedRootCopyright": "City of Brampton",
    "expectedCopyright": "City of Brampton",
    "rootDescriptionHash": "b987ca29a703714de13a849f69bcdf644204d5dc6578755b6e66275e52e4889b",
    "descriptionHash": "3865985504dd287a4b01ddf7daf86928cc7d06854f1ca1dbf4afca2a1e15977c",
    "itemDescriptionHash": "f514fbd20c2a9d5e8a51c13eb1c5b432d9e53e6784697d9198939bd330033b8b",
    "termsHash": "9169c5aaa73aac3884f693dd6b6d7552b69be7aadc6a142697ac82f806e714e2",
    "fields": {
      "POLY_ID": "recordId",
      "FILE_NUMBER": "publishedFileNumber",
      "REGIONAL_NUMBER": "publishedRegionalFileNumber",
      "LOCATION": "publishedLocation",
      "DATE_RECEIVED": "publishedReceivedDate",
      "APPLICATION_TYPE": "publishedApplicationType",
      "STATUS": "publishedStatus",
      "WARD": "publishedWard"
    },
    "fieldTypes": {
      "POLY_ID": "esriFieldTypeOID",
      "FILE_NUMBER": "esriFieldTypeString",
      "REGIONAL_NUMBER": "esriFieldTypeString",
      "LOCATION": "esriFieldTypeString",
      "DATE_RECEIVED": "esriFieldTypeDate",
      "APPLICATION_TYPE": "esriFieldTypeString",
      "STATUS": "esriFieldTypeString",
      "WARD": "esriFieldTypeString"
    },
    "dates": [
      "DATE_RECEIVED"
    ],
    "planningApplication": true,
    "licenceParent": "6b38d99be0484aada17668992f51e3c7",
    "note": "Published draft condominium applications polygons intersecting the screened point. Keep file number, location, received date, application type and raw status separate. GIS row IDs are not parcel identity; approval labels do not establish current decisions, cleared conditions/appeals, legal severance, registration, final inspection or development permission.",
    "source": {
      "id": "brampton:draftCondominiumApplications",
      "name": "Brampton — Draft Plan of Condominium",
      "url": "https://www.arcgis.com/home/item.html?id=d7de0f885829431f839d3b4624366158",
      "licence": "CC BY 4.0",
      "licenceUrl": "https://creativecommons.org/licenses/by/4.0/",
      "attribution": "City of Brampton. Contains information licensed under CC BY 4.0; selected attributes are renamed and dates reformatted by Homies / Realist. No City endorsement."
    }
  },
  {
    "key": "variance",
    "item": "7a3f7464562b488c9f39ab2243a405e9",
    "itemUrl": "https://services3.arcgis.com/rl7ACuZkiFsmDA2g/ArcGIS/rest/services/Planning_Land_Use_Development/FeatureServer/8",
    "expectedItemType": "Feature Service",
    "expectedItemTitle": "Minor Variance",
    "expectedAccessInformation": "City of Brampton",
    "rootUrl": "https://services3.arcgis.com/rl7ACuZkiFsmDA2g/ArcGIS/rest/services/Planning_Land_Use_Development/FeatureServer",
    "url": "https://services3.arcgis.com/rl7ACuZkiFsmDA2g/ArcGIS/rest/services/Planning_Land_Use_Development/FeatureServer/8",
    "child": 8,
    "expectedLayerName": "Minor Variance",
    "childType": "Feature Layer",
    "geometry": "esriGeometryPolygon",
    "oid": "POLY_ID",
    "expectedRootServiceItem": "6b38d99be0484aada17668992f51e3c7",
    "expectedServiceItem": "6b38d99be0484aada17668992f51e3c7",
    "expectedRootCopyright": "City of Brampton",
    "expectedCopyright": "City of Brampton",
    "rootDescriptionHash": "b987ca29a703714de13a849f69bcdf644204d5dc6578755b6e66275e52e4889b",
    "descriptionHash": "fc65f21387ac83f6b30d72787aa37f5656a0314d79cd2a133ae7efd356955aa9",
    "itemDescriptionHash": "a1cd905add275ce27a4eb2c19ee59a8a0e58c5d0c218ac064bb188a883da1b8e",
    "termsHash": "9169c5aaa73aac3884f693dd6b6d7552b69be7aadc6a142697ac82f806e714e2",
    "fields": {
      "POLY_ID": "recordId",
      "FILE_NUMBER": "publishedFileNumber",
      "REGIONAL_NUMBER": "publishedRegionalFileNumber",
      "LOCATION": "publishedLocation",
      "DATE_RECEIVED": "publishedReceivedDate",
      "APPLICATION_TYPE": "publishedApplicationType",
      "STATUS": "publishedStatus",
      "WARD": "publishedWard"
    },
    "fieldTypes": {
      "POLY_ID": "esriFieldTypeOID",
      "FILE_NUMBER": "esriFieldTypeString",
      "REGIONAL_NUMBER": "esriFieldTypeString",
      "LOCATION": "esriFieldTypeString",
      "DATE_RECEIVED": "esriFieldTypeDate",
      "APPLICATION_TYPE": "esriFieldTypeString",
      "STATUS": "esriFieldTypeString",
      "WARD": "esriFieldTypeString"
    },
    "dates": [
      "DATE_RECEIVED"
    ],
    "planningApplication": true,
    "licenceParent": "6b38d99be0484aada17668992f51e3c7",
    "note": "Published variance polygons intersecting the screened point. Keep file number, location, received date, application type and raw status separate. GIS row IDs are not parcel identity; approval labels do not establish current decisions, cleared conditions/appeals, legal severance, registration, final inspection or development permission.",
    "source": {
      "id": "brampton:variance",
      "name": "Brampton — Minor Variance",
      "url": "https://www.arcgis.com/home/item.html?id=7a3f7464562b488c9f39ab2243a405e9",
      "licence": "CC BY 4.0",
      "licenceUrl": "https://creativecommons.org/licenses/by/4.0/",
      "attribution": "City of Brampton. Contains information licensed under CC BY 4.0; selected attributes are renamed and dates reformatted by Homies / Realist. No City endorsement."
    }
  },
  {
    "key": "planningApplications",
    "item": "fe228c35bac14b03bfed732ababbb06d",
    "itemUrl": "https://services3.arcgis.com/rl7ACuZkiFsmDA2g/ArcGIS/rest/services/Planning_Land_Use_Development/FeatureServer/9",
    "expectedItemType": "Feature Service",
    "expectedItemTitle": "OPA ZBA Subdivision",
    "expectedAccessInformation": "City of Brampton",
    "rootUrl": "https://services3.arcgis.com/rl7ACuZkiFsmDA2g/ArcGIS/rest/services/Planning_Land_Use_Development/FeatureServer",
    "url": "https://services3.arcgis.com/rl7ACuZkiFsmDA2g/ArcGIS/rest/services/Planning_Land_Use_Development/FeatureServer/9",
    "child": 9,
    "expectedLayerName": "OPA ZBA Subdivision",
    "childType": "Feature Layer",
    "geometry": "esriGeometryPolygon",
    "oid": "POLY_ID",
    "expectedRootServiceItem": "6b38d99be0484aada17668992f51e3c7",
    "expectedServiceItem": "6b38d99be0484aada17668992f51e3c7",
    "expectedRootCopyright": "City of Brampton",
    "expectedCopyright": "City of Brampton",
    "rootDescriptionHash": "b987ca29a703714de13a849f69bcdf644204d5dc6578755b6e66275e52e4889b",
    "descriptionHash": "2bad0b460e5da3d2ec499446f87a2cc951b17d64c6f62f7ae51380661f6b3b77",
    "itemDescriptionHash": "37946701a70b3fd7abe30da166b2a97a9c334e852deaf63bfd06df28c1a39c03",
    "termsHash": "9169c5aaa73aac3884f693dd6b6d7552b69be7aadc6a142697ac82f806e714e2",
    "fields": {
      "POLY_ID": "recordId",
      "FILE_NUMBER": "publishedFileNumber",
      "REGIONAL_NUMBER": "publishedRegionalFileNumber",
      "LOCATION": "publishedLocation",
      "DATE_RECEIVED": "publishedReceivedDate",
      "APPLICATION_TYPE": "publishedApplicationType",
      "STATUS": "publishedStatus",
      "WARD": "publishedWard"
    },
    "fieldTypes": {
      "POLY_ID": "esriFieldTypeOID",
      "FILE_NUMBER": "esriFieldTypeString",
      "REGIONAL_NUMBER": "esriFieldTypeString",
      "LOCATION": "esriFieldTypeString",
      "DATE_RECEIVED": "esriFieldTypeDate",
      "APPLICATION_TYPE": "esriFieldTypeString",
      "STATUS": "esriFieldTypeString",
      "WARD": "esriFieldTypeString"
    },
    "dates": [
      "DATE_RECEIVED"
    ],
    "planningApplication": true,
    "licenceParent": "6b38d99be0484aada17668992f51e3c7",
    "note": "Published planning applications polygons intersecting the screened point. Keep file number, location, received date, application type and raw status separate. GIS row IDs are not parcel identity; approval labels do not establish current decisions, cleared conditions/appeals, legal severance, registration, final inspection or development permission.",
    "source": {
      "id": "brampton:planningApplications",
      "name": "Brampton — OPA ZBA Subdivision",
      "url": "https://www.arcgis.com/home/item.html?id=fe228c35bac14b03bfed732ababbb06d",
      "licence": "CC BY 4.0",
      "licenceUrl": "https://creativecommons.org/licenses/by/4.0/",
      "attribution": "City of Brampton. Contains information licensed under CC BY 4.0; selected attributes are renamed and dates reformatted by Homies / Realist. No City endorsement."
    }
  },
  {
    "key": "preConsultation",
    "item": "6dbde95afccd49bbb510ab4c7017eb7d",
    "itemUrl": "https://services3.arcgis.com/rl7ACuZkiFsmDA2g/ArcGIS/rest/services/Planning_Land_Use_Development/FeatureServer/10",
    "expectedItemType": "Feature Service",
    "expectedItemTitle": "Pre Consultation",
    "expectedAccessInformation": "City of Brampton",
    "rootUrl": "https://services3.arcgis.com/rl7ACuZkiFsmDA2g/ArcGIS/rest/services/Planning_Land_Use_Development/FeatureServer",
    "url": "https://services3.arcgis.com/rl7ACuZkiFsmDA2g/ArcGIS/rest/services/Planning_Land_Use_Development/FeatureServer/10",
    "child": 10,
    "expectedLayerName": "Pre Consultation",
    "childType": "Feature Layer",
    "geometry": "esriGeometryPolygon",
    "oid": "POLY_ID",
    "expectedRootServiceItem": "6b38d99be0484aada17668992f51e3c7",
    "expectedServiceItem": "6b38d99be0484aada17668992f51e3c7",
    "expectedRootCopyright": "City of Brampton",
    "expectedCopyright": "City of Brampton",
    "rootDescriptionHash": "b987ca29a703714de13a849f69bcdf644204d5dc6578755b6e66275e52e4889b",
    "descriptionHash": "a58ed9b58e645e88f5470535dbd8ca8ae422f7700b5da17e2e289907047e1f9f",
    "itemDescriptionHash": "eacc3d220317db39d1df727a3a7b5334070adc2a73db688d404231d0134b46a8",
    "termsHash": "9169c5aaa73aac3884f693dd6b6d7552b69be7aadc6a142697ac82f806e714e2",
    "fields": {
      "POLY_ID": "recordId",
      "FILE_NUMBER": "publishedFileNumber",
      "REGIONAL_NUMBER": "publishedRegionalFileNumber",
      "LOCATION": "publishedLocation",
      "DATE_RECEIVED": "publishedReceivedDate",
      "APPLICATION_TYPE": "publishedApplicationType",
      "STATUS": "publishedStatus",
      "WARD": "publishedWard"
    },
    "fieldTypes": {
      "POLY_ID": "esriFieldTypeOID",
      "FILE_NUMBER": "esriFieldTypeString",
      "REGIONAL_NUMBER": "esriFieldTypeString",
      "LOCATION": "esriFieldTypeString",
      "DATE_RECEIVED": "esriFieldTypeDate",
      "APPLICATION_TYPE": "esriFieldTypeString",
      "STATUS": "esriFieldTypeString",
      "WARD": "esriFieldTypeString"
    },
    "dates": [
      "DATE_RECEIVED"
    ],
    "planningApplication": true,
    "licenceParent": "6b38d99be0484aada17668992f51e3c7",
    "note": "Published pre consultation polygons intersecting the screened point. Keep file number, location, received date, application type and raw status separate. GIS row IDs are not parcel identity; approval labels do not establish current decisions, cleared conditions/appeals, legal severance, registration, final inspection or development permission.",
    "source": {
      "id": "brampton:preConsultation",
      "name": "Brampton — Pre Consultation",
      "url": "https://www.arcgis.com/home/item.html?id=6dbde95afccd49bbb510ab4c7017eb7d",
      "licence": "CC BY 4.0",
      "licenceUrl": "https://creativecommons.org/licenses/by/4.0/",
      "attribution": "City of Brampton. Contains information licensed under CC BY 4.0; selected attributes are renamed and dates reformatted by Homies / Realist. No City endorsement."
    }
  },
  {
    "key": "sitePlanApplications",
    "item": "63c2acbac6e74daaad23aa1d2787f90a",
    "itemUrl": "https://services3.arcgis.com/rl7ACuZkiFsmDA2g/ArcGIS/rest/services/Planning_Land_Use_Development/FeatureServer/11",
    "expectedItemType": "Feature Service",
    "expectedItemTitle": "Site Plan Approval",
    "expectedAccessInformation": "City of Brampton",
    "rootUrl": "https://services3.arcgis.com/rl7ACuZkiFsmDA2g/ArcGIS/rest/services/Planning_Land_Use_Development/FeatureServer",
    "url": "https://services3.arcgis.com/rl7ACuZkiFsmDA2g/ArcGIS/rest/services/Planning_Land_Use_Development/FeatureServer/11",
    "child": 11,
    "expectedLayerName": "Site Plan Approval",
    "childType": "Feature Layer",
    "geometry": "esriGeometryPolygon",
    "oid": "POLY_ID",
    "expectedRootServiceItem": "6b38d99be0484aada17668992f51e3c7",
    "expectedServiceItem": "6b38d99be0484aada17668992f51e3c7",
    "expectedRootCopyright": "City of Brampton",
    "expectedCopyright": "City of Brampton",
    "rootDescriptionHash": "b987ca29a703714de13a849f69bcdf644204d5dc6578755b6e66275e52e4889b",
    "descriptionHash": "e2e41861d4af15e705ffba40036c5a1d45fb23a01723f382f6db2de432e35b50",
    "itemDescriptionHash": "87e95e86444739ae9ee7c62d442fa4c1c12ba69587353f14b71f0903b42e59ba",
    "termsHash": "9169c5aaa73aac3884f693dd6b6d7552b69be7aadc6a142697ac82f806e714e2",
    "fields": {
      "POLY_ID": "recordId",
      "FILE_NUMBER": "publishedFileNumber",
      "REGIONAL_NUMBER": "publishedRegionalFileNumber",
      "LOCATION": "publishedLocation",
      "DATE_RECEIVED": "publishedReceivedDate",
      "APPLICATION_TYPE": "publishedApplicationType",
      "STATUS": "publishedStatus",
      "WARD": "publishedWard"
    },
    "fieldTypes": {
      "POLY_ID": "esriFieldTypeOID",
      "FILE_NUMBER": "esriFieldTypeString",
      "REGIONAL_NUMBER": "esriFieldTypeString",
      "LOCATION": "esriFieldTypeString",
      "DATE_RECEIVED": "esriFieldTypeDate",
      "APPLICATION_TYPE": "esriFieldTypeString",
      "STATUS": "esriFieldTypeString",
      "WARD": "esriFieldTypeString"
    },
    "dates": [
      "DATE_RECEIVED"
    ],
    "planningApplication": true,
    "licenceParent": "6b38d99be0484aada17668992f51e3c7",
    "note": "Published site plan applications polygons intersecting the screened point. Keep file number, location, received date, application type and raw status separate. GIS row IDs are not parcel identity; approval labels do not establish current decisions, cleared conditions/appeals, legal severance, registration, final inspection or development permission.",
    "source": {
      "id": "brampton:sitePlanApplications",
      "name": "Brampton — Site Plan Approval",
      "url": "https://www.arcgis.com/home/item.html?id=63c2acbac6e74daaad23aa1d2787f90a",
      "licence": "CC BY 4.0",
      "licenceUrl": "https://creativecommons.org/licenses/by/4.0/",
      "attribution": "City of Brampton. Contains information licensed under CC BY 4.0; selected attributes are renamed and dates reformatted by Homies / Realist. No City endorsement."
    }
  },
  {
    "key": "officialPlanReference",
    "item": "a75bad2305f64ea38ec3a873b09025dc",
    "itemUrl": "https://services3.arcgis.com/rl7ACuZkiFsmDA2g/arcgis/rest/services/Brampton_Plan_Schedule_2_Designations/FeatureServer",
    "expectedItemType": "Feature Service",
    "expectedItemTitle": "Brampton Plan Schedule 2 Designations",
    "expectedAccessInformation": "City of Brampton",
    "rootUrl": "https://services3.arcgis.com/rl7ACuZkiFsmDA2g/arcgis/rest/services/Brampton_Plan_Schedule_2_Designations/FeatureServer",
    "url": "https://services3.arcgis.com/rl7ACuZkiFsmDA2g/arcgis/rest/services/Brampton_Plan_Schedule_2_Designations/FeatureServer/3",
    "child": 3,
    "expectedLayerName": "Land Use Designations Schedule 2",
    "childType": "Feature Layer",
    "geometry": "esriGeometryPolygon",
    "oid": "OBJECTID",
    "expectedRootServiceItem": "a75bad2305f64ea38ec3a873b09025dc",
    "expectedServiceItem": "a75bad2305f64ea38ec3a873b09025dc",
    "expectedRootCopyright": "City of Brampton",
    "expectedCopyright": "City of Brampton",
    "rootDescriptionHash": "503b00955ddbe005a4456ea71377fa3fd9c0f945d81372499aa79341dd57fa04",
    "descriptionHash": "313cd5d4b611f1317306b7d05f12de435180c036e9a55b12999bbea260cddcf9",
    "itemDescriptionHash": "503b00955ddbe005a4456ea71377fa3fd9c0f945d81372499aa79341dd57fa04",
    "termsHash": "9169c5aaa73aac3884f693dd6b6d7552b69be7aadc6a142697ac82f806e714e2",
    "fields": {
      "OBJECTID": "recordId",
      "D_SCH2": "publishedDesignation"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "D_SCH2": "esriFieldTypeString"
    },
    "dates": [],
    "note": "Published Brampton Plan Schedule 2 land-use designations only. July 2026 text incorporates OLT Orders of March 11 and July 6, 2026, but some policies/schedules remain under appeal and portions of the 2006 plan remain applicable. Confirm current instruments and the inherited Peel Regional Official Plan separately; GIS labels do not establish development permission.",
    "source": {
      "id": "brampton:officialPlanReference",
      "name": "Brampton — Brampton Plan Schedule 2 Designations",
      "url": "https://www.arcgis.com/home/item.html?id=a75bad2305f64ea38ec3a873b09025dc",
      "licence": "CC BY 4.0",
      "licenceUrl": "https://creativecommons.org/licenses/by/4.0/",
      "attribution": "City of Brampton. Contains information licensed under CC BY 4.0; selected attributes are renamed and dates reformatted by Homies / Realist. No City endorsement."
    }
  },
  {
    "key": "majorTransitStationArea",
    "item": "f9980ed835f748c4975b58847e9cdfe0",
    "itemUrl": "https://services3.arcgis.com/rl7ACuZkiFsmDA2g/arcgis/rest/services/Brampton_Plan_Schedule_1B_Major_Transit_Station_Areas/FeatureServer",
    "expectedItemType": "Feature Service",
    "expectedItemTitle": "Brampton Plan Schedule 1B Major Transit Station Areas",
    "expectedAccessInformation": "City of Brampton",
    "rootUrl": "https://services3.arcgis.com/rl7ACuZkiFsmDA2g/arcgis/rest/services/Brampton_Plan_Schedule_1B_Major_Transit_Station_Areas/FeatureServer",
    "url": "https://services3.arcgis.com/rl7ACuZkiFsmDA2g/arcgis/rest/services/Brampton_Plan_Schedule_1B_Major_Transit_Station_Areas/FeatureServer/2",
    "child": 2,
    "expectedLayerName": "Primary Major Transit Station Areas",
    "childType": "Feature Layer",
    "geometry": "esriGeometryPolygon",
    "oid": "OBJECTID_12",
    "expectedRootServiceItem": "f9980ed835f748c4975b58847e9cdfe0",
    "expectedServiceItem": "f9980ed835f748c4975b58847e9cdfe0",
    "expectedRootCopyright": "City of Brampton",
    "expectedCopyright": "City of Brampton",
    "rootDescriptionHash": "781cd61335f7fb77eddf8a21e5882a1dda407ae49429a74e22b969b99568e3ba",
    "descriptionHash": "29cfb37cc58a1201b5d06d7f619f5ab70ac5c871e72fe6401b248e38f9d633ad",
    "itemDescriptionHash": "bc50214abb8b14db5075aac0d530a5d59bad609bde03784b264a93acf1a0d9d8",
    "termsHash": "9169c5aaa73aac3884f693dd6b6d7552b69be7aadc6a142697ac82f806e714e2",
    "fields": {
      "OBJECTID_12": "recordId",
      "MUN": "publishedMunicipality",
      "PRIORITY": "publishedPriority",
      "MTSA_NAME": "publishedStationAreaName",
      "CORRIDOR": "publishedCorridor",
      "SECONDARY_": "publishedSecondaryPlanReference",
      "AREA_HA": "publishedSourceAreaHa",
      "TYPOLOGY": "publishedTypology",
      "TARGETDENS": "publishedTargetDensity",
      "LABEL": "publishedLabel"
    },
    "fieldTypes": {
      "OBJECTID_12": "esriFieldTypeOID",
      "MUN": "esriFieldTypeString",
      "PRIORITY": "esriFieldTypeString",
      "MTSA_NAME": "esriFieldTypeString",
      "CORRIDOR": "esriFieldTypeString",
      "SECONDARY_": "esriFieldTypeString",
      "AREA_HA": "esriFieldTypeDouble",
      "TYPOLOGY": "esriFieldTypeString",
      "TARGETDENS": "esriFieldTypeDouble",
      "LABEL": "esriFieldTypeString"
    },
    "dates": [],
    "note": "Published Schedule 1B primary MTSA polygons, separate from station label points (which are not actual station locations). Source area/density are planning-reference values, not lot area or verified permitted density. Current legal schedules, amendments and appeals remain unverified.",
    "source": {
      "id": "brampton:majorTransitStationArea",
      "name": "Brampton — Brampton Plan Schedule 1B Major Transit Station Areas",
      "url": "https://www.arcgis.com/home/item.html?id=f9980ed835f748c4975b58847e9cdfe0",
      "licence": "CC BY 4.0",
      "licenceUrl": "https://creativecommons.org/licenses/by/4.0/",
      "attribution": "City of Brampton. Contains information licensed under CC BY 4.0; selected attributes are renamed and dates reformatted by Homies / Realist. No City endorsement."
    }
  }
];
export const BRAMPTON_WITHHELD=[
  {
    "layer": "zoning",
    "url": "https://www.brampton.ca/en/Business/planning-development/zoning/Pages/ZoningOnline.aspx",
    "reason": "The City reports both 270-2004 and 14-2026 apply with the most restrictive provisions prevailing during appeals. Current reusable dual-map lineage, exact exception/hold text and tribunal outcomes are unverified; zoning permission is not inferred from plan labels."
  },
  {
    "layer": "currentPlanningInstruments",
    "url": "https://www.brampton.ca/EN/Business/planning-development/Plans-and-Policies/Pages/Official-Plan.aspx",
    "reason": "Some Brampton Plan policies/schedules remain under appeal; limited portions of the 2006 plan and inherited Peel Regional Official Plan remain applicable. Current schedules, secondary plans, legal exception/appeal boundaries and permissions require the City instruments."
  },
  {
    "layer": "rentalLicences",
    "url": "https://www.brampton.ca/EN/Business/Licensing/Residential-Rental-Licensing",
    "reason": "Registered additional residential units are separate from current rental licences. No complete reusable current rental-licence feed has been verified in this audit."
  },
  {
    "layer": "parcel",
    "url": "https://geohub.brampton.ca",
    "reason": "Current cadastral geometry, title/MPAC/Teranet rights, surveyed lot area and legal identifiers are unverified; a public map does not supply third-party reuse rights."
  },
  {
    "layer": "buildingFootprints",
    "url": "https://geohub.brampton.ca",
    "reason": "No complete reusable current building-footprint/height source and originating aerial/supplier rights have been verified."
  },
  {
    "layer": "bramptonConservationRegulation",
    "url": "https://geohub.brampton.ca",
    "reason": "Current parcel-wide CVC/TRCA regulation, floodplain, natural heritage and source-water schedules and originating reuse grants remain unverified; existing watershed screens are separate."
  },
  {
    "layer": "airportConstraints",
    "url": "https://www.arcgis.com/home/item.html?id=81581ba9a4444b58bed45cc841f80b39",
    "reason": "City-hosted GTAA/airport layers include third-party originating rights. They are not queried until the complete grant and current regulatory instrument are verified."
  },
  {
    "layer": "completePermitHistory",
    "url": "https://geohub.brampton.ca/datasets/brampton::building-permits/about",
    "reason": "Permit/activity observations are not a certified complete permit file or final inspection/occupancy record; missing records do not establish absence."
  }
];
