import type { Layer, Row } from "./model";
export interface EvidenceQuestion { topic: string; question: string; evidenceLayers: string[]; }
function municipalSummary(name:string):string|null {
  if(name==="durhamPlanning")return "Published 2024 regional planning mapping intersects the confirmed municipal point. Current municipal amendments, parcel-wide constraints and drinking-water safety remain unverified; read every nested status.";
  if(name==="municipality")return "A published municipal boundary confirms the point's requested municipality; this does not verify title or a surveyed property boundary.";
  if(name.includes("2010"))return "Historical mapping from Mississauga's repealed 2010 plan is available; it does not establish current Official Plan 2051 designations or constraints.";
  return ({heritageDistrict:"Published heritage district mapping intersects the point; verify current district and property-specific alteration requirements.",generalizedLandUse:"A generalized land-use classification is available; detailed zone codes, exceptions and permitted uses are not supplied.",primaryTransitArea:"The point is in a published Primary Transit Area; verify current service and applicable policies.",communityImprovementArea:"A published improvement-project area intersects the point; current funding and eligibility are unverified.",existingLandUse:"Published existing-use classification intersects the point; it does not establish Official Plan policy, approved uses or a legal unit count.",rentalLicences:"Issued rental-licence evidence matched the civic address. Read the published expiry and file vintage; current validity, renewal and revocation status are unverified.",community:"A published municipal community boundary intersects the point; this does not classify household or neighbourhood quality."} as Record<string,string>)[name]??null;
}
export function preShowingBrief(layers: Record<string, Layer>, questions: EvidenceQuestion[]) {
  const findings = Object.entries(layers).filter(([name, value]) => name !== "location" && value.status === "available").map(([name, value]) => {
    const d = value.data as Row | null;
    const count = d && Array.isArray(d.records) ? d.records.length : d && Array.isArray(d.applications) ? d.applications.length : null;
    const haltonSummary=name==="planningApplications"&&value.source?.id.startsWith("milton:")?`${count ?? 0} published development polygons intersect the point. These are subject-point records, not nearby quarterly observations or a full planning history; verify current file conditions and appeals.`:name==="zoning"&&value.source?.id==="burlington:zoning"?"Older Burlington zoning mapping intersects the point. Current residential zoning under By-law 09-2026 is unverified; do not treat the old label as current permission.":name==="permits"&&["oakville:permits","burlington:permits"].includes(value.source?.id??"")?`${count ?? 0} exact civic-address permit observations returned. Preserve repeated files and published statuses; full history, final inspections and occupancy remain unverified.`:name==="heritageAddressEvidence"?"Exact civic-address heritage evidence matched; verify current register, parcel identity and any separate designation or alteration requirements.":null;
    return { layer: name, summary: haltonSummary ?? (name === "permits" && value.source?.id === "ottawa:permit-reports-2024-2026" ? `${count ?? 0} Ottawa permit/address report observations returned. Read reporting month, published issued date and descriptions separately; current status and final inspections are unverified.` : municipalSummary(name) ?? (name === "development" ? `${count ?? 0} nearby applications returned within 800 m; read distance${value.source?.id.startsWith("hamilton:") ? "; this Hamilton feed does not publish stages" : " and published stage"}.` : name === "planningApplications" ? `${count ?? 0} nearby quarterly planning observations returned; read each dated decision and appeal record without inferring current permission.` : name === "heritageGrants" ? "Historic heritage-grant payment evidence matched; verify the supported work and any continuing obligations." : name === "ruralSettlement" ? "A published rural settlement boundary intersects the point; verify boundary status and current parcel policies." : name === "wastewaterCatchment" ? "The point intersects a mapped wastewater catchment; actual connection and available capacity remain unverified." : name === "provincialPlanning" ? "Preliminary provincial plan mapping intersects the point; preserve coarse published accuracy and verify legal maps. Development-control requirements are not screened.": name === "heritage" ? "Heritage inventory/register evidence matched; read the published status and applicable bylaw." : name === "trca" || name === "conservation" ? "Mapped conservation evidence intersects the screened point; confirm parcel-wide requirements." : name === "environmentalSensitivity" ? "A published environmentally sensitive area intersects the screened point; confirm parcel-wide natural heritage requirements." : name === "zoning" ? "Published zoning intersects the screened point; review the parent bylaw, exceptions and holding provisions." : name === "additionalUnits" ? "Additional-unit registration evidence matched; request the documents for the advertised unit." : name === "buildingEvaluations" ? "Dated building evaluation evidence is available; review the latest visit and history." : `${name} evidence is available${count !== null ? ` (${count} returned records)` : ""}.`)), source: value.source, sourceUpdatedAt: value.sourceUpdatedAt, retrievedAt: value.retrievedAt, importedAt: value.importedAt ?? null, truncated: value.truncated ?? false };
  });
  const documents: { document: string; evidenceLayers: string[]; reason: string }[] = [
    { document: "Current listing and seller disclosures", evidenceLayers: [], reason: "Compare advertised features and disclosures with dated public records." },
    { document: "Survey and parcel identification", evidenceLayers: ["parcel"], reason: "Verify the property boundary; point screens cannot establish parcel-wide conditions." },
  ];
  if (layers.permits?.status === "available" || layers.additionalUnits?.status === "available") documents.push({ document: "Permit file, final inspections and occupancy or unit-registration documents", evidenceLayers: ["permits", "additionalUnits"], reason: "A published permit or registration entry does not prove all work received final approval." });
  if (layers.rentalLicences?.status === "available") documents.push({ document:"Current rental licence, renewal and revocation records for the advertised unit",evidenceLayers:["rentalLicences"],reason:"An issued-record list and published expiry date do not prove a licence is currently valid." });
  if (layers.heritage?.status === "available" || layers.heritageDistrict?.status === "available" || layers.heritageAddressEvidence?.status === "available") documents.push({ document: "Heritage designation/listing documents, district plan and applicable alteration approvals", evidenceLayers: ["heritage", "heritageDistrict", "heritageAddressEvidence"], reason: "Confirm the exact status and requirements for the proposed work." });
  if (layers.zoning?.status === "available" || layers.zoning?.status === "ambiguous" || layers.generalizedLandUse) documents.push({ document: "Current zoning verification, applicable bylaws, exceptions and holding provisions", evidenceLayers: ["zoning", "generalizedLandUse"], reason: "Point GIS evidence does not establish parcel-wide zoning or permission for the proposed use." });
  if (layers.environmentalSensitivity?.status === "available") documents.push({ document: "Natural heritage studies and municipal planning confirmation", evidenceLayers: ["environmentalSensitivity"], reason: "City environmental sensitivity mapping is separate from conservation-authority regulation and parcel-wide assessment." });
  if (layers.conservation?.status === "available" || layers.trca?.status === "available") documents.push({ document: "Conservation authority confirmation and any related permits", evidenceLayers: ["conservation", "trca"], reason: "Confirm parcel-wide mapped and unmapped constraints with the authority." });
  if (layers.planningApplications?.status === "available") documents.push({ document: "Full planning file, decision conditions, appeal decision and implementation records", evidenceLayers: ["planningApplications"], reason: layers.planningApplications.source?.id.startsWith("milton:") ? "Published development-polygon status, registration and date fields do not establish current approval conditions or appeal outcomes." : "Quarterly observations can have different statuses for one file; decision dates do not establish current parcel permissions." });
  if ((layers.officialPlan?.data as Row|null)?.formerRegionalPlanBecameMunicipalDate) documents.push({document:"Current municipal and former Halton regional-plan schedules, written policies and amendments",evidenceLayers:["officialPlan","zoning","hamlet"],reason:"Halton's former regional plan became a plan of each local municipality on July 1, 2024. Zone labels, general land use, neighbourhoods and hamlet boundaries do not replace the applicable current plans and amendments."});
  if (layers.heritageGrants?.status === "available") documents.push({ document: "Historic heritage grant agreement, invoices and conservation work records", evidenceLayers: ["heritageGrants"], reason: "A reported payment does not establish work completion, current eligibility or discharge of obligations." });
  if (layers.ruralSettlement?.status === "available" || layers.provincialPlanning?.status === "available") documents.push({ document: "Current official-plan schedules and provincial legal-map confirmation", evidenceLayers: ["ruralSettlement", "provincialPlanning"], reason: "Preliminary point mapping and coarse source accuracy cannot verify a lot's legal designation or development-control requirements." });
  if (layers.wastewaterCatchment?.status === "available") documents.push({ document: "Actual sewer/septic connection records and servicing-capacity confirmation", evidenceLayers: ["wastewaterCatchment"], reason: "A treatment catchment does not prove an actual connection or available capacity." });
  if (layers.hamiltonConservation) documents.push({ document: "Conservation-authority jurisdiction, regulation confirmation and any relevant permits", evidenceLayers: ["hamiltonConservation"], reason: "Hamilton's four authority maps were not screened; verify the parcel with the relevant authority." });
  if (layers.historicalOfficialPlan2010) documents.push({ document: "Current Official Plan 2051 schedules and amendments", evidenceLayers: ["officialPlan", "historicalOfficialPlan2010"], reason: "The returned 2010 plan was repealed on March 24, 2026; a recent feed edit does not make it current policy." });
  if (layers.durhamPlanning) documents.push({ document:"Current municipal Official Plan schedules, written policies, amendments and appeal decisions",evidenceLayers:["durhamPlanning","officialPlan","zoning"],reason:"The regional service describes September 2024 consolidation mapping; remaining northeast Pickering matters were approved later and municipalities assumed plan responsibility in January 2025. Current amendments are unverified." },{document:"Current source-protection policy confirmation and actual water-supply records",evidenceLayers:["durhamPlanning"],reason:"Recharge, wellhead and intake-zone point mapping is not a flood screen, contamination finding, water-quality result or proof of an actual municipal connection."});
  if (layers.communityImprovementArea?.status === "available") documents.push({ document: "Current improvement-program guidelines, funding and written eligibility confirmation", evidenceLayers: ["communityImprovementArea"], reason: "A mapped area does not establish grant entitlement or available funding." });
  if (layers.buildingEvaluations?.status === "available") documents.push({ document: "Latest building-condition reports and evidence of corrective work", evidenceLayers: ["buildingEvaluations"], reason: "Public evaluations are dated and concern building/common areas." });
  return {
    title: "Pre-showing property forensics briefing", findings,
    listingComparison: { status: "not_provided", discrepancies: [], instruction: "If a listing or seller documents are supplied, compare specific claims against the returned evidence. Report conflicts, date differences and unknowns separately; do not infer an inconsistency without both sides." },
    documentsToRequest: documents.map(d => ({ ...d, receiptStatus: "not_assessed" })),
    sellerQuestions: questions,
    coverageGaps: Object.entries(layers).filter(([, value]) => (value.status !== "available" || (value.data as Row | null)?.coverageComplete === false)).map(([name, value]) => ({ layer: name, status: (value.data as Row | null)?.coverageComplete === false ? "incomplete" : value.status, note: value.note })),
    limitations: ["Research briefing, not an inspection, appraisal, title opinion or municipal approval.", "No-match is not proof of absence. Source/import/retrieval dates remain separate.", "Documents listed here are requests; the API has not checked what the seller already holds."],
  };
}
