import type { Source } from "./model";
export const CORNWALL_GUIDANCE = {
  catalogue: "https://data-cornwallcity.opendata.arcgis.com",
  zoning: "https://www.cornwall.ca/en/build-invest/zoning/",
  officialPlan: "https://www.cornwall.ca/en/build-invest/official-plan/",
  permits: "https://www.cornwall.ca/en/property-environment/building-and-renovations/building-permits/",
  inspections: "https://www.cornwall.ca/en/property-environment/building-and-renovations/inspections/",
  propertyReports: "https://www.cornwall.ca/en/build-invest/planning-and-development/work-order-reports-and-compliance-letters/",
  heritage: "https://www.cornwall.ca/en/recreation-community-supports/history-and-heritage/",
  planning: "https://www.cornwall.ca/en/build-invest/planning-and-development/development-applications/",
  conservation: "https://rrca.on.ca/page.php?id=158",
  waterfront: "https://rrca.on.ca/page.php?id=111",
  sourceProtection: "https://yourdrinkingwater.ca/page.php?id=12",
};
export const CORNWALL_WITHHELD = [
  { layer: "permits", reason: "Current City permit guidance and application forms do not establish a licensed public property-history feed. Complete permits, inspections and occupancy remain unqueried; request City files and a Work Order Report.", guidance: CORNWALL_GUIDANCE.permits },
  { layer: "zoning", reason: "Catalogue GIS labels remain separate from verified current written 2022-001 rules, exceptions, holds, amendments and appeals. The City-linked December 2025 office consolidation is for convenience and warns of omissions; confirm current property applicability.", guidance: CORNWALL_GUIDANCE.zoning },
  { layer: "currentPlanningInstruments", reason: "Current City guidance links a June 2025 consolidation of the 2017 Official Plan and December 2025 zoning consolidation. Full operative policies, subsequent amendments and appeal currency are not established by catalogue labels.", guidance: CORNWALL_GUIDANCE.officialPlan },
  { layer: "planningApplications", reason: "Application guidance and draft-plan catalogue candidates do not establish complete current decisions, conditions, approvals or appeals; exact usable original feed rights and schema remain to be verified.", guidance: CORNWALL_GUIDANCE.planning },
  { layer: "variance", reason: "Complete Committee of Adjustment decisions, consent registration, cleared conditions and appeals have not been queried. City Work Order and Agreement Compliance reports are separate request workflows.", guidance: CORNWALL_GUIDANCE.propertyReports },
  { layer: "heritage", reason: "The designated-sites catalogue is a dated reference. Full current designated/listed/district coverage, exact legal extents and designation/alteration instruments remain unverified; the separate City website table is not republished as an open feed.", guidance: CORNWALL_GUIDANCE.heritage },
  { layer: "additionalUnits", reason: "Advertised-unit identity, legal unit count, registration, inspections and occupancy have not been verified. Civic unit/floor/building fields, footprints and renovation guidance do not establish these facts.", guidance: CORNWALL_GUIDANCE.propertyReports },
  { layer: "parcel", reason: "City-curated approximate parcels contain assessment-roll identifiers without established original cadastral rights. The City licence excludes third-party rights; parcel records/counts/geometry, title, ownership and surveyed measurements remain unqueried.", guidance: CORNWALL_GUIDANCE.catalogue },
  { layer: "cornwallConservationRegulation", reason: "Original RRCA reusable grant, current typed regulatory lineage and parcel-wide applicability remain unverified. RRCA says mapping is updated and may require site verification; request a formal Property Inquiry and proposed-work confirmation.", guidance: CORNWALL_GUIDANCE.conservation },
  { layer: "floodplainOverlay", reason: "Original RRCA flood/hazard mapping rights, current extent and property-wide requirements remain unverified; no City zoning or plan label establishes hazard absence or clearance.", guidance: CORNWALL_GUIDANCE.conservation },
  { layer: "shorelineManagementReference", reason: "Current shoreline/dock requirements and original authority mapping rights remain unverified; confirm proposed waterfront work directly with RRCA.", guidance: CORNWALL_GUIDANCE.waterfront },
  { layer: "contaminatedSedimentReference", reason: "RRCA describes Cornwall Sediment Strategy controls along the waterfront. Exact reusable original zones, legal applicability and proposed-work review remain unverified; no contamination finding or clearance is inferred.", guidance: CORNWALL_GUIDANCE.waterfront },
  { layer: "intakeProtection", reason: "Cornwall intake-protection guidance is available, but original reusable polygons, current adopted policies and activity-specific applicability have not been verified. No water safety, connection or contamination conclusion is returned.", guidance: CORNWALL_GUIDANCE.sourceProtection },
  { layer: "airportConstraints", reason: "Original airport-height/noise instrument rights, current surfaces and parcel applicability remain unaudited. Municipal zoning and land-use labels cannot substitute for this screen.", guidance: CORNWALL_GUIDANCE.planning },
];
export interface CornwallFeed { key:string; item:string; itemUrl:string; expectedItemType:string; expectedAccessInformation:string|null; expectedCuratedOrg:string|null; rootUrl:string; url:string; child:number; expectedItemTitle:string; expectedLayerName:string; geometry:string; oid:string; expectedRootServiceItem:string; expectedServiceItem:string; expectedRootCopyright:string; expectedCopyright:string; rootDescriptionHash:string; descriptionHash:string; itemDescriptionHash:string; termsHash:string; domainsHash:string; fields:Record<string,string>; fieldTypes:Record<string,string>; matchField?:string; note:string; source:Source; }
export const CORNWALL_GRANT={
  "site": "6cead708a3124ee5a7f25868d770862d",
  "siteTitle": "City of Cornwall-Open Data Site",
  "siteType": "Web Mapping Application",
  "siteOwner": "cityofcornwall",
  "siteUrl": "https://data-cornwallcity.opendata.arcgis.com",
  "org": "tPtW2sjE3XOR63A7",
  "siteTermsHash": "d4ba15b219ed7514eaa47b640094e9dde73ab56cd4fd2cc2536d94fdb719e2b1",
  "group": "dd4414fde4f642aaba4b85069186d8c2",
  "groupTitle": "City Open Data Users",
  "groupOwner": "cityofcornwall",
  "officialOffer": "https://www.cornwall.ca/en/government-council/opendata/",
  "offerHash": "26186b5af222840a41f48754dee703b37308446b5a1aedf3a4e059c45f267404",
  "licenceUrl": "https://media-003-ca.cdn.govstack.com/cornwall-ca/media/5i0aznnd/city-of-cornwall-open-government-licence.pdf",
  "licenceHash": "46159d2d6f18984e45a18078e1dff15187f890fea4f52a992ad43e9264c8dd32"
};
export const CORNWALL_FEEDS:CornwallFeed[]=[
  {
    "key": "municipalAddresses",
    "item": "134ac6de89ff493484541b6d8a326e62",
    "itemUrl": "https://services2.arcgis.com/tPtW2sjE3XOR63A7/arcgis/rest/services/AddressPoints/FeatureServer",
    "expectedItemType": "Feature Service",
    "expectedAccessInformation": "City of Cornwall, Infrastructure Planning Division",
    "expectedCuratedOrg": null,
    "rootUrl": "https://services2.arcgis.com/tPtW2sjE3XOR63A7/arcgis/rest/services/AddressPoints/FeatureServer",
    "url": "https://services2.arcgis.com/tPtW2sjE3XOR63A7/arcgis/rest/services/AddressPoints/FeatureServer/34",
    "child": 34,
    "expectedItemTitle": "Address Points",
    "expectedLayerName": "AddressPoints",
    "geometry": "esriGeometryPoint",
    "oid": "OBJECTID",
    "expectedRootServiceItem": "134ac6de89ff493484541b6d8a326e62",
    "expectedServiceItem": "134ac6de89ff493484541b6d8a326e62",
    "expectedRootCopyright": "City of Cornwall, Infrastructure Planning Division",
    "expectedCopyright": "",
    "rootDescriptionHash": "7faf7ac8a340e27b314de8314332cb1869ad85b5f3d5106f7d574509ff0b401d",
    "descriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "itemDescriptionHash": "7faf7ac8a340e27b314de8314332cb1869ad85b5f3d5106f7d574509ff0b401d",
    "termsHash": "b79489cda2845b83f82f2017d27e15c69d10abf798d3ce6b9d459e3cb7d9277e",
    "domainsHash": "bd5f5e97c9f935d15102f7b6caca85f64cfdb73ec89c61aa8df963136553bdc9",
    "fields": {
      "OBJECTID": "recordId",
      "AddressID": "publishedAddressId",
      "ADDRESS": "publishedAddress",
      "ST_NUMBER": "publishedNumber",
      "UNIT": "publishedUnit",
      "STREET": "publishedStreet",
      "STREET_LNG": "publishedLongStreet",
      "SUFFIX": "publishedStreetSuffix",
      "DIRECTION": "publishedDirection",
      "CITY": "publishedCity",
      "PROVINCE": "publishedProvince",
      "COUNTRY": "publishedCountry",
      "FLOOR": "publishedFloor",
      "BUILDING": "publishedBuilding",
      "ADD_TYPE": "publishedAddressType",
      "LAST_EDIT": "publishedLastEdit"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "AddressID": "esriFieldTypeInteger",
      "ADDRESS": "esriFieldTypeString",
      "ST_NUMBER": "esriFieldTypeInteger",
      "UNIT": "esriFieldTypeString",
      "STREET": "esriFieldTypeString",
      "STREET_LNG": "esriFieldTypeString",
      "SUFFIX": "esriFieldTypeString",
      "DIRECTION": "esriFieldTypeString",
      "CITY": "esriFieldTypeString",
      "PROVINCE": "esriFieldTypeString",
      "COUNTRY": "esriFieldTypeString",
      "FLOOR": "esriFieldTypeString",
      "BUILDING": "esriFieldTypeString",
      "ADD_TYPE": "esriFieldTypeString",
      "LAST_EDIT": "esriFieldTypeDate"
    },
    "matchField": "ADDRESS",
    "note": "Strict unique complete civic attributes only. Preserve suffix, direction, City/province/country, unit, floor, building and raw address type distinctions. One unique complete PRIMARY record with no unresolved unit/floor/building distinction may supply its published over-building point only after exact original Ontario municipal containment. Other civic paths return attributes only; current building, legal unit and surveyed identity remain unverified.",
    "source": {
      "id": "cornwall:municipalAddresses",
      "name": "Cornwall — Address Points",
      "url": "https://www.arcgis.com/home/item.html?id=134ac6de89ff493484541b6d8a326e62",
      "licence": "Open Government Licence – City of Cornwall 2.0",
      "licenceUrl": "https://media-003-ca.cdn.govstack.com/cornwall-ca/media/5i0aznnd/city-of-cornwall-open-government-licence.pdf",
      "attribution": "Contains information licensed under the Open Government Licence – City of Cornwall. Selected attributes are renamed by Homies / Realist; no City endorsement."
    }
  },
  {
    "key": "catalogueZoningReference",
    "item": "a9a3c751549c4d7dbd114446a39f910a",
    "itemUrl": "https://services2.arcgis.com/tPtW2sjE3XOR63A7/arcgis/rest/services/Zoning/FeatureServer",
    "expectedItemType": "Feature Service",
    "expectedAccessInformation": "City of Cornwall",
    "expectedCuratedOrg": null,
    "rootUrl": "https://services2.arcgis.com/tPtW2sjE3XOR63A7/arcgis/rest/services/Zoning/FeatureServer",
    "url": "https://services2.arcgis.com/tPtW2sjE3XOR63A7/arcgis/rest/services/Zoning/FeatureServer/0",
    "child": 0,
    "expectedItemTitle": "Zoning",
    "expectedLayerName": "Zoning",
    "geometry": "esriGeometryPolygon",
    "oid": "FID",
    "expectedRootServiceItem": "a9a3c751549c4d7dbd114446a39f910a",
    "expectedServiceItem": "a9a3c751549c4d7dbd114446a39f910a",
    "expectedRootCopyright": "City of Cornwall",
    "expectedCopyright": "",
    "rootDescriptionHash": "a4468fe00d88a177ee71c2bc6a6adac5c59f6766b4f10faf4392e607e5f9b9f8",
    "descriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "itemDescriptionHash": "a4468fe00d88a177ee71c2bc6a6adac5c59f6766b4f10faf4392e607e5f9b9f8",
    "termsHash": "b79489cda2845b83f82f2017d27e15c69d10abf798d3ce6b9d459e3cb7d9277e",
    "domainsHash": "9d3744001e28468dfcc6efbf9fd4d75974f738c84beacf79c95bb92ba2ca7f8f",
    "fields": {
      "FID": "recordId",
      "Zoning": "publishedZone",
      "Zone_Type": "publishedZoneType",
      "Zone_Abb": "publishedZoneAbbreviation",
      "ZONING_LNG": "publishedLongZone"
    },
    "fieldTypes": {
      "FID": "esriFieldTypeOID",
      "Zoning": "esriFieldTypeString",
      "Zone_Type": "esriFieldTypeString",
      "Zone_Abb": "esriFieldTypeString",
      "ZONING_LNG": "esriFieldTypeString"
    },
    "note": "Published zoning labels at the verified subject point. Current City map references this feed, but legal permission, written provisions, holds/exceptions, subsequent amendments and appeal currency remain unverified.",
    "source": {
      "id": "cornwall:catalogueZoningReference",
      "name": "Cornwall — Zoning",
      "url": "https://www.arcgis.com/home/item.html?id=a9a3c751549c4d7dbd114446a39f910a",
      "licence": "Open Government Licence – City of Cornwall 2.0",
      "licenceUrl": "https://media-003-ca.cdn.govstack.com/cornwall-ca/media/5i0aznnd/city-of-cornwall-open-government-licence.pdf",
      "attribution": "Contains information licensed under the Open Government Licence – City of Cornwall. Selected attributes are renamed by Homies / Realist; no City endorsement."
    }
  },
  {
    "key": "designatedHeritageReference",
    "item": "7e4d2ad84e584cceb938711fec2f9f2c",
    "itemUrl": "https://services2.arcgis.com/tPtW2sjE3XOR63A7/arcgis/rest/services/Heritage_Cornwall_DesignatedSites/FeatureServer",
    "expectedItemType": "Feature Service",
    "expectedAccessInformation": "City of Cornwall\n",
    "expectedCuratedOrg": "tPtW2sjE3XOR63A7",
    "rootUrl": "https://services2.arcgis.com/tPtW2sjE3XOR63A7/arcgis/rest/services/Heritage_Cornwall_DesignatedSites/FeatureServer",
    "url": "https://services2.arcgis.com/tPtW2sjE3XOR63A7/arcgis/rest/services/Heritage_Cornwall_DesignatedSites/FeatureServer/0",
    "child": 0,
    "expectedItemTitle": "Heritage_Cornwall_DesignatedSites",
    "expectedLayerName": "Heritage_Cornwall_DesignatedSites",
    "geometry": "esriGeometryPoint",
    "oid": "FID",
    "expectedRootServiceItem": "7e4d2ad84e584cceb938711fec2f9f2c",
    "expectedServiceItem": "7e4d2ad84e584cceb938711fec2f9f2c",
    "expectedRootCopyright": "",
    "expectedCopyright": "",
    "rootDescriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "descriptionHash": "7eacc5d82d9ac1cbebbd0496779c336232bae2ce94195df27bed0aa0a39c43aa",
    "itemDescriptionHash": "2f2124985ec7097680b39c081f40ff802f3608f4884b2b7fce3806833a0465f8",
    "termsHash": "b79489cda2845b83f82f2017d27e15c69d10abf798d3ce6b9d459e3cb7d9277e",
    "domainsHash": "cd2adbf6f3e7a25405acbc47b0aa8ea11a868ee5b0fa820f16bfc96e139ed676",
    "fields": {
      "FID": "recordId",
      "ADDRESS": "publishedAddress",
      "NAME": "publishedName"
    },
    "fieldTypes": {
      "FID": "esriFieldTypeOID",
      "ADDRESS": "esriFieldTypeString",
      "NAME": "esriFieldTypeString"
    },
    "matchField": "ADDRESS",
    "note": "Strict civic-address reference from the designated-sites catalogue only. Preserve data vintage; no match cannot establish absence. Full current listed/designated/district register, exact legal boundary and instruments remain unverified.",
    "source": {
      "id": "cornwall:designatedHeritageReference",
      "name": "Cornwall — Heritage_Cornwall_DesignatedSites",
      "url": "https://www.arcgis.com/home/item.html?id=7e4d2ad84e584cceb938711fec2f9f2c",
      "licence": "Open Government Licence – City of Cornwall 2.0",
      "licenceUrl": "https://media-003-ca.cdn.govstack.com/cornwall-ca/media/5i0aznnd/city-of-cornwall-open-government-licence.pdf",
      "attribution": "Contains information licensed under the Open Government Licence – City of Cornwall. Selected attributes are renamed by Homies / Realist; no City endorsement."
    }
  },
  {
    "key": "buildingFootprintReference",
    "item": "a01a6165c60e4099b64db5b173376e70",
    "itemUrl": "https://services2.arcgis.com/tPtW2sjE3XOR63A7/arcgis/rest/services/Buildings/FeatureServer",
    "expectedItemType": "Feature Service",
    "expectedAccessInformation": "",
    "expectedCuratedOrg": null,
    "rootUrl": "https://services2.arcgis.com/tPtW2sjE3XOR63A7/arcgis/rest/services/Buildings/FeatureServer",
    "url": "https://services2.arcgis.com/tPtW2sjE3XOR63A7/arcgis/rest/services/Buildings/FeatureServer/0",
    "child": 0,
    "expectedItemTitle": "Buildings",
    "expectedLayerName": "Buildings",
    "geometry": "esriGeometryPolygon",
    "oid": "FID",
    "expectedRootServiceItem": "a01a6165c60e4099b64db5b173376e70",
    "expectedServiceItem": "a01a6165c60e4099b64db5b173376e70",
    "expectedRootCopyright": "",
    "expectedCopyright": "",
    "rootDescriptionHash": "af4e97246330dbef480155cc95ef3dbfbddb5f3e8cb104af4606485a5b3eba3e",
    "descriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "itemDescriptionHash": "5b835a3447db2d3f15aa79315f5737ecfd154630279fbb3fe8b66352aad1910d",
    "termsHash": "b79489cda2845b83f82f2017d27e15c69d10abf798d3ce6b9d459e3cb7d9277e",
    "domainsHash": "5ba3fb42f16a98f6cda224fc983ed37fa3c6e3a4fb1bd6dd1da7926d5c4c5d9c",
    "fields": {
      "FID": "recordId"
    },
    "fieldTypes": {
      "FID": "esriFieldTypeOID"
    },
    "note": "Footprint row identifier only. Item description claims 2022 topographic mapping; originating service description claims 2017. Preserve both, with vintage unresolved. No geometry, measured area/dimensions, storeys/usage, age, condition or legal units are returned.",
    "source": {
      "id": "cornwall:buildingFootprintReference",
      "name": "Cornwall — Buildings",
      "url": "https://www.arcgis.com/home/item.html?id=a01a6165c60e4099b64db5b173376e70",
      "licence": "Open Government Licence – City of Cornwall 2.0",
      "licenceUrl": "https://media-003-ca.cdn.govstack.com/cornwall-ca/media/5i0aznnd/city-of-cornwall-open-government-licence.pdf",
      "attribution": "Contains information licensed under the Open Government Licence – City of Cornwall. Selected attributes are renamed by Homies / Realist; no City endorsement."
    }
  },
  {
    "key": "officialPlanReference",
    "item": "daefc517461947a295b3d242e8415b54",
    "itemUrl": "https://services2.arcgis.com/tPtW2sjE3XOR63A7/arcgis/rest/services/OP_Landuse_Schedule1/FeatureServer",
    "expectedItemType": "Feature Service",
    "expectedAccessInformation": "City of Cornwall",
    "expectedCuratedOrg": null,
    "rootUrl": "https://services2.arcgis.com/tPtW2sjE3XOR63A7/arcgis/rest/services/OP_Landuse_Schedule1/FeatureServer",
    "url": "https://services2.arcgis.com/tPtW2sjE3XOR63A7/arcgis/rest/services/OP_Landuse_Schedule1/FeatureServer/0",
    "child": 0,
    "expectedItemTitle": "Official_Plan_Schedule1-Landuse",
    "expectedLayerName": "OP_Landuse_Schedule1",
    "geometry": "esriGeometryPolygon",
    "oid": "FID",
    "expectedRootServiceItem": "daefc517461947a295b3d242e8415b54",
    "expectedServiceItem": "daefc517461947a295b3d242e8415b54",
    "expectedRootCopyright": "",
    "expectedCopyright": "",
    "rootDescriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "descriptionHash": "637b9d4e7602c62e7f9329bfb3bf4a91f757572ab9d1ecf7ad27e6b570c94019",
    "itemDescriptionHash": "63e82a12eb7b3b6ce11a45123ca9c82517b7c25a93cfde8fecd9d5f39d197c1b",
    "termsHash": "b79489cda2845b83f82f2017d27e15c69d10abf798d3ce6b9d459e3cb7d9277e",
    "domainsHash": "1a3b8f62a06cdbdc2e6ba27f789898d9bff9d7bae93c891d407104299c594a2c",
    "fields": {
      "FID": "recordId",
      "Land_Use": "publishedLandUse",
      "LU_ABBREV": "publishedLandUseAbbreviation"
    },
    "fieldTypes": {
      "FID": "esriFieldTypeOID",
      "Land_Use": "esriFieldTypeString",
      "LU_ABBREV": "esriFieldTypeString"
    },
    "note": "Catalogue Schedule 1 land-use labels at the verified subject point. Written policies, current consolidation, amendments, appeals and development permission remain unverified.",
    "source": {
      "id": "cornwall:officialPlanReference",
      "name": "Cornwall — Official_Plan_Schedule1-Landuse",
      "url": "https://www.arcgis.com/home/item.html?id=daefc517461947a295b3d242e8415b54",
      "licence": "Open Government Licence – City of Cornwall 2.0",
      "licenceUrl": "https://media-003-ca.cdn.govstack.com/cornwall-ca/media/5i0aznnd/city-of-cornwall-open-government-licence.pdf",
      "attribution": "Contains information licensed under the Open Government Licence – City of Cornwall. Selected attributes are renamed by Homies / Realist; no City endorsement."
    }
  }
];
