import type { MunicipalFeed, HaltonMarket } from "./ontario-municipal-sources";

export const HALTON_PLAN_GUIDANCE = "https://www.halton.ca/the-region/supporting-land-use-planning/regional-official-plan";
export const HALTON_GUIDANCE = {
  Burlington:{ zoning:"https://www.burlington.ca/en/planning-and-development/zoning.aspx", plan:"https://www.burlington.ca/en/planning-and-development/official-plan.aspx", terms:"https://opendata.burlington.ca/opendata-terms-of-use/City%20of%20Burlington%20-%20Open%20Data%20Terms%20of%20Use.pdf", hub:"navburl-burlington.opendata.arcgis.com", owner:"GISCOB", org:"xbWF6o8qyXoMFa8L" },
  Milton:{ zoning:"https://www.milton.ca/en/business-and-development/zoning-by-laws.aspx", plan:"https://www.milton.ca/en/business-and-development/official-plan.aspx", terms:"https://discover-milton.hub.arcgis.com/pages/disclaimer-and-terms-of-use", hub:"discover-milton.hub.arcgis.com", owner:"Milton_Maps", org:"FAgEZRLybpkpIX4O" },
  Oakville:{ zoning:"https://www.oakville.ca/town-hall/by-laws-enforcement/zoning-by-laws/", plan:"https://www.oakville.ca/town-hall/plans-strategies/official-plan/", terms:"https://www.oakville.ca/town-hall/plans-strategies/open-data/open-data-licence/", hub:"portal-exploreoakville.opendata.arcgis.com", owner:"Oakville_GIS", org:"QJebCdoMf4PF8fJP" },
} as const;
const oakAnchors=[HALTON_GUIDANCE.Oakville.terms,"https://www.oakville.ca/town-hall/town-studies-plans-projects/town-initiatives/open-data/open-data-licence/","https://www.oakville.ca/data/open_data_licence.html"];
function feed(market:HaltonMarket,key:string,item:string,url:string,fields:Record<string,string>,note:string,options:Partial<MunicipalFeed>={}):MunicipalFeed {
  const p=HALTON_GUIDANCE[market];
  return {market,key,item,url,owner:p.owner,org:p.org,oid:"OBJECTID",geometry:"esriGeometryPolygon",fields:{OBJECTID:"recordId",...fields},licenceAnchors:market==="Oakville"?oakAnchors:[p.terms],note,
    source:{id:`${market.toLowerCase()}:${key}`,name:`${market} ${key.replace(/([A-Z])/g," $1").toLowerCase()}`,url:`https://${p.hub}/datasets/${item}/about`,licence:market==="Burlington"?"City of Burlington Open Data Terms of Use, September 19, 2011":market==="Milton"?"Open Government Licence – Milton, version 2.0":"Open Government Licence – Town of Oakville (based on Canada version 2.0)",licenceUrl:p.terms,attribution:market==="Burlington"?"Contains City of Burlington open data. Access and reuse are subject to the linked Open Data Terms of Use; using these datasets indicates acceptance of those terms.":`Contains information licensed under the Open Government Licence – ${market==="Oakville"?"Town of Oakville":"Milton"}.`},...options};
}
const mil="https://api.milton.ca/arcgis/rest/services/",burl="https://mapping.burlington.ca/arcgisweb/rest/services/COB/",oak="https://maps.oakville.ca/oakgis/rest/services/";
const civic="Published municipal civic-address point, not a surveyed boundary or verified building centroid. Unit context remains building-level evidence, not proof of legality.";
const zone="Published zone labels and references are a point screen. Full written rules, applicable overlays, current amendments, appeals and parcel-wide permissions are unverified. Verify the proposed use with the municipality.";
const heritage="Preserve published listed/register and designated status separately. Published year-built text may be approximate. Verify the current register, designation bylaw and alteration requirements; no match does not establish absence.";
export const HALTON_FEEDS:MunicipalFeed[]=[
  feed("Milton","addresses","7b543a0d714a4930a90e771db838594b",mil+"Datasets/Address_Pts/MapServer/0",{ADDRESS_NUM:"civicNumber",GEOSTNAME:"streetName",STREET_TYPE:"streetType",ST_DIR_SUFFIX:"direction",UNIT_NUMBER:"unit",ADU:"publishedAdditionalUnitFlag",ADU_UNIT_NO:"publishedAdditionalUnitNumber"},civic+" ADU fields are published address flags, not a unit-registration certificate or verified legal unit count.",{geometry:"esriGeometryPoint",expectedLayerName:"ADDRESS_PTS"}),
  feed("Milton","urbanZoning","4b6840d0876b4b1494737315ab901728",mil+"WebMaps/UrbanZoning_202512171429/MapServer/8",{ZONECODE:"publishedZoneCode",ZONING:"publishedZoning",LABEL:"publishedZoneLabel",WEBSITE:"publishedReferenceUrl"},"Urban By-law 016-2014. "+zone,{expectedLayerName:"ZONING"}),
  feed("Milton","ruralZoning","48a3f0c2ddb143acb2d8b36d99606f4e",mil+"WebMaps/RuralZoning/MapServer/9",{ZONECODE:"publishedZoneCode",ZONING:"publishedZoning",LABEL:"publishedZoneLabel",WEBSITE:"publishedReferenceUrl"},"Rural By-law 144-2003. "+zone,{expectedLayerName:"ZONING"}),
  feed("Milton","heritage","cfc1a480977543cfbab034728f0d4690",mil+"Datasets/HeritageProperties/MapServer/0",{ADDRESS_NUM:"civicNumber",STREET_NAME:"street",TOWNSHIP:"publishedTownship",HISTORICAL_ADDRESS:"publishedHistoricalAddress",DESIGNATION:"publishedStatus",DESIGNATION_DATE:"publishedDesignationDateText",BY_LAW:"bylaw",PROPERTY_TYPE:"publishedPropertyType"},"The dataset title says Designated Heritage Properties, but records also include LISTED properties. "+heritage,{geometry:"esriGeometryPoint",expectedLayerName:"HERITAGE"}),
  feed("Milton","planningApplications","4b7c1ae792f2498e8f9b5f4c76f83060",mil+"Datasets/Development/MapServer/0",{PLANNINGNU:"applicationNumber",REGISTERED:"publishedRegistration",STATUS:"publishedStatus",PH_NAME:"publishedPhase",TYPE_DEV:"publishedDevelopmentType",DRAFT_PLAN_APPROVAL_DATE:"draftPlanApprovalDate",LAPSING_DATE:"publishedLapsingDate",RELATED_FILES:"publishedRelatedFiles"},"Published development polygons intersecting the point, not nearby applications or a full planning/decision history. Preserve repeated files and statuses; a registration, approval or lapsing date does not establish current permission, conditions or an appeal outcome.",{expectedLayerName:"DEVELOPMENT",dates:["DRAFT_PLAN_APPROVAL_DATE","LAPSING_DATE"]}),
  feed("Milton","hamlet","6ea655671ab84ead9047e8ec626fa83c",mil+"Datasets/Hamlets/MapServer/0",{NAME:"publishedHamlet"},"Published hamlet boundary point screen, not a current Official Plan designation, servicing or severance permission.",{expectedLayerName:"HAMLETS"}),
  feed("Milton","community","6c26ff98c86c48e38a01860c264b4eab",mil+"Datasets/Neighbourhoods/MapServer/0",{NAME:"publishedNeighbourhood"},"Published neighbourhood mapping, not household characteristics, school catchments or neighbourhood quality.",{expectedLayerName:"NEIGHBOURHOODS"}),
  feed("Burlington","addresses","d923cecae518430da70f9a29a0ea9b4d",burl+"AddressPoints/MapServer/0",{HOUSENUM:"civicNumber",STREET:"streetName",STRTYPE:"streetType",STRDIR:"direction",UNIT:"unit",CITY:"publishedCity",PROVINCE:"publishedProvince",PROPSTATUSDESC:"publishedAddressStatus"},civic+" Only Active civic entries are used for location identity.",{geometry:"esriGeometryPoint",expectedLayerName:"Address Points"}),
  feed("Burlington","permits","5a136c9ca8ee4b958d813c7426223cde",burl+"Permits/MapServer/1",{ADDRESS:"address",FOLDERTYPE:"publishedPermitType",FILENO:"permitNumber",INDATE:"applicationDate",ISSUEDATE:"issuedDate",WORKDESC:"publishedWorkType",SUBDESC:"publishedSubtype",FOLDERSTATUSDESC:"publishedStatus",REFERENCEFILE:"publishedReferenceFile",RESUNITS:"publishedResidentialUnits",CONSTRUCTVALUE:"estimatedConstructionValueCAD"},"Exact civic-address observations, including repeated permit numbers with different work/date fields. Retain all observations; row counts are not distinct permits. Issued or Final status is not a verified final inspection or occupancy approval. Published construction value is an estimate in CAD, not property value; residential-unit fields are permit context, not a verified existing/legal unit count. Full historical coverage is unverified.",{geometry:"esriGeometryPoint",expectedLayerName:"Permit Building",dates:["INDATE","ISSUEDATE"]}),
  feed("Burlington","heritage","8cc75fa5239e48f19a8e8c42d06cba1a",burl+"HeritagePropertyParcels/FeatureServer/0",{HOUSENUM:"civicNumber",STREET_NAME:"street",YEARBUILT:"publishedYearBuiltText",DESIGNATION:"publishedDesignatedFlag",REGISTER:"publishedRegisterFlag",DESCRIPTION:"publishedDescription",BYLAW_INFORMATION:"publishedBylawInformation"},"Published heritage property-parcel polygon point screen. "+heritage,{expectedLayerName:"Heritage Properties Parcels"}),
  feed("Burlington","heritageAddressEvidence","d1fa369c97074c738475a303110df620",burl+"HeritageProperties/MapServer/0",{HOUSENUM:"civicNumber",STREET_NAME:"street",YEARBUILT:"publishedYearBuiltText",DESIGNATION:"publishedDesignatedFlag",REGISTER:"publishedRegisterFlag",DESCRIPTION:"publishedDescription"},"Exact civic-address heritage point evidence, separate from heritage parcel mapping. "+heritage,{geometry:"esriGeometryPoint",expectedLayerName:"Heritage Properties"}),
  feed("Burlington","zoning2020Mapping","41ddbd93d8d14293b4608ac9a7fc1bd4",burl+"Zoning_ByLaw/MapServer/6",{FULL_ZONING:"publishedZoneLabel",NOTE:"publishedNote",LAST_EDITED_DATE:"recordModifiedDate"},"Older published zoning mapping: it does not establish current residential zoning after By-law 09-2026 came into force March 2, 2026. By-law 2020 still applies to other lands; applicability is unverified. "+zone,{expectedLayerName:"Zoning Bylaw",dates:["LAST_EDITED_DATE"]}),
  feed("Burlington","community","1afaa4cd5c1148f89480817fce4c0469",burl+"PlanningCommunities/MapServer/1",{PLANNING_COMMUNITY:"publishedCommunity",LAST_EDITED_DATE:"recordModifiedDate"},"Published planning-community boundary point screen; separate from current land-use policy or neighbourhood quality.",{expectedLayerName:"Planning Communities",dates:["LAST_EDITED_DATE"]}),
  feed("Burlington","planningDistrict","ce407b02904542889c3a24a68ba5573f",burl+"PlanningCommunities/MapServer/0",{PLANNING_DISTRICT:"publishedPlanningDistrict",LAST_EDITED_DATE:"recordModifiedDate"},"Published planning-district boundary point screen; not an Official Plan designation.",{expectedLayerName:"Planning Districts",dates:["LAST_EDITED_DATE"]}),
  feed("Burlington","heritageDistrict","04a8e36fc9a745a6b953606ad2bc9bae",burl+"HeritageConservationDistricts/MapServer/0",{},"",{disabledReason:"The district catalogue item has no explicit dataset reuse licence. No district records are queried; confirm the current district/register with the City."}),
  feed("Burlington","residentialZoning2026","c1cdc567dee3414bbb60128aa0700530","https://services1.arcgis.com/xbWF6o8qyXoMFa8L/arcgis/rest/services/NewZoningBylawContent/FeatureServer/27",{},"",{disabledReason:"The discovered January 2026 final-draft item links separate use limitations; current enacted By-law 09-2026 mapping and dataset reuse are not verified. No draft records are queried or presented as current zoning."}),
  feed("Oakville","addresses","f218b2b0a1c747939b179e132e648b8f",oak+"ArcGISOnline/AGO_Oakville_Misc_Layers/MapServer/15",{STREET_NUM:"civicNumber",SUFFIX:"civicSuffix",STREET_NAME:"streetName",STREET_TYPE:"streetType",STREET_DIR:"direction",STREET_TYPE_PREFIX:"streetTypePrefix",STREET_DIR_PREFIX:"directionPrefix",UNIT:"unit",SUITE:"suite",CITY:"publishedCity",PROV:"publishedProvince"},civic+" Missing published CITY/PROV fields are unknown; conflicting fields are rejected. No owner or contact fields are requested.",{geometry:"esriGeometryPoint",expectedLayerName:"Address Points"}),
  feed("Oakville","zoning2014","54d77fc2abd34bc694b4ea1e57e2fa1c",oak+"SBS/Zoning_By_law_2014_014/FeatureServer/10",{ZONE:"publishedZoneCode",ZONE_DESC:"publishedZoneDescription",FULL_ZONING_DESC:"publishedFullZoneLabel",SP_DESC:"publishedSiteSpecificDescription",HOLD:"publishedHolding",TEMP:"publishedTemporaryUse",GROWTH_AREA:"publishedGrowthArea",BLDG_HEIGHTS:"publishedBuildingHeightText",COMMENTS:"publishedComments",ENABLED:"publishedEnabledFlag",last_edited_date:"recordModifiedDate"},"By-law 2014-014 applies south of Dundas Street and north of Highway 407. Preserve source text, including holding and exception references; do not convert unexplained text into permitted density or height. "+zone,{expectedLayerName:"Zoning By-law 2014-014",dates:["last_edited_date"]}),
  feed("Oakville","zoning2009","1ed2256eb6d04caea4c9c799aed2cff3",oak+"SBS/Zoning_By_law_2009_189/FeatureServer/4",{ZONE:"publishedZoneCode",ZONE_DESC:"publishedZoneDescription",SUB_CLASS:"publishedSubclass",HOLD:"publishedHolding",SP_DESC:"publishedSiteSpecificDescription",last_edited_date:"recordModifiedDate"},"North Oakville By-law 2009-189 applies between Dundas Street and Highway 407. "+zone,{expectedLayerName:"Zoning By-law 2009-189",dates:["last_edited_date"]}),
  feed("Oakville","permits","c8b0e73d060b4c208e603c2bcad90d36","https://services5.arcgis.com/QJebCdoMf4PF8fJP/arcgis/rest/services/Building_Permits/FeatureServer/0",{CUSTOMFOLDERNUMBER:"permitNumber",FOLDERNAME:"publishedFolderAddress",FOLDERDESCRIPTION:"publishedDescription",FOLDERTYPE:"publishedPermitType",Subtype:"publishedSubtype",Worktype:"publishedWorkType",INDATE:"applicationDate",ISSUEDATE:"issuedDate",Status:"publishedStatus",Construction_Value:"estimatedConstructionValueCAD",Dwelling_Units_Created:"publishedUnitsCreated",GFA:"publishedGrossFloorAreaUnknownUnits",GFA__Accessory_Unit_:"publishedAccessoryUnitAreaUnknownUnits",GFA__Basements_Alterations_:"publishedBasementAlterationAreaUnknownUnits",ConstructionStartDate:"publishedConstructionStartDate",UnitsDemolished:"publishedUnitsDemolished",StatusGroup:"publishedStatusGroup",Number_of_Storeys:"publishedStoreys"},"The catalogue advertises the last ten years of building permits, updated nightly; this is not full property history. Exact published folder-address observations retain Cancelled, Closed and other statuses separately. Closed is not a verified final inspection or occupancy approval. Values are published estimates in CAD; GFA units are undocumented and are not assumed to be m². Unit counts are permit context, not current/legal unit counts. No legal-description or owner fields are requested.",{owner:"richard.dean@oakville.ca_ExploreOakville",oid:"OBJECTID_1",fields:{OBJECTID_1:"recordId",CUSTOMFOLDERNUMBER:"permitNumber",FOLDERNAME:"publishedFolderAddress",FOLDERDESCRIPTION:"publishedDescription",FOLDERTYPE:"publishedPermitType",Subtype:"publishedSubtype",Worktype:"publishedWorkType",INDATE:"applicationDate",ISSUEDATE:"issuedDate",Status:"publishedStatus",Construction_Value:"estimatedConstructionValueCAD",Dwelling_Units_Created:"publishedUnitsCreated",GFA:"publishedGrossFloorAreaUnknownUnits",GFA__Accessory_Unit_:"publishedAccessoryUnitAreaUnknownUnits",GFA__Basements_Alterations_:"publishedBasementAlterationAreaUnknownUnits",ConstructionStartDate:"publishedConstructionStartDate",UnitsDemolished:"publishedUnitsDemolished",StatusGroup:"publishedStatusGroup",Number_of_Storeys:"publishedStoreys"},geometry:"esriGeometryPoint",expectedLayerName:"BuildingPermits",dates:["INDATE","ISSUEDATE","ConstructionStartDate"]}),
  feed("Oakville","generalizedLandUse","6a4ecc2ef60f4811a0ab408a719a2397","https://services5.arcgis.com/QJebCdoMf4PF8fJP/arcgis/rest/services/General_Land_Use/FeatureServer/0",{SGU_Type:"publishedGeneralLandUse"},"Published general land use only. No Official Plan vintage, legend, policy permissions or full municipal plan/constraint coverage is established.",{owner:"frank.goehner@oakville.ca_ExploreOakville",expectedLayerName:"General_Land_Use"}),
  feed("Oakville","heritage","6a57f4591e314fb5b5c88e067add8872",oak+"ArcGISOnline/AGO_OpenData/MapServer/26",{},"",{disabledReason:"The selected heritage item lacks an explicit dataset reuse licence. No records are queried, including its owner and owner-address fields. Confirm the current register and districts with the Town."}),
  feed("Oakville","planningApplications","fb204fefc6494027ab42504137ec36f4",oak+"SBS/Active_Development_Applications/MapServer/1",{},"",{owner:"frank.goehner@oakville.ca_ExploreOakville",disabledReason:"The selected active-development item lacks an explicit dataset reuse licence. No records are queried. Other licensed catalogue references are labelled broken or use a proxy; complete current application and decision coverage remains unverified."}),
];
