import type { Source, Row } from "./model";

export type Market = "Mississauga" | "London" | "Ottawa" | "Oshawa";
export type HaltonMarket = "Burlington" | "Milton" | "Oakville";
export interface MunicipalFeed {
  market: Market | HaltonMarket | "Durham Region"; key: string; item: string; url: string; owner: string; org: string | null;
  licenceAnchors: string[]; oid: string; geometry: "esriGeometryPoint" | "esriGeometryPolygon";
  fields: Record<string, string>; dates?: string[]; source: Source; note: string;
  disabledReason?: string; expectedLayerName?: string;
}
const MS_TERMS = "https://mississauga.maps.arcgis.com/sharing/rest/content/items/961c790805c14d8da258ec91bf4117e3/data";
const LN_TERMS = "https://london.maps.arcgis.com/sharing/rest/content/items/e31458fd0c7e41dd9f93144a9550781d/data";
const OT_TERMS = "https://ottawa.ca/en/city-hall/get-know-your-city/open-data#open-data-licence-version-2-0";
export const OSHAWA_TERMS = "https://map.oshawa.ca/OpenData/Open%20Government%20Licence%20version%202.0%20-%20Oshawa.pdf";
export const OSHAWA_LICENCE_ANCHORS = [OSHAWA_TERMS, decodeURI(OSHAWA_TERMS)];
const ms = "https://services6.arcgis.com/hM5ymMLbxIyWTjn2/arcgis/rest/services/";
const ln = "https://maps.london.ca/server/rest/services/OpenData/OpenData_Community/MapServer/";
const ot = "https://maps.ottawa.ca/arcgis/rest/services/";
const osh = "https://map.oshawa.ca/arcgis/rest/services/Operational/";
function feed(market: Market, key: string, item: string, url: string, fields: Record<string, string>, note: string, options: Partial<MunicipalFeed> = {}): MunicipalFeed {
  const publishers = {
    Mississauga: { owner:"MississaugaData", org:"hM5ymMLbxIyWTjn2", host:"data.mississauga.ca", terms:MS_TERMS },
    London: { owner:"opendata_London", org:null, host:"opendata.london.ca", terms:LN_TERMS },
    Ottawa: { owner:"open.ouvert@ottawa.ca", org:"G6F8XLCl5KtAlZ2G", host:"open.ottawa.ca", terms:OT_TERMS },
    Oshawa: { owner:"City.of.Oshawa", org:"qQGLFamV2KgdKsUa", host:"city-oshawa.opendata.arcgis.com", terms:OSHAWA_TERMS },
  };
  const p = publishers[market], ogl = market === "Ottawa" || market === "Oshawa";
  return { market, key, item, url, owner:p.owner, org:p.org,
    licenceAnchors: market === "Oshawa" ? OSHAWA_LICENCE_ANCHORS : [p.terms], oid: "OBJECTID", geometry: "esriGeometryPolygon", fields: { OBJECTID: "recordId", ...fields }, note,
    source: { id: `${market.toLowerCase()}:${key}`, name: `${market} ${key.replace(/([A-Z])/g, " $1").toLowerCase()}`, url: `https://${p.host}/datasets/${item}/about`, licence: ogl ? `Open Government Licence – ${market === "Oshawa" ? "The Corporation of the " : ""}City of ${market}, version 2.0` : `City of ${market} Open Data Terms of Use`, licenceUrl:p.terms, attribution: ogl ? `Contains information licensed under the Open Government Licence – ${market === "Oshawa" ? "The Corporation of the " : ""}City of ${market}.` : `Contains public data from the City of ${market}, distributed under its Open Data Terms of Use. Access and reuse are subject to the linked terms.` }, ...options };
}
const historicalPlan = "Historical 2010 Official Plan mapping only. The City reports that plan was repealed on March 24, 2026 when Official Plan 2051 came into effect. This is not a current plan designation or constraint screen. Verify the current 2051 schedules and subsequent amendments.";
export const ONTARIO_MUNICIPAL: MunicipalFeed[] = [
  feed("Mississauga", "addresses", "8efbfcb82a2e4373bea6013105ed1c8c", ms+"Address/FeatureServer/0", { FID:"recordId", ADDR_ID:"addressId", STNO:"civicNumber", UNIT_NO:"unit", FULLNAME:"street", SUFFIX:"streetType", DIRECTION:"direction" }, "Published municipal civic-address points; building-level scope only.", { oid:"FID", fields:{ FID:"recordId", ADDR_ID:"addressId", STNO:"civicNumber", UNIT_NO:"unit", FULLNAME:"street", SUFFIX:"streetType", DIRECTION:"direction" }, geometry:"esriGeometryPoint" }),
  feed("Mississauga", "permits", "978ce8c2c5844486b5d768420fa9c72d", ms+"Issued_Building_Permits/FeatureServer/0", { BP_NO:"permitNumber", STATUS:"publishedStatus", ADDRESS:"address", UNIT_NO:"unit", DESCRIPTION:"description", SCOPE:"scope", FILE_TYPE:"fileType", BLDG_TYPE:"buildingType", APP_DETAIL:"applicationDetail", APPL_AREA:"publishedApplicationArea", STOREYS:"storeys", EST_CON_VALUE:"estimatedConstructionValueCAD", RES_UNITS:"publishedResidentialUnits", DEMO:"demolition", APPLICATION_DATE:"applicationDate", ISSUE_DATE:"issuedDate", COMPLETE_DATE:"completedDate" }, "Exact civic-address permit history. Unit identifiers remain visible within building-level results; these records do not establish unit legality. Construction value is a published estimate in CAD, not property value. Application area is preserved without assuming an unpublished unit. Status and completion date do not prove final inspection or occupancy.", { geometry:"esriGeometryPoint", dates:["APPLICATION_DATE","ISSUE_DATE","COMPLETE_DATE"] }),
  feed("Mississauga", "heritage", "a32dbe48193b44d09033c15b4b4b9f39", ms+"Mississauga_Heritage_Properties/FeatureServer/0", { HERC_DESCRIPTION:"publishedDescription", HERC_STATUS:"publishedStatus" }, "Published heritage polygon point screen. Preserve the published status; listing, designation and district membership have different meanings. Verify the current register, bylaw and planned alteration with the City.", { licenceAnchors:[MS_TERMS,"https://ago-item-storage.s3.amazonaws.com/961c790805c14d8da258ec91bf4117e3/CityofMississauga_TermsofUse.pdf"] }),
  feed("Mississauga", "ward", "f1cad02b3a40422dac2ea99b59cc36a5", ms+"Ward_Boundaries/FeatureServer/2", { WARD:"ward" }, "Published ward boundary point screen; elected-person contact information is excluded.", { licenceAnchors:["https://smartcity.mississauga.ca/wp-content/uploads/2021/04/CityofMississauga_TermsofUse.pdf",MS_TERMS] }),
  feed("Mississauga", "historicalOfficialPlan2010", "af2caaeb20a542fd871a5abcdf1834cb", ms+"MississaugaOfficialPlan_2010_LandUse_Schedule_10/FeatureServer/1", { MOP_CODE:"historicalPlanCode", MOP_DESCRIPTION:"historicalPlanDescription" }, historicalPlan),
  feed("Mississauga", "historicalNaturalSystem2010", "7be4673bc93d4d35819a0d24c7cf485d", ms+"MOP_NaturalSystem/FeatureServer/10", { Layer:"publishedLayer", NaturalSystem:"historicalNaturalSystem" }, historicalPlan+" Natural-system mapping is separate from conservation-authority regulation."),
  feed("Mississauga", "historicalNaturalHazards2010", "4d65df1071be4c44886db98f44d7ad6c", ms+"MOP_NaturalHazards/FeatureServer/0", {}, historicalPlan+" The layer publishes polygon IDs without hazard categories; do not invent a flood or erosion classification.", { oid:"FID", fields:{ FID:"recordId" } }),
  feed("Mississauga", "zoning", "ea40103d821f4a118b0d3c55dc4ca2fa", ms+"2022_Zoning/FeatureServer/0", {}, "", { disabledReason:"The official dataset terms say GIS data may not be modified or copied without written consent. No zoning records are queried or redistributed. Consult the City's zoning map and obtain current parcel-specific verification." }),
  feed("Mississauga", "rezoningApplications", "9b25caf083d54593a7db21ea056cfb3d", ms+"Rezoning_Applications/FeatureServer/0", {}, "", { disabledReason:"This official feed's reuse licence is unverified. No records are queried. Its advertised scope is approvals since 2016 or still-active applications, not complete planning history." }),
  feed("Mississauga", "sitePlanApplications", "85536f145719436ebde8d31f36d11d83", ms+"Site_Plan_Applications/FeatureServer/0", {}, "", { disabledReason:"This official feed's reuse licence is unverified. No records are queried. Its advertised scope is approvals since 2016 or still-active applications, not complete planning history." }),
  feed("London", "addresses", "24b16712d14c42d7ac1e679c8c89bf47", ln+"0", { FullNumber:"civicNumber", FullStreetName:"street", UnitNumber:"unit", Status:"publishedStatus" }, "Issued municipal civic-address points only. Proposed and inactive addresses are excluded.", { geometry:"esriGeometryPoint" }),
  feed("London", "heritage", "ac8425f044e1477b849c53f37df11eff", ln+"7", { Status:"publishedStatus", Address:"address", YearBuilt:"publishedYearBuiltText", BuildingName:"buildingName", ArchitecturalStyle:"architecturalStyle", DesignationPart:"designationPart", HeritageConservationDistrict:"heritageConservationDistrict", ByLaw:"bylaw" }, "Heritage parcel point screen. Preserve status, designation part and district separately. Published year-built text can be approximate or a range; do not turn it into a verified construction year. Verify the current register and alteration requirements."),
  feed("London", "heritageDistrict", "accdfc5946194f1cad7507ca322e5c7a", ln+"6", { CulturalResourcesCategory:"publishedCategory", NAICSDEF:"publishedDescription", LastEditDate:"recordModifiedDate" }, "Heritage conservation district point screen. This does not establish an individual Part IV designation.", { dates:["LastEditDate"] }),
  feed("London", "generalizedLandUse", "adaf9f5e53d7462594fa3ee4f5544d1a", ln+"16", { GeneralizedLandUse:"generalizedLandUse", GeneralizedLanduseStatus:"publishedMappingStatus", LastEditDate:"recordModifiedDate" }, "The licensed Zoning Areas feed publishes generalized land use and mapping status only. It does not publish zone codes, exceptions, holding provisions or permitted-use rules. It is not a complete zoning verification.", { dates:["LastEditDate"] }),
  feed("London", "primaryTransitArea", "552505a970174a78ae779a5e42da9e4c", ln+"15", { GIS_ID:"publishedAreaId", LastEditDate:"recordModifiedDate" }, "Primary Transit Area point screen. This does not measure walking distance, current transit service or development permission.", { dates:["LastEditDate"] }),
  feed("London", "communityImprovementArea", "1b0d11ccf60f4e77b2e86dc98ace1e83", ln+"12", { CommunityImprovementProjectArea:"publishedArea", LastEditDate:"recordModifiedDate" }, "Community Improvement Project Area point screen. Area membership does not prove a currently funded program, grant amount, eligibility or an approved application.", { dates:["LastEditDate"] }),
  feed("Ottawa", "addresses", "03ba03fdf8e2486ca94fe64ad2c99102", ot+"Address_Information/MapServer/0", { ADDRNUM:"civicNumber", QUALIFIER:"qualifier", UNIT:"unit", FULL_ROADNAME_EN:"street", FULL_ROADNAME_FR:"streetFrench", MUNICIPALITY:"municipality", CP_MUNICIPALITY:"postalMunicipality", ADDRTYPE:"addressType" }, "Municipal address points are published at parcel centres or approximate building entrances; they are not verified building centroids.", { geometry:"esriGeometryPoint" }),
  feed("Ottawa", "heritageDistrict", "3ef851c23a1c4e92b461dd27571a2fd8", ot+"Planning/MapServer/17", { HCD_EN:"district", HCD_FR:"districtFrench", BYLAW:"bylaw", AMENDMENT:"amendment", DESCR_EN:"description", MODIFIED_DATE:"recordModifiedDate" }, "Part V heritage district point screen. This does not establish an individual Part IV designation or complete heritage-register search.", { dates:["MODIFIED_DATE"] }),
  feed("Oshawa", "addresses", "528210b2e00c4607b8c971f4ed9389ff", osh+"Parcels_AddPts/MapServer/0", { ADDRESSID:"addressId", SITE_CIVIC_NO:"civicNumber", SITE_CIVIC_CHAR:"civicSuffix", SITE_UNIT_ID:"unit", STNAME:"street" }, "Municipal civic-address points assigned to buildings or properties; location scope is not a surveyed building centroid.", { geometry:"esriGeometryPoint" }),
  feed("Oshawa", "zoning", "dee9180066de48c684a34ab6c35ac62a", osh+"PopularLayers/MapServer/17", {}, "Published zoning label point screen. Preserve the full label, including any exceptions or holding notation; the feed does not publish separate rule text, amendment dates, appeal status or an observation date. Verify By-law 60-94 as amended and applicable overlays with the City. Central Oshawa and Thornton's Corners transit-station amendments have approval-dependent provisions; a mapped label does not establish current development permission.", { oid:"OBJECTID_1", fields:{ OBJECTID_1:"recordId", DESCRIPTION:"publishedZoneLabel" } }),
  feed("Oshawa", "existingLandUse", "d5c53053f810480bb6390a67659a9160", osh+"OpenData/MapServer/0", { PARCELID:"municipalParcelId", EXISTING_USE_CODE:"publishedUseCode", EXISTING_USE_DESC:"publishedExistingUse", PROPERTY_CLASS:"publishedPropertyClass", DS_PROPERTY_CLASS:"publishedDetailedClass", LAST_EDITED_DATE:"recordModifiedDate" }, "Published existing-use classification point screen, separate from Official Plan designations and zoning permission. Dwelling/unit descriptions are classifications, not a verified unit count or proof of legality.", { dates:["LAST_EDITED_DATE"] }),
  feed("Oshawa", "parcel", "444c69bedab545b8ae819d78555eb4aa", osh+"OpenData/MapServer/1", { PARCELID:"municipalParcelId", FCODE:"publishedFeatureCode", SHAPE_Area:"publishedGeometryAreaInternalUnitsSquared" }, "Municipal parcel-reference point screen. The municipal parcel ID is not a land-registry PIN or title record. Published geometry area uses internal units squared; no surveyed lot area or unit conversion is asserted. Boundaries are reference mapping, not a survey."),
  feed("Oshawa", "community", "1d9e2d22e339458d8486ee5af8fa6ff8", osh+"OpenData/MapServer/2", { COMM:"publishedCommunityCode", COMMNAME:"publishedCommunity" }, "Published City community-boundary point screen; this is not a neighbourhood quality, school catchment or household classification."),
  feed("Oshawa", "ward", "a9257f99b2d941a3bff928f4a19d6f9d", osh+"OpenData/MapServer/11", { WARDNUMBER:"ward" }, "Published 2018 ward-boundary mapping point screen. Current electoral boundaries and representation must be verified; elected-person contact information is excluded."),
];

export function validMunicipalPublisher(item:Row, f:Pick<MunicipalFeed,"owner"|"org"|"licenceAnchors">):boolean {
  if (item.access !== "public" || item.owner !== f.owner || (item.orgId ?? null) !== f.org) return false;
  const terms = typeof item.licenseInfo === "string" ? item.licenseInfo : "";
  if (/may not be (?:modified|copied)|without written consent|non.commercial only|all rights reserved/i.test(terms)) return false;
  const anchors = terms.includes("<") ? [...terms.matchAll(/href=['"]([^'"]+)['"]/gi)].map(m => m[1]) : [terms.trim()];
  return anchors.some(a => f.licenceAnchors.includes(a.split("?")[0]));
}
/** Exact publisher, endpoint and terms binding; a public service alone does not grant reuse rights. */
export function validMunicipalItem(item: Row, f: MunicipalFeed): boolean {
  if (f.disabledReason || !validMunicipalPublisher(item,f)) return false;
  const url = typeof item.url === "string" ? item.url.replace(/\/$/, "") : "";
  return url === f.url || url === f.url.replace(/\/\d+$/, "");
}
