import type { Source } from "./model";

export const SPA_KEY = "ontarioSourceProtectionAreaReference";
export const SPA_NAME = "Source Protection Area Generalized";
export const SPA_LICENCE = "https://www.ontario.ca/page/open-government-licence-ontario";
export const SPA_OFFER = "https://geohub.lio.gov.on.ca/datasets/source-protection-area-generalized";
export const SPA_ITEM = "e47ba8e4f5884a08be8e17b165ede457";
export const SPA_ROOT = "https://ws.lioservices.lrc.gov.on.ca/arcgis2/rest/services/LIO_OPEN_DATA/LIO_Open05/MapServer";
export const SPA_DESCRIPTION = "https://www.publicdocs.mnr.gov.on.ca/mirb/Source%20Protection%20Area%20Generalized%20-%20Data%20Description.pdf";
export const SPA_FIELDS = { OBJECTID: "esriFieldTypeOID", OGF_ID: "esriFieldTypeDouble", SPP_ID: "esriFieldTypeInteger", SPR_ID: "esriFieldTypeSmallInteger", LEAD_SPA: "esriFieldTypeString", FTYPE: "esriFieldTypeString", LOCATION_ACCURACY: "esriFieldTypeString", GEOMETRY_UPDATE_DATETIME: "esriFieldTypeDate", EFFECTIVE_DATETIME: "esriFieldTypeDate", SYSTEM_DATETIME: "esriFieldTypeDate" };
export const SPA_SOURCE: Source = { id: "ontario:source-protection-area-generalized:2", name: SPA_NAME, url: `${SPA_ROOT}/2`, licence: "Open Government Licence – Ontario", licenceUrl: SPA_LICENCE, attribution: "Contains information licensed under the Open Government Licence – Ontario. Ministry of the Environment, Conservation and Parks / Geospatial Ontario." };
export const SPA_NOTE = "Original generalized/smoothed source-protection area reference at an independent point. Preserve raw SPA/region IDs, landform type, administrative lead label and reported location accuracy. Names are historical lookup labels from the original 2012 data description, not verified current legal names or contact/jurisdiction assignments. Record/geometry/system dates and catalogue/item edits are separate from current plan approval or policy dates. This is not a legal SPA boundary, WHPA/IPZ/SGRA/HVA screen, parcel-wide constraint, conservation-regulation/flood screen, water-supply connection or water-quality finding. No-match does not establish absence, current permission, clearance, water safety or insurance eligibility. Obtain current original-authority maps, operative plan/policies and activity-specific requirements separately.";

// Original 2012 data-description tables, pages 7–9; not a current legal crosswalk.
export const HISTORICAL_SPA: Record<number, readonly [string, number]> = {
  0: ["Undetermined/No Official Name", 99], 10: ["Ausable Bayfield", 10], 11: ["Cataraqui", 12], 12: ["Catfish Creek", 15], 13: ["Central Lake Ontario", 11], 14: ["Halton", 14], 15: ["Credit Valley", 11], 16: ["Crowe Valley", 28], 17: ["Essex", 13], 18: ["Ganaraska Region", 28], 19: ["Grand River", 15], 20: ["Grey Sauble", 23], 21: ["Hamilton", 14], 22: ["Kawartha-Haliburton", 28], 23: ["Kettle Creek", 15], 24: ["Lakehead", 16], 25: ["Lakes Simcoe and Couchiching/Black River", 25], 26: ["Long Point", 15], 27: ["Lower Thames Valley", 27], 28: ["Lower Trent", 28], 29: ["Maitland Valley", 10], 30: ["Mattagami", 17], 31: ["Mississippi Valley", 18], 32: ["Niagara Peninsula", 19], 33: ["Nickel District", 26], 34: ["North Bay-Mattawa", 20], 35: ["Nottawasaga Valley", 25], 36: ["Otonabee-Peterborough", 28], 37: ["Quinte", 21], 38: ["Raisin Region", 22], 39: ["Rideau Valley", 18], 40: ["Saugeen Valley", 23], 41: ["Sault Ste Marie", 24], 42: ["South Nation", 22], 43: ["St. Clair Region", 27], 44: ["Toronto", 11], 45: ["Upper Thames River", 27], 46: ["Severn Sound", 25], 48: ["Northern Bruce Peninsula", 23],
};
export const HISTORICAL_SPR: Record<number, string> = { 10: "Ausable Bayfield Maitland Valley", 11: "CTC", 12: "Cataraqui", 13: "Essex", 14: "Halton-Hamilton", 15: "Lake Erie", 16: "Lakehead", 17: "Mattagami", 18: "Mississippi-Rideau", 19: "Niagara Peninsula", 20: "North Bay-Mattawa", 21: "Quinte", 22: "Raisin Region South Nation", 23: "Saugeen, Grey Sauble, Northern Bruce Peninsula", 24: "Sault Ste Marie", 25: "South Georgian Bay Lake Simcoe", 26: "Sudbury", 27: "Thames, Sydenham and Region", 28: "Trent Conservation Coalition", 99: "Undetermined" };
export const SPA_LOOKUP = { source: SPA_DESCRIPTION, documentCopyrightYear: 2012, reviewedPages: [7, 8, 9], sha256: "6d6ab68bd26762dbf067c2286ad666461dc40e2e1f80cb29a3dd7ac0b33914ad", currentNamesVerified: false, currentLegalCrosswalkVerified: false };
