import { cityKey, layer, type Layer } from "./model";
import { provinceKey } from "./geocode";
import type { EvidenceQuestion } from "./brief";

const city = "https://www.owensound.ca";
export const OWEN_PLANNING = `${city}/business-building-development/planning-and-development/`;
export const OWEN_INQUIRY = `${city}/business-building-development/property-inquiry-requests/`;
export const OWEN_BUILDING = `${city}/business-building-development/building-permits-inspections/`;
export const OWEN_MAP = "https://experience.arcgis.com/experience/f3a1262f41be4ce78ca5b0db09782b38";
export const OWEN_ZONING_NOTICE = "https://media-001-ca.cdn.govstack.com/owensound-005-ca/media/3ctbyugv/notice-of-passing-zba-no-57.pdf";
export const OWEN_PLAN_NOTICE = "https://media-001-ca.cdn.govstack.com/owensound-005-ca/media/phjmhvo1/notice-of-adoption-opa-no-14.pdf";
export const OWEN_ARU = "https://media-001-ca.cdn.govstack.com/owensound-005-ca/media/tukbkfey/additional-residential-unit-guide.pdf";
export const OWEN_TERMS = `${city}/privacy-policy/`;
export const OWEN_RIGHTS = "The exact current City experience, its two public web maps and original PUBLIC_GIS_WFL1 item have blank reuse grants. Selected zoning, special-provision, parcel, plan, regulation and plaque children have blank descriptions/copyright. The City's privacy page provides no affirmative commercial data grant; the footer Terms & Conditions link is a non-document ## anchor. A compatible City merged commercial API grant was not established. The offered temporary viewer item is inaccessible (ArcGIS CONT_0001); it was not bypassed. These findings do not override the independently verified original County Open Data Licence or provincial grants. No City feature/count/geometry queries were performed.";
const scope = (layer: string, url: string, reason: string, termsUrl = OWEN_TERMS) => ({ layer, url, reason, termsUrl });
export const OWEN_WITHHELD = [
  scope("municipalAddresses", OWEN_MAP, `${OWEN_RIGHTS} City parcel labels are separate from a precisely placed building/site or unit address; no civic point is reused.`),
  scope("parcel", OWEN_MAP, `${OWEN_RIGHTS} Reference cadastral/assessment labels are separate from current survey/title, ownership and legal boundaries. Obtain a current Ontario Land Surveyor survey and title review.`),
  scope("catalogueZoningReference", OWEN_MAP, `${OWEN_RIGHTS} GIS labels and special provisions do not establish current written rules, exceptions, holds, amendments/appeals or development permission.`),
  ...["zoning", "currentPlanningInstruments", "officialPlan"].map(name => scope(name, OWEN_PLANNING, "The April 16, 2026 notices establish April 13 passage of 2026-030/ZBA57 and adoption of 2026-029/OPA14. ZBA57's notice sets a May 6, 2026 appeal deadline and expressly makes its effect conditional on OPA14 coming into effect. OPA14 requires County approval and can replace the 2021 plan in parts at different times. Current County decision, appeal outcomes and operative provisions/schedules remain unverified. The City zoning/PIR pages still refer to 2010-078; final document labels and elapsed deadlines do not establish full effect. Preserve document conflicts: the OPA notice says November 24, 2025 meetings while the appended adopted bylaw says November 24, 2026; the ZBA appended second page header says 2025-079 while its title/passage identify 2026-030. Obtain authoritative corrections/current instruments.")),
  ...["planningApplications", "variance", "consentToSever", "sitePlanDrawings", "sitePlanControl"].map(name => scope(name, `${OWEN_PLANNING}active-planning-applications/`, "Public application/Committee notices and passing/adoption notices are manual research routes, not complete decisions or approvals. Obtain full decisions, cleared conditions, current appeal outcomes, approved drawings, signed/registered agreements and expiry. The County FAQ expressly treats Owen Sound differently: the City generally decides its own applications except five-year reviews and boundary expansions; do not automatically apply the other eight municipalities' approval split.")),
  scope("owenSoundPropertyInquiry", OWEN_INQUIRY, "The paid Property Inquiry Request Form offers separate tax/water certificates, By-law Enforcement work-order checks, Building current permit/work-order status, current planning/zoning, heritage notice, agreement/completion/lot releases, securities, recent fire/building reports, Fire field inspection and existing municipal service availability. A completed form and fee are required for each property; guidance estimates at least two to three weeks. These are separate requested scopes, not one completed report or automatic full history. No request, payment, inspection or certificate was obtained."),
  ...["permits", "inspectionResults", "occupancyDocuments"].map(name => scope(name, OWEN_BUILDING, "Cloudpermit manages applications and inspections. The PIR current permit/work-order status is separate from full historic permit files, passed inspections and occupancy evidence. City guidance says occupancy may be issued while safe but incomplete work leaves the building permit open until final inspection. Obtain each advertised unit's actual occupancy permission, passed finals, outstanding conditions/orders and full property files; an open permit alone does not establish unlawful occupancy, and an occupancy permit does not establish a closed permit. City guidance states it does not conduct pre-purchase inspections.")),
  scope("additionalUnits", OWEN_ARU, "The currently offered seven-page undated ARU guide describes one ARU in the main dwelling plus one in an accessory structure, residential single/semi/row-house eligibility and Section 5.27/6 requirements. It separately says converted duplex/triplex dwellings have no main-building ARU, with an accessory ARU potentially permitted. Servicing guidance requires sufficient municipal water/sewer and connections through the primary dwelling; where municipal services exist, wells/septic are not allowed for ARUs. Preserve these as guide statements, not verified current adopted unit limits or actual connection/capacity. The 2026 planning transition, building-code tables, off-site construction/ESA guidance and fee exemptions require current confirmation. No guide publication/effective date, legal unit register, advertised-unit approval or occupancy was verified."),
  ...["heritage", "heritageDistrict"].map(name => scope(name, `${city}/recreation-culture/heritage-conservation/`, "The webpage offers an online heritage list with an asterisk identifying Part IV designation and says the official register at City Hall has more detail. Its narrative count is not an audited current count, and its linked 2020 PPS is a separate older vintage. Obtain the complete current statutory listed/designated/district instruments, attributes, notices, amendments/appeals and alteration/demolition permissions. The PIR warns the register does not identify all potential heritage properties. No register extraction, matched property finding or current district absence was established.")),
  scope("historicPlaqueReference", OWEN_MAP, `${OWEN_RIGHTS} Interpretive plaque history is separate from statutory heritage listing, designation or district status.`),
  scope("shortTermRentalLicences", `${city}/business-building-development/short-term-rentals/str-registry/`, "The City publishes a list of issued STR licence numbers and addresses, without verified expiry or current operative status. A licence number occurs against different addresses in the published list; confirm unique identity directly. Compatible table redistribution rights, complete current licensing, underlying lawful unit/occupancy, suspension/expiry and property-specific status remain unverified. The table was not extracted, matched or counted."),
  scope("servicingEvidence", OWEN_INQUIRY, "Engineering's PIR scope is existing municipal service availability, with camera investigation priced separately. Availability and a County settlement label do not establish actual subject connections, condition, capacity, paid charges or ARU eligibility. Obtain authorized engineering/utility/as-built evidence for the proposed use."),
  scope("owenSoundConservationRegulation", "https://www.greysauble.on.ca/planning-regulations/plan-inputreview-regulations/", "Original GSCA guidance identifies Ontario Regulation 41/24, shoreline/river/wetland/hazard work and activity-specific exemptions requiring staff confirmation. Its mapping licence prohibits scraping/data transfer/disclosure while separately permitting attributed generated map products under its conditions. No map agreement was accepted or authority property query performed. County mapping constraints warn of unmapped watercourses/wetlands and say regulation text prevails; its separate SVCA notice still mentions legacy 169/06. City GSCA regulation/hazard labels and historical County karst/woodland/valleyland or generalized provincial source-protection references are separate from current parcel-wide original-authority regulation, vulnerable areas and policies. Confirm jurisdiction and proposed-work requirements; no clearance, hazard absence, water-safety or insurance conclusion.", "https://www.greysauble.on.ca/mapping-gis/mapping-application-terms-of-use/"),
];
export const OWEN_AUDIT = { city: "Owen Sound", auditedAt: "2026-10-04", map: OWEN_MAP, terms: OWEN_TERMS, rightsFinding: OWEN_RIGHTS, featureQueriesPerformed: false, countsQueried: false, geometryQueried: false, registryExtracted: false, recordSearchRequested: false, complete: false, metadata: { experience: "f3a1262f41be4ce78ca5b0db09782b38", webMaps: ["24766fa78a1a491e96c43fae66658b69", "a0a1a295d1ec44eabbac99ff16ce46e0"], serviceItem: "2a312c8b568d4c8182d323b34367f0bf", selectedChildren: [0, 1, 3, 77, 79, 80], temporaryViewerError: "CONT_0001", planningAdoptedOrPassedDate: "2026-04-13", noticeDate: "2026-04-16", zoningAppealDeadline: "2026-05-06", countyApprovalVerified: false, currentAppealOutcomesVerified: false, fullCurrentInstrumentsVerified: false, adoptionMeetingDateConflict: true, zoningAppendedHeaderConflict: true, zoningNoticeSha256: "bc7480453dd61a69168fdf0c8d217a0a77a8bafdc46be3db0dbddc3bcdb3b0ce", planNoticeSha256: "2936690334279395df42cf2a4dd079fa071fc06c313ab3fc6be4a6a248327d40", aruGuideSha256: "9ab9f507a1d27b2979dddbed4b692df34b13c2ee8ef7afc954989765b65632cb", aruGuideDateVerified: false, strUniqueIdentityUnverified: true, independentCountyReferences: "Five licensed County settlement/historical-plan references counted once separately; other Grey municipalities require their own current local audits." } };
export const owenSoundMarket = (city: string | null | undefined, province: string | null | undefined) => cityKey(city ?? "") === "owen sound" && provinceKey(province ?? "") === "ontario";
export function owenSoundLayers(city: string | null | undefined, province: string | null | undefined): Record<string, Layer> { return owenSoundMarket(city, province) ? Object.fromEntries(OWEN_WITHHELD.map(g => [g.layer, layer("unavailable", { coverageComplete: false, screenPerformed: false, featureQueriesPerformed: false, countsQueried: false, geometryQueried: false, registryExtracted: false, recordSearchRequested: false, withheld: g, audit: { city: OWEN_AUDIT.city, auditedAt: OWEN_AUDIT.auditedAt } }, null, g.reason)])) : {}; }
export function owenSoundQuestions(city: string | null | undefined, province: string | null | undefined): EvidenceQuestion[] { return owenSoundMarket(city, province) ? [
  { topic: "owen_sound_current_planning", question: "Can City/County Planning provide OPA14's County decision, current appeals/effect and the operative 2010-078/2026-030 provisions and schedules? Reconcile the November 2025/2026 meeting-date and 2025-079/2026-030 header conflicts. Obtain full decisions, cleared conditions and approved/registered agreements; passage, final-file labels and an elapsed appeal deadline do not establish effect.", evidenceLayers: ["zoning", "officialPlan", "currentPlanningInstruments", "planningApplications", "variance", "consentToSever", "sitePlanControl", "greyHistoricalLandUseReference"] },
  { topic: "owen_sound_property_files_and_units", question: "Can the seller authorize the separate paid PIR scopes and provide full permit history, each advertised unit's occupancy permission, passed final inspections, outstanding conditions/work orders and current ARU/servicing evidence? Confirm actual connections/capacity and agreement releases separately. Occupancy can coexist with an open building permit pending final inspection; the undated guide is not current unit approval.", evidenceLayers: ["owenSoundPropertyInquiry", "permits", "inspectionResults", "occupancyDocuments", "additionalUnits", "servicingEvidence", "greySettlementReference"] },
  { topic: "owen_sound_heritage_str_and_constraints", question: "Can the Clerk confirm the full current heritage instruments and the STR licence's unique identity/current expiry or suspension, and can original authorities confirm parcel-wide regulation, source-protection policies and proposed-work requirements? Obtain a current survey and appropriate karst/ecological investigations where relevant. Interpretive plaques, historical County references and issued-licence labels are separate evidence.", evidenceLayers: ["heritage", "heritageDistrict", "historicPlaqueReference", "shortTermRentalLicences", "parcel", "owenSoundConservationRegulation", "greyHistoricalKarstReference", "greyHistoricalWoodlandReference", "greyHistoricalValleylandReference", "ontarioSourceProtectionAreaReference"] },
] : []; }
export function owenSoundCoverage() { return { cities: [OWEN_AUDIT.city], auditDate: OWEN_AUDIT.auditedAt, delivery: "metadata_only_reuse_audit", datasets: [], withheld: OWEN_WITHHELD.map(g => ({ ...g, status: "withheld", records: null })), complete: false, audit: OWEN_AUDIT, note: "Owen Sound City source-guidance audit with explicit reuse/current-instrument/property-file gaps. Five independently licensed County references appear and count only in their separate coverage entry. No City property records, counts, geometry, register extraction, request or payment occurred." }; }
