import type { Layer } from "./model";
import type { enrichProperty } from "./service";
export type PropertyResult = Extract<Awaited<ReturnType<typeof enrichProperty>>, { success: true }>;
const escape = (value: unknown): string => String(value).replace(/[&<>"']/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[char]!));
const label = (value: string) => value.replace(/([a-z])([A-Z])/g, "$1 $2").replace(/_/g, " ");
function safeLink(value: unknown): string | null { try { const u = new URL(String(value)); return u.protocol === "https:" ? u.href : null; } catch { return null; } }
function renderValue(value: unknown): string {
  if (value === null || value === undefined) return '<span class="unknown">Unknown / unpublished</span>';
  if (Array.isArray(value)) return value.length ? `<ol class="records">${value.map(item => `<li>${renderValue(item)}</li>`).join("")}</ol>` : '<p class="unknown">No returned records.</p>';
  if (typeof value === "object") return `<dl>${Object.entries(value).map(([key, item]) => `<div><dt>${escape(label(key))}</dt><dd>${renderValue(item)}</dd></div>`).join("")}</dl>`;
  const href = safeLink(value); return href ? `<a href="${escape(href)}" rel="noopener noreferrer">${escape(value)}</a>` : escape(value);
}
function renderLayer(name: string, layer: Layer): string {
  return `<section id="${escape(name)}"><h2>${escape(label(name))} <span class="badge">${escape(layer.status)}</span></h2>${layer.source ? `<p><a href="${escape(safeLink(layer.source.url) ?? "#")}" rel="noopener noreferrer">${escape(layer.source.name)}</a></p>` : ""}<p class="note">${escape(layer.note ?? "No additional source note.")}</p>${renderValue({ sourceUpdatedAt: layer.sourceUpdatedAt, retrievedAt: layer.retrievedAt, importedAt: layer.importedAt ?? null, truncated: layer.truncated ?? false })}${layer.data !== null ? renderValue(layer.data) : '<p class="unknown">No factual result returned for this layer.</p>'}${layer.source ? `<p class="attribution">${escape(layer.source.attribution)} · ${escape(layer.source.licence)}</p>` : ""}</section>`;
}
export function renderReport(result: PropertyResult): string {
  const title = [result.data.address, result.data.city, result.data.province].filter(Boolean).join(", ") || "Property at supplied coordinates";
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Property Forensics · ${escape(title)}</title><style>
:root{color-scheme:light;--ink:#132529;--accent:#14664f;--muted:#546b6d}*{box-sizing:border-box}body{margin:0;background:#edf3ef;color:var(--ink);font:16px/1.6 system-ui,sans-serif}main{max-width:1080px;margin:auto;padding:32px 24px}header{padding:40px;background:#142e2a;color:white;border-radius:20px}header p{color:#d6ece0}h1{font-size:clamp(28px,5vw,50px);line-height:1.15;margin:12px 0}h2{line-height:1.3;text-transform:capitalize}h3{margin-top:28px}section{background:white;border:1px solid #d4e3da;border-radius:14px;padding:28px;margin:20px 0;break-inside:avoid}a{color:var(--accent);overflow-wrap:anywhere}header a{color:#acf1cb}.eyebrow{text-transform:uppercase;letter-spacing:.16em;font-size:12px;color:#a1f3bd}.badge{font-size:12px;background:#eaf4ed;padding:4px 8px;border-radius:20px;white-space:nowrap}.note,.unknown,.attribution{color:var(--muted)}.attribution{font-size:12px;border-top:1px solid #dce7df;padding-top:16px}dl{margin:8px 0}dl>div{display:grid;grid-template-columns:minmax(140px,27%) 1fr;gap:16px;padding:7px 0;border-bottom:1px solid #eef2ef}dt{font-weight:600;text-transform:capitalize}dd{margin:0;overflow-wrap:anywhere}dd dl>div{display:block}dd dt{font-size:12px;color:var(--muted)}ol.records{padding-left:24px}ol.records>li{margin-bottom:18px}nav{display:flex;flex-wrap:wrap;gap:10px;margin:20px 0}nav a{background:white;padding:6px 12px;border-radius:16px}footer{font-size:13px;color:var(--muted)}@media(max-width:600px){main{padding:12px}section,header{padding:20px}dl>div{display:block}dt{font-size:12px}}@media print{body{background:white;font-size:11px}main{max-width:none;padding:0}header{background:white;color:#132529;border:1px solid #ccc}header p,.eyebrow{color:#132529}section{border-radius:0;padding:14px;break-inside:auto}nav{display:none}a{color:inherit}h2{break-after:avoid}}
</style></head><body><main><header><div class="eyebrow">Homies · Property Forensics</div><h1>${escape(title)}</h1><p>Pre-showing briefing and full public-record evidence</p><p>Generated ${escape(new Date().toISOString())} · ${result.available.length} available layers · ${result.missing.length} coverage gaps</p></header><nav>${Object.keys(result.layers).map(name => `<a href="#${escape(name)}">${escape(label(name))}</a>`).join("")}</nav><section><h2>Before the showing</h2>${renderValue(result.brief)}<h3>Research notes</h3>${renderValue(result.notes)}</section><section><h2>Property identification</h2>${renderValue({ address: result.data.address, city: result.data.city, province: result.data.province, latitude: result.data.latitude, longitude: result.data.longitude, query: result.query })}</section>${Object.entries(result.layers).map(([name, value]) => renderLayer(name, value)).join("")}<footer>Public-record research can guide questions and document requests. Source observation dates, retrieval dates and import dates have different meanings. Unknown and unsupported results remain visible. Re-run the lookup to refresh this report; a saved artifact is a dated snapshot.</footer></main></body></html>`;
}
