import { cityKey, layer, type Layer } from "./model";
import { provinceKey } from "./geocode";
import type { EvidenceQuestion } from "./brief";

const city = "https://www.stratford.ca", county = "https://www.perthcounty.ca";
export const STRATFORD_PLANNING = `${city}/live-here/building-and-planning-services/planning/`;
export const STRATFORD_BUILDING = `${city}/live-here/building-and-planning-services/building/`;
export const STRATFORD_TERMS = `${city}/inside-city-hall/privacy-policy/`;
export const STRATFORD_MAP = "https://maps.stratford.ca/gisportal/apps/experiencebuilder/experience/?id=758c96921906478889c5fa4e82a66bf3";
const countyMaps = `${county}/living-here/gis-maps/`, countyTerms = `${county}/terms-of-use-privacy-and-accessibility-policy/`;
export const STRATFORD_ARU = "https://media-003-ca.cdn.govstack.com/stratford-ca/media/vdohblha/additional-residential-units-pamphlet-04092026.pdf";
export const STRATFORD_ZONING = `${city}/media/rkjpnn05/_stratford-zoning-by-law-final-november-2021-part-2-preamble-to-section-14-for-web.pdf`;
export const STRATFORD_RIGHTS = "The exact City experience, web map and original public service item have blank reuse grants; selected typed children have blank copyright/description. City website terms allow personal, educational and non-commercial reproduction, with separate third-party/map/document rights. No compatible commercial merged-data redistribution grant was established for these selected City layers. This finding does not apply those terms automatically to independently licensed original provincial sources. The County Lite map separately requires written permission for commercial/legal reproduction and restricts MPAC products to assessment/tax purposes; its parcel/lots/address items have no affirmative reuse grant. No City/County property feature/count/geometry queries or dataset integration were performed.";
const scope = (layer: string, url: string, reason: string, termsUrl = STRATFORD_TERMS) => ({ layer, url, reason, termsUrl });
export const STRATFORD_WITHHELD = [
  scope("municipalAddresses", STRATFORD_MAP, `${STRATFORD_RIGHTS} Generic City civic-label point placement is unverified and is not promoted to a building, unit or legal parcel identity.`),
  scope("parcel", STRATFORD_MAP, `${STRATFORD_RIGHTS} City and County reference parcels are separate from current Ontario Land Surveyor/title evidence; PIN, roll, ownership and legal boundary geometry are not reused.`),
  scope("catalogueZoningReference", STRATFORD_MAP, `${STRATFORD_RIGHTS} Child 15 is labelled Comprehensive Zoning By-Law 2022. Reference labels do not establish current written rules, exceptions/holds, amendments/appeals or permission.`),
  scope("zoning", STRATFORD_PLANNING, "The current City page identifies By-law 10-2022, but its offered 213-page text is marked Final for Council Adoption – January 2022. Its preamble warns of unconsolidated amendments/holds, out-of-date mapping and unreflected minor variances. Sections 4.24 use older second-suite rules, separately from the current ARU pamphlet. Confirm the currently operative written bylaw, exceptions, schedules, amendments, holds, variance decisions and appeals; the full current instruments are not verified."),
  ...["currentPlanningInstruments", "officialPlan"].map(name => scope(name, STRATFORD_PLANNING, "The City offers an Official Plan file labelled 2026-tbd/final consolidated to OPA 36 and a separate land-use schedule. Filename labels do not establish effective dates or a complete current consolidation. Obtain current adopted text/schedules, unconsolidated amendments and appeal outcomes. Perth County's plan applies to its four member municipalities; it is not automatically Stratford's governing plan.")),
  ...["planningApplications", "variance", "consentToSever", "sitePlanDrawings", "sitePlanControl"].map(name => scope(name, STRATFORD_PLANNING, "City application/Committee notices and site-plan process guidance are manual research routes. A future meeting notice is not a decision or approval. Obtain full decisions, cleared conditions, approved drawings, signed/registered agreements, expiry and appeals. The selected eSCRIBE agenda returned HTTP403 and was not bypassed; no vote/adopted amendment was verified.")),
  ...["permits", "inspectionResults", "occupancyDocuments"].map(name => scope(name, STRATFORD_BUILDING, "The City's paid Zoning and Building Information Report offers zoning/permitted uses, recent permits, outstanding inspections and work orders. Recent/outstanding observations are separate from complete historic permits, passed inspections and occupancy evidence. Obtain full authorized property files and each advertised unit's permits/final inspections/occupancy; no report was requested, paid for or completed.")),
  scope("stratfordBuildingReports", STRATFORD_BUILDING, "The City offers a 2024–2025 building-permit revenue report. Its PDF contents, property observations, reusable publication rights and a complete current series are not integrated or counted. Annual revenue/activity does not establish complete property permit history or final inspections."),
  scope("additionalUnits", STRATFORD_ARU, "The current offered pamphlet describes up to three total units per lot (three in the main dwelling, or two main plus one accessory), subject to residential zoning, municipal water/sanitary sewer and zoning requirements, with building/ESA permits. The webpage also lists combinations of ARUs implying four total units: preserve this conflict. Older offered second-suite rules are a separate vintage. The pamphlet filename 04092026 has no verified unambiguous publication/effective date. No current unit register, adopted current provisions, actual connection/capacity, unit approval/occupancy or development-charge exemption is verified."),
  ...["heritage", "heritageDistrict"].map(name => scope(name, `${city}/live-here/heritage-stratford/heritage-conservation-district/`, "The City provides designated/non-designated heritage pages and identifies a Part V City Centre Core district with a static map and heritage-permit guidance. The complete current statutory register, property-specific designation/attributes, district boundary/instruments, amendments/appeals and approvals remain unverified. No register was extracted/count queried or district image converted to geometry.")),
  scope("propertySurveyRecords", STRATFORD_BUILDING, "The City may hold an owner-supplied survey copy, subject to registered-owner/photo-ID or authorized-agent access, availability and a fee when located. Planning guidance estimates five days while Building estimates three: confirm current timing and release eligibility. Older copies can be outdated; obtain a current Ontario Land Surveyor survey/title review. No request or payment was made."),
  scope("buildingFootprintReference", STRATFORD_MAP, `${STRATFORD_RIGHTS} City child 23 has elevation/thickness/area fields, but units, datum, vintage and meaning are unverified. No geometry, height, area, current building existence/condition or legal unit count is inferred.`),
  scope("shortTermRentalLicences", STRATFORD_MAP, `${STRATFORD_RIGHTS} City child 144 has address/licence/accommodation-type labels, without verified current expiry/approval evidence. A map label is separate from an operative licence and lawful unit/occupancy; records remain unqueried.`),
  scope("stratfordConservationRegulation", "https://thamesriver.on.ca/planning-permits-maps/regulation-section-28/", "UTRCA's current page identifies Regulation 41/24 and says policies/mapping are being updated. Its separate map-data licence requires written consent to disclose/sublicence data or derivative data, while expressly allowing attributed generated map products; an API data grant was not established. No agreement was accepted or authority property query performed. City UTRCA_REG fields and the independently licensed provincial generalized source-protection reference are separate from current original-authority parcel-wide regulation, floodplain, vulnerable areas and activity-specific plan policies. Confirm jurisdiction, current instruments and proposed-work requirements directly; no clearance, water-safety or insurance conclusion is available.", "https://maps.thamesriver.on.ca/terms-of-use.aspx"),
  scope("countyPlanningReference", countyMaps, "Perth County's exact Lite experience has a scoped written-permission commercial/legal reproduction notice and MPAC assessment-purpose restriction; selected original parcel/lots/address grants are blank. The County plan effective September 12, 2025 covers North Perth, West Perth, Perth East and Perth South. Those municipalities and St. Marys remain separately unaudited; no County/internal-viewer property feed was queried or counted.", countyTerms),
];
export const STRATFORD_AUDIT = { city: "Stratford", auditedAt: "2026-10-03", map: STRATFORD_MAP, terms: STRATFORD_TERMS, rightsFinding: STRATFORD_RIGHTS, featureQueriesPerformed: false, countsQueried: false, geometryQueried: false, recordSearchRequested: false, complete: false, metadata: { experience: "758c96921906478889c5fa4e82a66bf3", webMap: "5bb340987a8d404ea246846e504bccb7", serviceItem: "592bec2ddbdf432eb828331787c9f494", selectedChildren: [15, 18, 19, 23, 24, 27, 144], countyLiteExperience: "8a2c876bab7c414fa5ef80ca686f5806", countyInternalViewerQueried: false, aruGuidanceConflict: true, aruDocumentDateVerified: false, aruDocumentSha256: "137ad0df7ec72d99214b258cf649417b9efea74cda5f3f6c219d420037782a63", offeredZoningText: STRATFORD_ZONING, zoningTextSha256: "cd880c73dfb0837ee78b7373a0ee5611012d32281261600e805b7a3a01351933", zoningReviewedPDFPages: [20, 120, 121, 122], fullCurrentInstrumentsVerified: false, surveyTurnaroundGuidanceVaries: true, buildingRevenueReportParsed: false, independentProvinceReference: "Original Ontario OGL generalized source-protection area reference, counted once separately; not County/City or current vulnerable-area data." } };
export function stratfordMarket(name: string | null | undefined, province: string | null | undefined): boolean { return provinceKey(province ?? "") === "ontario" && cityKey(name ?? "") === "stratford"; }
export function stratfordLayers(name: string | null | undefined, province: string | null | undefined): Record<string, Layer> {
  return stratfordMarket(name, province) ? Object.fromEntries(STRATFORD_WITHHELD.map(g => [g.layer, layer("unavailable", { coverageComplete: false, screenPerformed: false, featureQueriesPerformed: false, countsQueried: false, geometryQueried: false, recordSearchRequested: false, withheld: g, audit: { city: STRATFORD_AUDIT.city, auditedAt: STRATFORD_AUDIT.auditedAt, terms: STRATFORD_TERMS } }, null, g.reason)])) : {};
}
export function stratfordQuestions(name: string | null | undefined, province: string | null | undefined): EvidenceQuestion[] {
  return stratfordMarket(name, province) ? [
    { topic: "stratford_current_planning_and_units", question: "Can City Planning reconcile the three-total-unit pamphlet with webpage combinations implying four and confirm currently adopted ARU/10-2022 rules, exceptions/holds, amendments/appeals, operative City plan/schedules and each advertised unit's approved identity? Obtain final planning/Committee decisions, cleared conditions and approved/registered site-plan instruments; notices and older second-suite rules are separate evidence.", evidenceLayers: ["additionalUnits", "zoning", "currentPlanningInstruments", "officialPlan", "planningApplications", "variance", "consentToSever", "sitePlanDrawings", "sitePlanControl"] },
    { topic: "stratford_property_files_and_surveys", question: "Can the seller authorize the paid Zoning and Building Information Report and provide full historical permits, final inspections, work orders, occupancy and actual servicing/capacity evidence? Confirm survey-copy authorization, availability, fees and the three/five-day guidance difference directly; obtain a current survey/title review. Recent permits or outstanding inspections are separate from complete history and passed finals.", evidenceLayers: ["permits", "inspectionResults", "occupancyDocuments", "propertySurveyRecords", "stratfordBuildingReports"] },
    { topic: "stratford_heritage_and_constraints", question: "Can the Clerk provide current listed/designated/City Centre Core district instruments and appeal outcomes, and can original authorities confirm parcel-wide regulation, current source-protection vulnerable areas/policies and proposed-work requirements? Historic generalized labels, GIS licence flags, building elevation fields and Riverbend service flags do not establish legal status, measurements, current STR approval or actual connection.", evidenceLayers: ["heritage", "heritageDistrict", "stratfordConservationRegulation", "ontarioSourceProtectionAreaReference", "buildingFootprintReference", "shortTermRentalLicences"] },
  ] : [];
}
export function stratfordCoverage() { return { cities: [STRATFORD_AUDIT.city], auditDate: STRATFORD_AUDIT.auditedAt, delivery: "metadata_only_reuse_audit", datasets: [], withheld: STRATFORD_WITHHELD.map(g => ({ ...g, status: "withheld", records: null })), complete: false, audit: STRATFORD_AUDIT, note: "Stratford/Perth source-guidance audit with explicit gaps. Original independently licensed provincial reference rows are counted once in their own coverage entry. No City/County property feed is integrated or counted, and other Perth municipalities/St. Marys remain separately unaudited." }; }
