import type { Source } from "./model";
export const SUDBURY_WITHHELD = [
  { layer: "completePermitHistory", url: "https://www.greatersudbury.ca/live/building-and-renovating/open-permit-search/", reason: "The licensed Pronto/Accela feed includes archived observations, but older history completeness, unrecognized statuses, former-municipality crosswalks, exact unit identity, independently verified final inspections and occupancy remain unverified. Raw Complete is not silently changed to the legend's Completed." },
  { layer: "currentPlanningInstruments", url: "https://www.greatersudbury.ca/city-hall/reports-studies-policies-and-plans/official-plan/", reason: "Current written 2010-100Z provisions, exceptions, holds, amendments and appeals require official instruments; printed publications take precedence. The City identifies the Phase 1 Official Plan review effective April 26, 2019 separately from the ongoing Phase 2 review. No current property-level plan schedule adapter is verified." },
  { layer: "planningApplications", url: "https://www.greatersudbury.ca/do-business/planning-and-development/participate-in-the-planning-process/", reason: "The current public planning process, meeting notices and Pronto application workflow do not establish a complete licensed property application/decision/conditions/appeal feed in the inspected open catalogue. No such records or counts are queried." },
  { layer: "variance", url: "https://www.greatersudbury.ca/do-business/planning-and-development/", reason: "The City provides Committee of Adjustment and consent-process guidance. A complete current licensed property decision/conditions/appeal adapter remains unverified; no variance or consent records/counts are queried." },
  { layer: "heritage", url: "https://www.greatersudbury.ca/do-business/planning-and-development/heritage-properties/", reason: "The City distinguishes designated and listed properties and links a separate heritage story map with blank item licence and a 2017 edit. Exact current register/district instruments and originating reuse binding are unverified. A roofline heritage flag is not the current register; no separate heritage records/counts are queried." },
  { layer: "additionalUnits", url: "https://www.greatersudbury.ca/live/building-and-renovating/", reason: "Permit project dwelling-units/bedrooms-created fields do not establish advertised unit legality. A current licensed property registration, final-inspection and occupancy register remains unverified." },
  { layer: "wellheadProtection", url: "https://www.arcgis.com/home/item.html?id=136737a7125249159d2d007ef711c03f", reason: "The current City map uses a separate source-water feed outside the inspected open group with blank item grant. Originating source-protection rights, current policy binding and typed adapter are unverified; no record/count/geometry queries." },
  { layer: "intakeProtection", url: "https://www.arcgis.com/home/item.html?id=e31b5f2486354ae78288af7a7ecdf4e4", reason: "The City map's separate intake-protection feed has blank item licence outside the inspected curated catalogue. Originating rights/current policy adapter are unverified; no record/count/geometry queries." },
  { layer: "watershedReference", url: "https://www.arcgis.com/home/item.html?id=bd2b7b73f3784cf7a207e574cb8fd7e1", reason: "Separate Ramsey Lake watershed mapping is outside the inspected open group with blank item grant. Originating grant/vintage/typed source are unverified; no record/count/geometry queries or water safety conclusions." },
  { layer: "airportConstraints", url: "https://www.greatersudbury.ca/do-business/zoning/", reason: "The City map's separate AHR1/AHR2 surface items have blank grants outside the inspected open group. Current originating airport rights, height/vertical datum and legally applicable instruments are unverified; no constraint records/counts/geometry are queried." },
  { layer: "floodplainOverlay", url: "https://www.arcgis.com/home/item.html?id=c59aad79155e4f58824bcd42e3e5c0b4", reason: "The City map's separate Flood_Plain item has blank grant outside the inspected open group. Originating conservation-authority rights, vintage, complete regulation and flood mapping remain unverified; no record/count/geometry queries or safety/insurance conclusions." },
  { layer: "sudburyConservationRegulation", url: "https://www.greatersudbury.ca/do-business/planning-and-development/", reason: "The relevant conservation authority must confirm current parcel-wide regulation and proposed-work requirements. Zoning/roofline/parcel references do not establish flood, environmental, regulatory or insurance clearance." },
];
export interface SudburyFeed { key:string; item:string; itemUrl:string; owner:string; rootUrl:string; url:string; child:number; title:string; layerName:string; geometry:string; oid:string; accessInformation:string|null; rootCopyright:string; copyright:string; rootDescriptionHash:string; descriptionHash:string; itemDescriptionHash:string; termsHash:string; fields:Record<string,string>; fieldTypes:Record<string,string>; note:string; source:Source; }
export const SUDBURY_GRANT={
  "site": "15b5f74271704cc99bb029b62f12356d",
  "siteTitle": "City of Greater Sudbury Open Data",
  "siteType": "Web Mapping Application",
  "siteOwner": "Open.Data",
  "siteUrl": "https://opendata-Sudbury.opendata.arcgis.com",
  "catalogueUrl": "https://opendata.greatersudbury.ca",
  "org": "q3mIlR87lZlZsds3",
  "group": "5bb3fe014a714e8b9f0102f5fcb7f8a8",
  "groupTitle": "Open Data",
  "groupOwner": "Open.Data",
  "officialOffer": "https://www.greatersudbury.ca/city-hall/open-government/open-data/",
  "policyUrl": "https://www.greatersudbury.ca/city-hall/open-government/open-data/policy/",
  "licenceUrl": "https://www.greatersudbury.ca/city-hall/open-government/open-data/licence/",
  "siteTermsHash": "6f4e3c182704b72d26241ed51006e242a133945cbad8388d0b81077801548b58",
  "fullGrantHash": "10284328ae7bb38dd93dafa18744c86aeacb45a944a544c31123a73728c02963",
  "policyHash": "3817b9edf1253e39330d2e0e6b1f89e4a312b2f7b9ce48c22d5d16a5417365b2",
  "offerHash": "f02ee3de548d2350765185807ec1284a4e8c5fe88d7ec27535f0b963b8455c5d"
};
// The City current zoning link is a lineage check, not a licence for every map layer.
export const SUDBURY_ZONING_MAP = {
  officialOffer: "https://www.greatersudbury.ca/do-business/zoning/",
  offerHash: "6cd9c3872a3b6cf23c395a4f97fd48a70fa7eba8062b7fbeb217eb681477a62e",
  app: "57094561875b4260b719f9e6caaf4154",
  appTitle: "Zoning App",
  appUrl: "https://sudbury.maps.arcgis.com/apps/webappviewer/index.html?id=57094561875b4260b719f9e6caaf4154",
  map: "5e528bc3c41b41b8ba8658dc7a505246",
  mapTitle: "Zone Map Ver6",
  owner: "tek04pla",
};
export const SUDBURY_FEEDS:SudburyFeed[]=[
  {
    "key": "municipalAddresses",
    "item": "d3b94bd7d0a14b4b97b3757d1a383dd4",
    "itemUrl": "https://services.arcgis.com/q3mIlR87lZlZsds3/arcgis/rest/services/Address_and_Building_Roofline/FeatureServer",
    "owner": "Greater.Sudbury",
    "rootUrl": "https://services.arcgis.com/q3mIlR87lZlZsds3/arcgis/rest/services/Address_and_Building_Roofline/FeatureServer",
    "url": "https://services.arcgis.com/q3mIlR87lZlZsds3/arcgis/rest/services/Address_and_Building_Roofline/FeatureServer/2",
    "child": 2,
    "title": "Address and Building Roofline",
    "layerName": "Address",
    "geometry": "esriGeometryPoint",
    "oid": "OBJECTID",
    "accessInformation": null,
    "rootCopyright": "",
    "copyright": "",
    "rootDescriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "descriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "itemDescriptionHash": "2195f729ce7923c18cbe902df0e782d35d981216e5a23113d5fccc464144db57",
    "termsHash": "42cd7b82054b42389662e19472a96457fc5dcbefc9fa84d1c2e816b446e813b2",
    "fields": {
      "OBJECTID": "recordId",
      "FULLADDRESSTEXT": "publishedAddress",
      "ADDRESSNUMBERPREFIX": "numberPrefix",
      "ADDRESSNUMBER": "number",
      "ADDRESSNUMBERSUFFIX": "numberSuffix",
      "FULLSTREETNAME": "publishedStreet",
      "ADDRESSID": "publishedAddressId",
      "STYPE": "publishedAddressType",
      "ADDRESSLIFECYCLESTATUS": "publishedLifecycleStatus",
      "COMMUNITY": "publishedCommunity",
      "ASSIGNEDADDRESSID": "assignedAddressId",
      "UNIT_OR_AMENITY": "publishedUnitOrAmenity",
      "UNIT_AMENITY_TYPE": "publishedUnitAmenityType",
      "LASTUPDATE": "publishedRecordUpdateDate",
      "CREATEDATE": "publishedRecordCreateDate",
      "VERIFIED_DATE": "publishedAddressVerificationDate"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "FULLADDRESSTEXT": "esriFieldTypeString",
      "ADDRESSNUMBERPREFIX": "esriFieldTypeString",
      "ADDRESSNUMBER": "esriFieldTypeString",
      "ADDRESSNUMBERSUFFIX": "esriFieldTypeString",
      "FULLSTREETNAME": "esriFieldTypeString",
      "ADDRESSID": "esriFieldTypeString",
      "STYPE": "esriFieldTypeString",
      "ADDRESSLIFECYCLESTATUS": "esriFieldTypeString",
      "COMMUNITY": "esriFieldTypeString",
      "ASSIGNEDADDRESSID": "esriFieldTypeString",
      "UNIT_OR_AMENITY": "esriFieldTypeString",
      "UNIT_AMENITY_TYPE": "esriFieldTypeString",
      "LASTUPDATE": "esriFieldTypeDate",
      "CREATEDATE": "esriFieldTypeDate",
      "VERIFIED_DATE": "esriFieldTypeDate"
    },
    "note": "Exact full civic address and components, community, active/retired, primary/secondary and unit/amenity distinctions are retained. Only one complete active primary point with unambiguous building address identity may select a source civic location. Address dates are administrative events, not construction dates; no legal unit or cadastral identity is established.",
    "source": {
      "id": "sudbury:municipalAddresses",
      "name": "Greater Sudbury — Address",
      "url": "https://www.arcgis.com/home/item.html?id=d3b94bd7d0a14b4b97b3757d1a383dd4",
      "licence": "City of Greater Sudbury Open Data Licence 1.0",
      "licenceUrl": "https://www.greatersudbury.ca/city-hall/open-government/open-data/licence/",
      "attribution": "Contains information licensed under the Open Data Licence – City of Greater Sudbury. Selected attributes are renamed by Homies / Realist; no City endorsement."
    }
  },
  {
    "key": "permits",
    "item": "5c72bc458cc34af9b4df00b8bc938151",
    "itemUrl": "https://services.arcgis.com/q3mIlR87lZlZsds3/arcgis/rest/services/Building Permits/FeatureServer",
    "owner": "Open.Data",
    "rootUrl": "https://services.arcgis.com/q3mIlR87lZlZsds3/arcgis/rest/services/Building%20Permits/FeatureServer",
    "url": "https://services.arcgis.com/q3mIlR87lZlZsds3/arcgis/rest/services/Building%20Permits/FeatureServer/0",
    "child": 0,
    "title": "Building Permits",
    "layerName": "Building_Permits",
    "geometry": "esriGeometryPoint",
    "oid": "OBJECTID",
    "accessInformation": null,
    "rootCopyright": "",
    "copyright": "",
    "rootDescriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "descriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "itemDescriptionHash": "d3f5170c983bb2133d49dfd54fd59f9d191a7472045a1814383221bcb6ef8897",
    "termsHash": "46cf51b31983fddec1ee7dd057f6b6a958dc6b658bd1af1cd51200a234cd72f4",
    "fields": {
      "OBJECTID": "recordId",
      "RecordNumber": "permitNumber",
      "RecordType": "publishedRecordType",
      "RecordStatus": "publishedStatus",
      "Module": "publishedModule",
      "Address": "publishedAddress",
      "ParentRecordNumber": "publishedParentRecordNumber",
      "SubmittedDate": "publishedSubmittedDate",
      "IssuedDate": "publishedIssuedDate",
      "PermitType": "publishedPermitType",
      "LandUse": "publishedProjectLandUse",
      "StructureDetails": "publishedStructureDetails",
      "ClassificationType": "publishedClassificationType",
      "DwellingUnitsCreated": "publishedProjectDwellingUnitsCreated",
      "BedroomsCreated": "publishedProjectBedroomsCreated",
      "Storeys": "publishedProjectStoreys",
      "Length": "publishedProjectLength",
      "Width": "publishedProjectWidth",
      "Height": "publishedProjectHeight",
      "BuildingMeasureUnit": "publishedProjectMeasureUnit",
      "Ground": "publishedProjectGround",
      "Gross": "publishedProjectGross",
      "EstimatedValue": "publishedProjectEstimatedValue"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "RecordNumber": "esriFieldTypeString",
      "RecordType": "esriFieldTypeString",
      "RecordStatus": "esriFieldTypeString",
      "Module": "esriFieldTypeString",
      "Address": "esriFieldTypeString",
      "ParentRecordNumber": "esriFieldTypeString",
      "SubmittedDate": "esriFieldTypeString",
      "IssuedDate": "esriFieldTypeString",
      "PermitType": "esriFieldTypeString",
      "LandUse": "esriFieldTypeString",
      "StructureDetails": "esriFieldTypeString",
      "ClassificationType": "esriFieldTypeString",
      "DwellingUnitsCreated": "esriFieldTypeDouble",
      "BedroomsCreated": "esriFieldTypeDouble",
      "Storeys": "esriFieldTypeDouble",
      "Length": "esriFieldTypeDouble",
      "Width": "esriFieldTypeDouble",
      "Height": "esriFieldTypeDouble",
      "BuildingMeasureUnit": "esriFieldTypeString",
      "Ground": "esriFieldTypeDouble",
      "Gross": "esriFieldTypeDouble",
      "EstimatedValue": "esriFieldTypeDouble"
    },
    "note": "Published Pronto/Accela permit observations, including archived files, match the exact civic address and confirmed community. Preserve raw statuses and separate submitted/issued dates. The City legend does not define every raw status (e.g. Complete differs from Completed); no silent status remapping. Projects and dimensions/units/value are not current building area, construction year, market value, legal units, occupancy or independently verified final inspections. Ground/Gross area units and estimated-value currency are unverified; do not convert or total repeated files. Unmapped former-municipality addresses and complete history remain gaps. Personal/applicant/contractor data and free-text project descriptions are excluded.",
    "source": {
      "id": "sudbury:permits",
      "name": "Greater Sudbury — Building Permits",
      "url": "https://www.arcgis.com/home/item.html?id=5c72bc458cc34af9b4df00b8bc938151",
      "licence": "City of Greater Sudbury Open Data Licence 1.0",
      "licenceUrl": "https://www.greatersudbury.ca/city-hall/open-government/open-data/licence/",
      "attribution": "Contains information licensed under the Open Data Licence – City of Greater Sudbury. Selected attributes are renamed by Homies / Realist; no City endorsement."
    }
  },
  {
    "key": "zoning",
    "item": "80a3131be75b481582675297c89d267a",
    "itemUrl": "https://services.arcgis.com/q3mIlR87lZlZsds3/arcgis/rest/services/Land_Use_and_Boundaries_view/FeatureServer",
    "owner": "Greater.Sudbury",
    "rootUrl": "https://services.arcgis.com/q3mIlR87lZlZsds3/arcgis/rest/services/Land_Use_and_Boundaries_view/FeatureServer",
    "url": "https://services.arcgis.com/q3mIlR87lZlZsds3/arcgis/rest/services/Land_Use_and_Boundaries_view/FeatureServer/1",
    "child": 1,
    "title": "Land Use and Boundaries",
    "layerName": "Zoning",
    "geometry": "esriGeometryPolygon",
    "oid": "OBJECTID",
    "accessInformation": null,
    "rootCopyright": "",
    "copyright": "",
    "rootDescriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "descriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "itemDescriptionHash": "a32648e48aea2f32e3abf4cafd3f6a9c4bdf94fe76b30e541ac44f12bf433ba1",
    "termsHash": "42cd7b82054b42389662e19472a96457fc5dcbefc9fa84d1c2e816b446e813b2",
    "fields": {
      "OBJECTID": "recordId",
      "ZONING": "publishedZone",
      "ROOTZONE": "publishedRootZone",
      "ZONEDESCRIPTION": "publishedZoneDescription"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "ZONING": "esriFieldTypeString",
      "ROOTZONE": "esriFieldTypeString",
      "ZONEDESCRIPTION": "esriFieldTypeString"
    },
    "note": "The selected zone layer is the same fixed source in the City current interactive zoning map. Read full labels including exceptions/holds; written 2010-100Z provisions, amendments, appeals, parcel-wide coverage and current legal applicability still need official instruments. Outdated PDF maps are not substituted.",
    "source": {
      "id": "sudbury:zoning",
      "name": "Greater Sudbury — Zoning",
      "url": "https://www.arcgis.com/home/item.html?id=80a3131be75b481582675297c89d267a",
      "licence": "City of Greater Sudbury Open Data Licence 1.0",
      "licenceUrl": "https://www.greatersudbury.ca/city-hall/open-government/open-data/licence/",
      "attribution": "Contains information licensed under the Open Data Licence – City of Greater Sudbury. Selected attributes are renamed by Homies / Realist; no City endorsement."
    }
  },
  {
    "key": "temporaryZoning",
    "item": "dbad763950d0415c85c413360e71c2dc",
    "itemUrl": "https://services.arcgis.com/q3mIlR87lZlZsds3/arcgis/rest/services/Temporary_Zoning_/FeatureServer",
    "owner": "Greater.Sudbury",
    "rootUrl": "https://services.arcgis.com/q3mIlR87lZlZsds3/arcgis/rest/services/Temporary_Zoning_/FeatureServer",
    "url": "https://services.arcgis.com/q3mIlR87lZlZsds3/arcgis/rest/services/Temporary_Zoning_/FeatureServer/0",
    "child": 0,
    "title": "Temporary Zoning",
    "layerName": "Temporary Zoning",
    "geometry": "esriGeometryPolygon",
    "oid": "OBJECTID",
    "accessInformation": null,
    "rootCopyright": "",
    "copyright": "",
    "rootDescriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "descriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "itemDescriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "termsHash": "42cd7b82054b42389662e19472a96457fc5dcbefc9fa84d1c2e816b446e813b2",
    "fields": {
      "OBJECTID": "recordId",
      "ZONING": "publishedZone",
      "WARD": "publishedWard",
      "BYLAW": "publishedBylaw",
      "BYLAWDATE": "publishedBylawDate",
      "BYLAWLABEL": "publishedBylawLabel",
      "LOT": "publishedLotReference",
      "CONCESSION": "publishedConcessionReference",
      "LASTUPDATE": "publishedRecordUpdateDate"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "ZONING": "esriFieldTypeString",
      "WARD": "esriFieldTypeString",
      "BYLAW": "esriFieldTypeString",
      "BYLAWDATE": "esriFieldTypeDate",
      "BYLAWLABEL": "esriFieldTypeString",
      "LOT": "esriFieldTypeString",
      "CONCESSION": "esriFieldTypeString",
      "LASTUPDATE": "esriFieldTypeDate"
    },
    "note": "Published temporary-zoning reference in the current City interactive map. Bylaw identifiers/dates are separate from expiry, extensions, adoption, appeals and current effect; none of those is established by a polygon match.",
    "source": {
      "id": "sudbury:temporaryZoning",
      "name": "Greater Sudbury — Temporary Zoning",
      "url": "https://www.arcgis.com/home/item.html?id=dbad763950d0415c85c413360e71c2dc",
      "licence": "City of Greater Sudbury Open Data Licence 1.0",
      "licenceUrl": "https://www.greatersudbury.ca/city-hall/open-government/open-data/licence/",
      "attribution": "Contains information licensed under the Open Data Licence – City of Greater Sudbury. Selected attributes are renamed by Homies / Realist; no City endorsement."
    }
  },
  {
    "key": "buildingFootprintReference",
    "item": "d3b94bd7d0a14b4b97b3757d1a383dd4",
    "itemUrl": "https://services.arcgis.com/q3mIlR87lZlZsds3/arcgis/rest/services/Address_and_Building_Roofline/FeatureServer",
    "owner": "Greater.Sudbury",
    "rootUrl": "https://services.arcgis.com/q3mIlR87lZlZsds3/arcgis/rest/services/Address_and_Building_Roofline/FeatureServer",
    "url": "https://services.arcgis.com/q3mIlR87lZlZsds3/arcgis/rest/services/Address_and_Building_Roofline/FeatureServer/3",
    "child": 3,
    "title": "Address and Building Roofline",
    "layerName": "Building Roofline",
    "geometry": "esriGeometryPolygon",
    "oid": "OBJECTID",
    "accessInformation": null,
    "rootCopyright": "",
    "copyright": "",
    "rootDescriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "descriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "itemDescriptionHash": "2195f729ce7923c18cbe902df0e782d35d981216e5a23113d5fccc464144db57",
    "termsHash": "42cd7b82054b42389662e19472a96457fc5dcbefc9fa84d1c2e816b446e813b2",
    "fields": {
      "OBJECTID": "recordId",
      "BUILDINGID": "publishedBuildingId",
      "STYPE": "publishedStructureType",
      "LIFECYCLESTATUS": "publishedLifecycleStatus",
      "BUILDINGTYPE": "publishedBuildingType",
      "HERITAGE": "publishedHeritageFlag",
      "LASTUPDATE": "publishedRecordUpdateDate"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "BUILDINGID": "esriFieldTypeString",
      "STYPE": "esriFieldTypeString",
      "LIFECYCLESTATUS": "esriFieldTypeString",
      "BUILDINGTYPE": "esriFieldTypeString",
      "HERITAGE": "esriFieldTypeString",
      "LASTUPDATE": "esriFieldTypeDate"
    },
    "note": "A published roofline polygon intersects the screened point. Original imagery/observation vintage and current physical identity are unverified. Published administrative type/lifecycle/heritage flags are not verified present condition or the current heritage register. No geometry, area, floor count, height, width, age, construction date, legal units or condition is returned.",
    "source": {
      "id": "sudbury:buildingFootprintReference",
      "name": "Greater Sudbury — Building Roofline",
      "url": "https://www.arcgis.com/home/item.html?id=d3b94bd7d0a14b4b97b3757d1a383dd4",
      "licence": "City of Greater Sudbury Open Data Licence 1.0",
      "licenceUrl": "https://www.greatersudbury.ca/city-hall/open-government/open-data/licence/",
      "attribution": "Contains information licensed under the Open Data Licence – City of Greater Sudbury. Selected attributes are renamed by Homies / Realist; no City endorsement."
    }
  },
  {
    "key": "community",
    "item": "80a3131be75b481582675297c89d267a",
    "itemUrl": "https://services.arcgis.com/q3mIlR87lZlZsds3/arcgis/rest/services/Land_Use_and_Boundaries_view/FeatureServer",
    "owner": "Greater.Sudbury",
    "rootUrl": "https://services.arcgis.com/q3mIlR87lZlZsds3/arcgis/rest/services/Land_Use_and_Boundaries_view/FeatureServer",
    "url": "https://services.arcgis.com/q3mIlR87lZlZsds3/arcgis/rest/services/Land_Use_and_Boundaries_view/FeatureServer/2",
    "child": 2,
    "title": "Land Use and Boundaries",
    "layerName": "Community",
    "geometry": "esriGeometryPolygon",
    "oid": "OBJECTID",
    "accessInformation": null,
    "rootCopyright": "",
    "copyright": "",
    "rootDescriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "descriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "itemDescriptionHash": "a32648e48aea2f32e3abf4cafd3f6a9c4bdf94fe76b30e541ac44f12bf433ba1",
    "termsHash": "42cd7b82054b42389662e19472a96457fc5dcbefc9fa84d1c2e816b446e813b2",
    "fields": {
      "OBJECTID": "recordId",
      "COMMID": "publishedCommunityId",
      "COMMUNITY": "publishedCommunity",
      "STYPE": "publishedType",
      "CLEVEL": "publishedLevel",
      "LASTUPDATE": "publishedRecordUpdateDate"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "COMMID": "esriFieldTypeString",
      "COMMUNITY": "esriFieldTypeString",
      "STYPE": "esriFieldTypeString",
      "CLEVEL": "esriFieldTypeString",
      "LASTUPDATE": "esriFieldTypeDate"
    },
    "note": "Published City community reference at the point. This does not classify household or neighbourhood quality, identify former permit municipalities or establish current legal boundaries.",
    "source": {
      "id": "sudbury:community",
      "name": "Greater Sudbury — Community",
      "url": "https://www.arcgis.com/home/item.html?id=80a3131be75b481582675297c89d267a",
      "licence": "City of Greater Sudbury Open Data Licence 1.0",
      "licenceUrl": "https://www.greatersudbury.ca/city-hall/open-government/open-data/licence/",
      "attribution": "Contains information licensed under the Open Data Licence – City of Greater Sudbury. Selected attributes are renamed by Homies / Realist; no City endorsement."
    }
  },
  {
    "key": "townshipReference",
    "item": "80a3131be75b481582675297c89d267a",
    "itemUrl": "https://services.arcgis.com/q3mIlR87lZlZsds3/arcgis/rest/services/Land_Use_and_Boundaries_view/FeatureServer",
    "owner": "Greater.Sudbury",
    "rootUrl": "https://services.arcgis.com/q3mIlR87lZlZsds3/arcgis/rest/services/Land_Use_and_Boundaries_view/FeatureServer",
    "url": "https://services.arcgis.com/q3mIlR87lZlZsds3/arcgis/rest/services/Land_Use_and_Boundaries_view/FeatureServer/4",
    "child": 4,
    "title": "Land Use and Boundaries",
    "layerName": "Township",
    "geometry": "esriGeometryPolygon",
    "oid": "OBJECTID",
    "accessInformation": null,
    "rootCopyright": "",
    "copyright": "",
    "rootDescriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "descriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "itemDescriptionHash": "a32648e48aea2f32e3abf4cafd3f6a9c4bdf94fe76b30e541ac44f12bf433ba1",
    "termsHash": "42cd7b82054b42389662e19472a96457fc5dcbefc9fa84d1c2e816b446e813b2",
    "fields": {
      "OBJECTID": "recordId",
      "TOWNSHIP": "publishedTownshipCode"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "TOWNSHIP": "esriFieldTypeSmallInteger"
    },
    "note": "Published numeric township reference at the point. No source code-to-name or former permit-community crosswalk is inferred.",
    "source": {
      "id": "sudbury:townshipReference",
      "name": "Greater Sudbury — Township",
      "url": "https://www.arcgis.com/home/item.html?id=80a3131be75b481582675297c89d267a",
      "licence": "City of Greater Sudbury Open Data Licence 1.0",
      "licenceUrl": "https://www.greatersudbury.ca/city-hall/open-government/open-data/licence/",
      "attribution": "Contains information licensed under the Open Data Licence – City of Greater Sudbury. Selected attributes are renamed by Homies / Realist; no City endorsement."
    }
  },
  {
    "key": "parcelReference",
    "item": "80a3131be75b481582675297c89d267a",
    "itemUrl": "https://services.arcgis.com/q3mIlR87lZlZsds3/arcgis/rest/services/Land_Use_and_Boundaries_view/FeatureServer",
    "owner": "Greater.Sudbury",
    "rootUrl": "https://services.arcgis.com/q3mIlR87lZlZsds3/arcgis/rest/services/Land_Use_and_Boundaries_view/FeatureServer",
    "url": "https://services.arcgis.com/q3mIlR87lZlZsds3/arcgis/rest/services/Land_Use_and_Boundaries_view/FeatureServer/6",
    "child": 6,
    "title": "Land Use and Boundaries",
    "layerName": "Parcels",
    "geometry": "esriGeometryPolygon",
    "oid": "OBJECTID",
    "accessInformation": null,
    "rootCopyright": "",
    "copyright": "",
    "rootDescriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "descriptionHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "itemDescriptionHash": "a32648e48aea2f32e3abf4cafd3f6a9c4bdf94fe76b30e541ac44f12bf433ba1",
    "termsHash": "42cd7b82054b42389662e19472a96457fc5dcbefc9fa84d1c2e816b446e813b2",
    "fields": {
      "OBJECTID": "recordId"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID"
    },
    "note": "City-curated parcel-fabric reference identifier at the point only. No geometry, area, owner, PIN, title, survey, legal boundary or current legal parcel identity is returned.",
    "source": {
      "id": "sudbury:parcelReference",
      "name": "Greater Sudbury — Parcels",
      "url": "https://www.arcgis.com/home/item.html?id=80a3131be75b481582675297c89d267a",
      "licence": "City of Greater Sudbury Open Data Licence 1.0",
      "licenceUrl": "https://www.greatersudbury.ca/city-hall/open-government/open-data/licence/",
      "attribution": "Contains information licensed under the Open Data Licence – City of Greater Sudbury. Selected attributes are renamed by Homies / Realist; no City endorsement."
    }
  }
];
