import type { Source } from "./model";

export interface WaterlooFeed { market:string; publisher:"kitchener"|"waterloo"|"cambridge"|"region"; key:string; group:string; item:string; rootUrl:string; url:string; owner:string; org:string; expectedItemTitle:string; expectedLayerName:string; expectedCopyright:string; termsHash:string; oid:string; geometry:string; fields:Record<string,string>; fieldTypes:Record<string,string>; dates:string[]; matchField?:string; note:string; source:Source; }
export const WATERLOO_GRANTS={
  "cambridge": {
    "url": "https://www.cambridge.ca/mayor-city-council-government/open-data/",
    "selector": "div[id^=\"collapse_\"]",
    "hash": "ce9c5f56b510cd0fb0afb6dafd6aa367d878314959ea85b6fb664eb64b61680f"
  },
  "region": {
    "url": "https://www.regionofwaterloo.ca/government-and-council/transparency-and-accountability/open-data/",
    "selector": "div[id^=\"collapse_\"]",
    "hash": "12f8d7bcd459f69d6ad13ccfcc259b712340b35869e652d8418b611d83b0fbb7"
  }
};
export const WATERLOO_CITY_GRANT={
  "site": "c4904b1bf1a8429ab6240226038def3d",
  "group": "b04b0eafc4ff4d05a66de852c57d153b",
  "page": "8844e3b457d2436cb1029e7470b2be8c",
  "pageOwner": "cdejacob",
  "hash": "6f6ab8d33e415f15e7861df037c994cca00ed6c4cb524600adf8896bb185450e"
};
export const WATERLOO_FEEDS:WaterlooFeed[]=[
  {
    "market": "Kitchener",
    "publisher": "kitchener",
    "key": "municipality",
    "group": "municipality",
    "item": "2840815b1dff4989b8c8513541a00b49",
    "rootUrl": "https://services1.arcgis.com/qAo1OsXi67t7XgmS/arcgis/rest/services/Municipal_Boundary/FeatureServer",
    "url": "https://services1.arcgis.com/qAo1OsXi67t7XgmS/arcgis/rest/services/Municipal_Boundary/FeatureServer/0",
    "owner": "KitchenerGIS",
    "org": "qAo1OsXi67t7XgmS",
    "expectedItemTitle": "Municipal_Boundary",
    "expectedLayerName": "Municipal Boundary",
    "expectedCopyright": "",
    "termsHash": "694e24d6cf639ccbfe64efc673820be7eb0f13950077df97a9210931fea97cc4",
    "oid": "OBJECTID",
    "geometry": "esriGeometryPolygon",
    "fields": {
      "OBJECTID": "recordId",
      "MUNICIPALITY": "publishedMunicipality",
      "CATEGORY": "publishedCategory",
      "SOURCE_DATE": "publishedSourceDate",
      "SOURCE": "publishedSource"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "MUNICIPALITY": "esriFieldTypeString",
      "CATEGORY": "esriFieldTypeString",
      "SOURCE_DATE": "esriFieldTypeDate",
      "SOURCE": "esriFieldTypeString"
    },
    "dates": [
      "SOURCE_DATE"
    ],
    "note": "City boundary point confirmation; not a survey or title record.",
    "source": {
      "id": "waterloo-region:kitchener:municipality",
      "name": "Kitchener Municipal Boundary",
      "url": "https://www.arcgis.com/home/item.html?id=2840815b1dff4989b8c8513541a00b49",
      "licence": "Open Government Licence - The Corporation of the City of Kitchener 1.0",
      "licenceUrl": "https://www.kitchener.ca/council-and-city-administration/data-and-maps/open-data-licence/",
      "attribution": "Contains information licensed under the Open Government Licence - The Corporation of the City of Kitchener."
    }
  },
  {
    "market": "Kitchener",
    "publisher": "kitchener",
    "key": "permits",
    "group": "permits",
    "item": "c486d37abe2948d884a159cba20bec8c",
    "rootUrl": "https://services1.arcgis.com/qAo1OsXi67t7XgmS/arcgis/rest/services/Building_Permits/FeatureServer",
    "url": "https://services1.arcgis.com/qAo1OsXi67t7XgmS/arcgis/rest/services/Building_Permits/FeatureServer/0",
    "owner": "KitchenerGIS",
    "org": "qAo1OsXi67t7XgmS",
    "expectedItemTitle": "Building_Permits",
    "expectedLayerName": "Building Permit",
    "expectedCopyright": "",
    "termsHash": "694e24d6cf639ccbfe64efc673820be7eb0f13950077df97a9210931fea97cc4",
    "oid": "OBJECTID",
    "geometry": "esriGeometryPoint",
    "fields": {
      "OBJECTID": "recordId",
      "PERMITNO": "permitNumber",
      "PERMIT_TYPE": "publishedPermitType",
      "FOLDERNAME": "publishedFolderName",
      "PERMIT_STATUS": "publishedStatus",
      "APPLICATION_DATE": "publishedApplicationDate",
      "ISSUE_DATE": "publishedIssueDate",
      "FINAL_DATE": "publishedFinalDate",
      "EXPIRY_DATE": "publishedExpiryDate",
      "SUB_WORK_TYPE": "publishedSubWorkType",
      "WORK_TYPE": "publishedWorkType",
      "PERMIT_DESCRIPTION": "publishedPermitDescription",
      "CONSTRUCTION_VALUE": "publishedConstructionValue",
      "TOTAL_UNITS": "publishedTotalUnits",
      "UNITS_CREATED": "publishedUnitsCreated",
      "UNITS_LOST": "publishedUnitsLost",
      "UNITS_NET_CHANGE": "publishedUnitsNetChange",
      "SPECIAL_CONDITIONS": "publishedSpecialConditions",
      "EXTRACTION_DATE": "publishedExtractionDate",
      "OCCUPANCY_PERMITTED_DT": "publishedOccupancyPermittedDt",
      "STOREYS_PROPOSED": "publishedStoreysProposed"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "PERMITNO": "esriFieldTypeString",
      "PERMIT_TYPE": "esriFieldTypeString",
      "FOLDERNAME": "esriFieldTypeString",
      "PERMIT_STATUS": "esriFieldTypeString",
      "APPLICATION_DATE": "esriFieldTypeDate",
      "ISSUE_DATE": "esriFieldTypeDate",
      "FINAL_DATE": "esriFieldTypeDate",
      "EXPIRY_DATE": "esriFieldTypeDate",
      "SUB_WORK_TYPE": "esriFieldTypeString",
      "WORK_TYPE": "esriFieldTypeString",
      "PERMIT_DESCRIPTION": "esriFieldTypeString",
      "CONSTRUCTION_VALUE": "esriFieldTypeDouble",
      "TOTAL_UNITS": "esriFieldTypeString",
      "UNITS_CREATED": "esriFieldTypeString",
      "UNITS_LOST": "esriFieldTypeString",
      "UNITS_NET_CHANGE": "esriFieldTypeDouble",
      "SPECIAL_CONDITIONS": "esriFieldTypeString",
      "EXTRACTION_DATE": "esriFieldTypeDate",
      "OCCUPANCY_PERMITTED_DT": "esriFieldTypeDate",
      "STOREYS_PROPOSED": "esriFieldTypeString"
    },
    "dates": [
      "APPLICATION_DATE",
      "ISSUE_DATE",
      "FINAL_DATE",
      "EXPIRY_DATE",
      "EXTRACTION_DATE",
      "OCCUPANCY_PERMITTED_DT"
    ],
    "matchField": "FOLDERNAME",
    "note": "Published permit observations preserve status and dates separately. Construction value is a declared project value, not property value. A published final or occupancy date does not verify current occupancy approval, inspected completion or legal units. Full history is unverified.",
    "source": {
      "id": "waterloo-region:kitchener:permits",
      "name": "Kitchener Building Permit",
      "url": "https://www.arcgis.com/home/item.html?id=c486d37abe2948d884a159cba20bec8c",
      "licence": "Open Government Licence - The Corporation of the City of Kitchener 1.0",
      "licenceUrl": "https://www.kitchener.ca/council-and-city-administration/data-and-maps/open-data-licence/",
      "attribution": "Contains information licensed under the Open Government Licence - The Corporation of the City of Kitchener."
    }
  },
  {
    "market": "Kitchener",
    "publisher": "kitchener",
    "key": "planningApplications",
    "group": "planningApplications",
    "item": "b7e2f8feda7340eaa5f4dd7b9c4d5ac0",
    "rootUrl": "https://services1.arcgis.com/qAo1OsXi67t7XgmS/arcgis/rest/services/Planning_Applications_Active/FeatureServer",
    "url": "https://services1.arcgis.com/qAo1OsXi67t7XgmS/arcgis/rest/services/Planning_Applications_Active/FeatureServer/0",
    "owner": "KitchenerGIS",
    "org": "qAo1OsXi67t7XgmS",
    "expectedItemTitle": "Planning_Applications_Active",
    "expectedLayerName": "Planning Applications Active",
    "expectedCopyright": "",
    "termsHash": "29f23849526c9622da39787906f0c64c1d3f3d8b121a96c0f350f02539e19209",
    "oid": "OBJECTID",
    "geometry": "esriGeometryPoint",
    "fields": {
      "OBJECTID": "recordId",
      "ADDRESS": "publishedAddress",
      "APPLICATION_NO": "publishedApplicationNo",
      "STATUS": "publishedStatus",
      "FOLDERTYPE": "publishedFoldertype",
      "SUBTYPE": "publishedSubtype",
      "DESCRIPTION": "publishedDescription",
      "COMBINED_APPLICATION": "publishedCombinedApplication",
      "INDATE": "publishedIndate",
      "PUBLIC_STATUS_UPDATE": "publishedPublicStatusUpdate",
      "DRAFT_APPROVAL_DATE": "publishedDraftApprovalDate",
      "REGIONAL_APPROVAL_DATE": "publishedRegionalApprovalDate",
      "REMOVAL_DATE": "publishedRemovalDate",
      "FINAL_DATE": "publishedFinalDate",
      "EXISTING_OPA_LANDUSE": "publishedExistingOpaLanduse",
      "PROPOSED_OPA_LANDUSE": "publishedProposedOpaLanduse",
      "EXISTING_ZONING": "publishedExistingZoning",
      "PROPOSED_ZONING": "publishedProposedZoning",
      "EXISTING_LANDUSE": "publishedExistingLanduse",
      "PROPOSED_LANDUSE": "publishedProposedLanduse",
      "PROP_MAX_RES_UNITS_INCIR": "publishedPropMaxResUnitsIncir",
      "PROP_MAX_RES_UNITS_DA": "publishedPropMaxResUnitsDa",
      "PUBLIC_STATUS_DESC": "publishedPublicStatusDesc",
      "AMANDA_STATUS_DESC": "publishedAmandaStatusDesc"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "ADDRESS": "esriFieldTypeString",
      "APPLICATION_NO": "esriFieldTypeString",
      "STATUS": "esriFieldTypeString",
      "FOLDERTYPE": "esriFieldTypeString",
      "SUBTYPE": "esriFieldTypeString",
      "DESCRIPTION": "esriFieldTypeString",
      "COMBINED_APPLICATION": "esriFieldTypeString",
      "INDATE": "esriFieldTypeDate",
      "PUBLIC_STATUS_UPDATE": "esriFieldTypeString",
      "DRAFT_APPROVAL_DATE": "esriFieldTypeString",
      "REGIONAL_APPROVAL_DATE": "esriFieldTypeString",
      "REMOVAL_DATE": "esriFieldTypeString",
      "FINAL_DATE": "esriFieldTypeDate",
      "EXISTING_OPA_LANDUSE": "esriFieldTypeString",
      "PROPOSED_OPA_LANDUSE": "esriFieldTypeString",
      "EXISTING_ZONING": "esriFieldTypeString",
      "PROPOSED_ZONING": "esriFieldTypeString",
      "EXISTING_LANDUSE": "esriFieldTypeString",
      "PROPOSED_LANDUSE": "esriFieldTypeString",
      "PROP_MAX_RES_UNITS_INCIR": "esriFieldTypeString",
      "PROP_MAX_RES_UNITS_DA": "esriFieldTypeString",
      "PUBLIC_STATUS_DESC": "esriFieldTypeString",
      "AMANDA_STATUS_DESC": "esriFieldTypeString"
    },
    "dates": [
      "INDATE",
      "FINAL_DATE"
    ],
    "matchField": "ADDRESS",
    "note": "Active exact civic-address application observations. Published approval/removal strings remain raw text; proposed use/zoning is separate from current legal permission. Multi-address files, nearby proposals, closed history, decisions, conditions and appeals are unsearched.",
    "source": {
      "id": "waterloo-region:kitchener:planningApplications",
      "name": "Kitchener Planning Applications Active",
      "url": "https://www.arcgis.com/home/item.html?id=b7e2f8feda7340eaa5f4dd7b9c4d5ac0",
      "licence": "Open Government Licence - The Corporation of the City of Kitchener 1.0",
      "licenceUrl": "https://www.kitchener.ca/council-and-city-administration/data-and-maps/open-data-licence/",
      "attribution": "Contains information licensed under the Open Government Licence - The Corporation of the City of Kitchener."
    }
  },
  {
    "market": "Kitchener",
    "publisher": "kitchener",
    "key": "heritageProperties",
    "group": "heritage",
    "item": "806af22b0cf94dacaecece52a4f96ada",
    "rootUrl": "https://services1.arcgis.com/qAo1OsXi67t7XgmS/arcgis/rest/services/Heritage_Properties/FeatureServer",
    "url": "https://services1.arcgis.com/qAo1OsXi67t7XgmS/arcgis/rest/services/Heritage_Properties/FeatureServer/0",
    "owner": "KitchenerGIS",
    "org": "qAo1OsXi67t7XgmS",
    "expectedItemTitle": "Heritage_Properties",
    "expectedLayerName": "Heritage Properties",
    "expectedCopyright": "",
    "termsHash": "694e24d6cf639ccbfe64efc673820be7eb0f13950077df97a9210931fea97cc4",
    "oid": "OBJECTID",
    "geometry": "esriGeometryPoint",
    "fields": {
      "OBJECTID": "recordId",
      "ADDRESSES": "publishedAddresses",
      "HERITAGE_ADDRESS": "publishedHeritageAddress",
      "COMMON_NAME": "publishedCommonName",
      "HERITAGE_ATTRIBUTES": "publishedHeritageAttributes",
      "DISTRICT_SIGNIFICANCE": "publishedDistrictSignificance",
      "YEAR_BUILT": "publishedYearBuilt",
      "YEAR_BUILT_QUALIFIER": "publishedYearBuiltQualifier",
      "LEGAL_AGREEMENT": "publishedLegalAgreement",
      "HERITAGE_DISTRICT": "publishedHeritageDistrict",
      "CATEGORY": "publishedCategory",
      "STATUS": "publishedStatus",
      "STATUS_DATE": "publishedStatusDate",
      "SOURCE_DATE": "publishedSourceDate",
      "DATE_LISTED": "publishedDateListed",
      "DATE_DESIGNATED": "publishedDateDesignated",
      "BYLAW_NO": "publishedBylawNo",
      "REPORT_NO": "publishedReportNo"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "ADDRESSES": "esriFieldTypeString",
      "HERITAGE_ADDRESS": "esriFieldTypeString",
      "COMMON_NAME": "esriFieldTypeString",
      "HERITAGE_ATTRIBUTES": "esriFieldTypeString",
      "DISTRICT_SIGNIFICANCE": "esriFieldTypeString",
      "YEAR_BUILT": "esriFieldTypeInteger",
      "YEAR_BUILT_QUALIFIER": "esriFieldTypeString",
      "LEGAL_AGREEMENT": "esriFieldTypeString",
      "HERITAGE_DISTRICT": "esriFieldTypeString",
      "CATEGORY": "esriFieldTypeString",
      "STATUS": "esriFieldTypeString",
      "STATUS_DATE": "esriFieldTypeDate",
      "SOURCE_DATE": "esriFieldTypeDate",
      "DATE_LISTED": "esriFieldTypeDate",
      "DATE_DESIGNATED": "esriFieldTypeDate",
      "BYLAW_NO": "esriFieldTypeString",
      "REPORT_NO": "esriFieldTypeString"
    },
    "dates": [
      "STATUS_DATE",
      "SOURCE_DATE",
      "DATE_LISTED",
      "DATE_DESIGNATED"
    ],
    "matchField": "HERITAGE_ADDRESS",
    "note": "Exact published heritage civic-address evidence. Preserve raw category/status, construction-year qualifier and instruments; current register, designation and alteration permissions remain unverified.",
    "source": {
      "id": "waterloo-region:kitchener:heritageProperties",
      "name": "Kitchener Heritage Properties",
      "url": "https://www.arcgis.com/home/item.html?id=806af22b0cf94dacaecece52a4f96ada",
      "licence": "Open Government Licence - The Corporation of the City of Kitchener 1.0",
      "licenceUrl": "https://www.kitchener.ca/council-and-city-administration/data-and-maps/open-data-licence/",
      "attribution": "Contains information licensed under the Open Government Licence - The Corporation of the City of Kitchener."
    }
  },
  {
    "market": "Kitchener",
    "publisher": "kitchener",
    "key": "heritageDistrict",
    "group": "heritageDistrict",
    "item": "3ed6bb7c8460499e9b32ac4fee29cf2b",
    "rootUrl": "https://services1.arcgis.com/qAo1OsXi67t7XgmS/arcgis/rest/services/Heritage_District/FeatureServer",
    "url": "https://services1.arcgis.com/qAo1OsXi67t7XgmS/arcgis/rest/services/Heritage_District/FeatureServer/0",
    "owner": "KitchenerGIS",
    "org": "qAo1OsXi67t7XgmS",
    "expectedItemTitle": "Heritage_District",
    "expectedLayerName": "Heritage District",
    "expectedCopyright": "City of Kitchener, please see: http://app.kitchener.ca/opendata/",
    "termsHash": "694e24d6cf639ccbfe64efc673820be7eb0f13950077df97a9210931fea97cc4",
    "oid": "OBJECTID",
    "geometry": "esriGeometryPolygon",
    "fields": {
      "OBJECTID": "recordId",
      "HERITAGE_DISTRICT": "publishedHeritageDistrict",
      "SOURCE_DATE": "publishedSourceDate",
      "SOURCE": "publishedSource",
      "STATUS": "publishedStatus",
      "STATUS_DATE": "publishedStatusDate",
      "HERITAGEDISTRICTID": "publishedHeritagedistrictid"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "HERITAGE_DISTRICT": "esriFieldTypeString",
      "SOURCE_DATE": "esriFieldTypeDate",
      "SOURCE": "esriFieldTypeString",
      "STATUS": "esriFieldTypeString",
      "STATUS_DATE": "esriFieldTypeDate",
      "HERITAGEDISTRICTID": "esriFieldTypeString"
    },
    "dates": [
      "SOURCE_DATE",
      "STATUS_DATE"
    ],
    "note": "Published heritage-district polygon intersects the subject point; current legal boundary, status and permissions remain unverified.",
    "source": {
      "id": "waterloo-region:kitchener:heritageDistrict",
      "name": "Kitchener Heritage District",
      "url": "https://www.arcgis.com/home/item.html?id=3ed6bb7c8460499e9b32ac4fee29cf2b",
      "licence": "Open Government Licence - The Corporation of the City of Kitchener 1.0",
      "licenceUrl": "https://www.kitchener.ca/council-and-city-administration/data-and-maps/open-data-licence/",
      "attribution": "Contains information licensed under the Open Government Licence - The Corporation of the City of Kitchener."
    }
  },
  {
    "market": "Kitchener",
    "publisher": "kitchener",
    "key": "communityImprovement",
    "group": "communityImprovement",
    "item": "df19f8da52a842d18c2d700e7e213e76",
    "rootUrl": "https://services1.arcgis.com/qAo1OsXi67t7XgmS/arcgis/rest/services/Community_Improvement_Plans/FeatureServer",
    "url": "https://services1.arcgis.com/qAo1OsXi67t7XgmS/arcgis/rest/services/Community_Improvement_Plans/FeatureServer/0",
    "owner": "KitchenerGIS",
    "org": "qAo1OsXi67t7XgmS",
    "expectedItemTitle": "Community_Improvement_Plans",
    "expectedLayerName": "Community Improvement Plans",
    "expectedCopyright": "City of Kitchener",
    "termsHash": "694e24d6cf639ccbfe64efc673820be7eb0f13950077df97a9210931fea97cc4",
    "oid": "OBJECTID",
    "geometry": "esriGeometryPolygon",
    "fields": {
      "OBJECTID": "recordId",
      "COMMUNITYIMPROVEMENTPLANID": "publishedCommunityimprovementplanid",
      "BYLAW_NO": "publishedBylawNo",
      "BYLAW_DATE": "publishedBylawDate",
      "CATEGORY": "publishedCategory",
      "SUBCATEGORY": "publishedSubcategory",
      "NOTES": "publishedNotes",
      "STATUS": "publishedStatus",
      "STATUS_DATE": "publishedStatusDate",
      "SOURCE_DATE": "publishedSourceDate"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "COMMUNITYIMPROVEMENTPLANID": "esriFieldTypeInteger",
      "BYLAW_NO": "esriFieldTypeString",
      "BYLAW_DATE": "esriFieldTypeDate",
      "CATEGORY": "esriFieldTypeString",
      "SUBCATEGORY": "esriFieldTypeString",
      "NOTES": "esriFieldTypeString",
      "STATUS": "esriFieldTypeString",
      "STATUS_DATE": "esriFieldTypeDate",
      "SOURCE_DATE": "esriFieldTypeDate"
    },
    "dates": [
      "BYLAW_DATE",
      "STATUS_DATE",
      "SOURCE_DATE"
    ],
    "note": "Community-improvement reference polygon only. This does not establish current program eligibility, available funding or an approved grant.",
    "source": {
      "id": "waterloo-region:kitchener:communityImprovement",
      "name": "Kitchener Community Improvement Plans",
      "url": "https://www.arcgis.com/home/item.html?id=df19f8da52a842d18c2d700e7e213e76",
      "licence": "Open Government Licence - The Corporation of the City of Kitchener 1.0",
      "licenceUrl": "https://www.kitchener.ca/council-and-city-administration/data-and-maps/open-data-licence/",
      "attribution": "Contains information licensed under the Open Government Licence - The Corporation of the City of Kitchener."
    }
  },
  {
    "market": "Kitchener",
    "publisher": "kitchener",
    "key": "subwatershed",
    "group": "subwatershed",
    "item": "841ffb37eadb4fb2b3cba32f21477f4a",
    "rootUrl": "https://services1.arcgis.com/qAo1OsXi67t7XgmS/arcgis/rest/services/Storm_Subwatersheds/FeatureServer",
    "url": "https://services1.arcgis.com/qAo1OsXi67t7XgmS/arcgis/rest/services/Storm_Subwatersheds/FeatureServer/0",
    "owner": "KitchenerGIS",
    "org": "qAo1OsXi67t7XgmS",
    "expectedItemTitle": "Storm_Subwatersheds",
    "expectedLayerName": "Stm Subwatersheds",
    "expectedCopyright": "",
    "termsHash": "694e24d6cf639ccbfe64efc673820be7eb0f13950077df97a9210931fea97cc4",
    "oid": "OBJECTID",
    "geometry": "esriGeometryPolygon",
    "fields": {
      "OBJECTID": "recordId",
      "SUBWATERSHEDID": "publishedSubwatershedid",
      "CATEGORY": "publishedCategory",
      "SUBCATEGORY": "publishedSubcategory",
      "SWM_RANK": "publishedSwmRank",
      "WATERQUALITY_RANK": "publishedWaterqualityRank",
      "STREAMHEALTH_RANK": "publishedStreamhealthRank",
      "AQUATIC_RANK": "publishedAquaticRank",
      "TERRESTRIAL_RANK": "publishedTerrestrialRank",
      "OVERALL_RANK": "publishedOverallRank",
      "COMPLETED_SW_PLAN": "publishedCompletedSwPlan",
      "SOURCE_DATE": "publishedSourceDate",
      "STATUS_DATE": "publishedStatusDate"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "SUBWATERSHEDID": "esriFieldTypeInteger",
      "CATEGORY": "esriFieldTypeString",
      "SUBCATEGORY": "esriFieldTypeString",
      "SWM_RANK": "esriFieldTypeString",
      "WATERQUALITY_RANK": "esriFieldTypeString",
      "STREAMHEALTH_RANK": "esriFieldTypeString",
      "AQUATIC_RANK": "esriFieldTypeString",
      "TERRESTRIAL_RANK": "esriFieldTypeString",
      "OVERALL_RANK": "esriFieldTypeString",
      "COMPLETED_SW_PLAN": "esriFieldTypeString",
      "SOURCE_DATE": "esriFieldTypeDate",
      "STATUS_DATE": "esriFieldTypeDate"
    },
    "dates": [
      "SOURCE_DATE",
      "STATUS_DATE"
    ],
    "note": "Subwatershed study reference and raw source ranks only. Ranks are not a property risk score, current water quality, flood safety or conservation-authority clearance.",
    "source": {
      "id": "waterloo-region:kitchener:subwatershed",
      "name": "Kitchener Stm Subwatersheds",
      "url": "https://www.arcgis.com/home/item.html?id=841ffb37eadb4fb2b3cba32f21477f4a",
      "licence": "Open Government Licence - The Corporation of the City of Kitchener 1.0",
      "licenceUrl": "https://www.kitchener.ca/council-and-city-administration/data-and-maps/open-data-licence/",
      "attribution": "Contains information licensed under the Open Government Licence - The Corporation of the City of Kitchener."
    }
  },
  {
    "market": "Waterloo",
    "publisher": "waterloo",
    "key": "addresses",
    "group": "addresses",
    "item": "fb1ce9625c634b2dbe1d2be36d419711",
    "rootUrl": "https://services.arcgis.com/ZpeBVw5o1kjit7LT/arcgis/rest/services/Addresses/FeatureServer",
    "url": "https://services.arcgis.com/ZpeBVw5o1kjit7LT/arcgis/rest/services/Addresses/FeatureServer/0",
    "owner": "OpenData_Waterloo",
    "org": "ZpeBVw5o1kjit7LT",
    "expectedItemTitle": "Addresses",
    "expectedLayerName": "City_of_Waterloo_Address_Points",
    "expectedCopyright": "",
    "termsHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "oid": "OBJECTID_1",
    "geometry": "esriGeometryPoint",
    "fields": {
      "OBJECTID_1": "recordId",
      "ADDRESS_ID": "publishedAddressId",
      "CIVIC_ADDR": "publishedCivicAddr",
      "STREET_NM": "publishedStreetNm",
      "WARD": "publishedWard"
    },
    "fieldTypes": {
      "OBJECTID_1": "esriFieldTypeOID",
      "ADDRESS_ID": "esriFieldTypeString",
      "CIVIC_ADDR": "esriFieldTypeString",
      "STREET_NM": "esriFieldTypeString",
      "WARD": "esriFieldTypeInteger"
    },
    "dates": [],
    "note": "Municipal civic identity and location only; the feed has no unit, building-centroid or lifecycle field.",
    "source": {
      "id": "waterloo-region:waterloo:addresses",
      "name": "Waterloo City_of_Waterloo_Address_Points",
      "url": "https://www.arcgis.com/home/item.html?id=fb1ce9625c634b2dbe1d2be36d419711",
      "licence": "City of Waterloo Open Data User Licence",
      "licenceUrl": "https://data.waterloo.ca/pages/open-data-licence",
      "attribution": "Contains information provided by the City of Waterloo under licence"
    }
  },
  {
    "market": "Waterloo",
    "publisher": "waterloo",
    "key": "municipality",
    "group": "municipality",
    "item": "eda133697fd446db92dec930f162a700",
    "rootUrl": "https://services.arcgis.com/ZpeBVw5o1kjit7LT/arcgis/rest/services/CityBoundary/FeatureServer",
    "url": "https://services.arcgis.com/ZpeBVw5o1kjit7LT/arcgis/rest/services/CityBoundary/FeatureServer/0",
    "owner": "OpenData_Waterloo",
    "org": "ZpeBVw5o1kjit7LT",
    "expectedItemTitle": "Municipal Boundary",
    "expectedLayerName": "City Boundary",
    "expectedCopyright": "",
    "termsHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "oid": "OBJECTID",
    "geometry": "esriGeometryPolygon",
    "fields": {
      "OBJECTID": "recordId",
      "AREA_M": "publishedAreaM"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "AREA_M": "esriFieldTypeDouble"
    },
    "dates": [],
    "note": "City-owned City Boundary polygon confirms Waterloo at the point. The source has no municipality-name field; the City identity comes from the bound publisher/service, not a row label.",
    "source": {
      "id": "waterloo-region:waterloo:municipality",
      "name": "Waterloo City Boundary",
      "url": "https://www.arcgis.com/home/item.html?id=eda133697fd446db92dec930f162a700",
      "licence": "City of Waterloo Open Data User Licence",
      "licenceUrl": "https://data.waterloo.ca/pages/open-data-licence",
      "attribution": "Contains information provided by the City of Waterloo under licence"
    }
  },
  {
    "market": "Waterloo",
    "publisher": "waterloo",
    "key": "permits",
    "group": "permits",
    "item": "9319ff78ff074327acb9e2e084e30b2c",
    "rootUrl": "https://services.arcgis.com/ZpeBVw5o1kjit7LT/arcgis/rest/services/City_of_Waterloo_Building_Permits/FeatureServer",
    "url": "https://services.arcgis.com/ZpeBVw5o1kjit7LT/arcgis/rest/services/City_of_Waterloo_Building_Permits/FeatureServer/0",
    "owner": "OpenData_Waterloo",
    "org": "ZpeBVw5o1kjit7LT",
    "expectedItemTitle": "City of Waterloo Building Permits",
    "expectedLayerName": "BUILDING_PERMITS_wgs84",
    "expectedCopyright": "",
    "termsHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "oid": "OBJECTID",
    "geometry": "esriGeometryPoint",
    "fields": {
      "OBJECTID": "recordId",
      "PERMIT_ID": "publishedPermitId",
      "PERMIT_NUM": "permitNumber",
      "ADDRESS_ID": "publishedAddressId",
      "ADDRESS": "publishedAddress",
      "ISSUE_YEAR": "publishedIssueYear",
      "STATUS": "publishedStatus",
      "PERMITTYPE": "publishedPermittype",
      "PERMITDESC": "publishedPermitdesc",
      "SUBDESC": "publishedSubdesc",
      "WORKDESC": "publishedWorkdesc",
      "DESCRIPTN": "publishedDescriptn",
      "ISSUEDATE": "publishedIssuedate",
      "LOCATION": "publishedLocation",
      "CONTRVALUE": "publishedContrvalue",
      "UNITS": "publishedUnits",
      "BEDROOMS": "publishedBedrooms",
      "PROPAREA": "publishedProparea"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "PERMIT_ID": "esriFieldTypeInteger",
      "PERMIT_NUM": "esriFieldTypeString",
      "ADDRESS_ID": "esriFieldTypeString",
      "ADDRESS": "esriFieldTypeString",
      "ISSUE_YEAR": "esriFieldTypeString",
      "STATUS": "esriFieldTypeString",
      "PERMITTYPE": "esriFieldTypeString",
      "PERMITDESC": "esriFieldTypeString",
      "SUBDESC": "esriFieldTypeString",
      "WORKDESC": "esriFieldTypeString",
      "DESCRIPTN": "esriFieldTypeString",
      "ISSUEDATE": "esriFieldTypeDate",
      "LOCATION": "esriFieldTypeString",
      "CONTRVALUE": "esriFieldTypeDouble",
      "UNITS": "esriFieldTypeInteger",
      "BEDROOMS": "esriFieldTypeInteger",
      "PROPAREA": "esriFieldTypeDouble"
    },
    "dates": [
      "ISSUEDATE"
    ],
    "matchField": "ADDRESS",
    "note": "Published issued/complete/occupancy-final permit observations matched to an exact civic address. Raw status and issue date do not establish inspected completion, current occupancy approval, legal units or a complete history. Construction value is not property value.",
    "source": {
      "id": "waterloo-region:waterloo:permits",
      "name": "Waterloo BUILDING_PERMITS_wgs84",
      "url": "https://www.arcgis.com/home/item.html?id=9319ff78ff074327acb9e2e084e30b2c",
      "licence": "City of Waterloo Open Data User Licence",
      "licenceUrl": "https://data.waterloo.ca/pages/open-data-licence",
      "attribution": "Contains information provided by the City of Waterloo under licence"
    }
  },
  {
    "market": "Waterloo",
    "publisher": "waterloo",
    "key": "heritageBuildings",
    "group": "heritage",
    "item": "3822d7856d034f07a14e67e25c6ced4b",
    "rootUrl": "https://services.arcgis.com/ZpeBVw5o1kjit7LT/arcgis/rest/services/HeritageBuildings/FeatureServer",
    "url": "https://services.arcgis.com/ZpeBVw5o1kjit7LT/arcgis/rest/services/HeritageBuildings/FeatureServer/1",
    "owner": "OpenData_Waterloo",
    "org": "ZpeBVw5o1kjit7LT",
    "expectedItemTitle": "Heritage Buildings",
    "expectedLayerName": "Heritage Buildings",
    "expectedCopyright": "",
    "termsHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "oid": "OBJECTID",
    "geometry": "esriGeometryPolygon",
    "fields": {
      "OBJECTID": "recordId",
      "ID": "publishedId",
      "STATUS": "publishedStatus",
      "ACT": "publishedAct",
      "NAME": "publishedName",
      "ADDRESS": "publishedAddress",
      "CONST_DATE": "publishedConstDate",
      "SOURCE": "publishedSource",
      "ARCH_STYLE": "publishedArchStyle",
      "DESCRIPTION": "publishedDescription",
      "IN_DISTRCT": "publishedInDistrct",
      "BYLAW": "publishedBylaw",
      "RPT_NO": "publishedRptNo"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "ID": "esriFieldTypeString",
      "STATUS": "esriFieldTypeString",
      "ACT": "esriFieldTypeString",
      "NAME": "esriFieldTypeString",
      "ADDRESS": "esriFieldTypeString",
      "CONST_DATE": "esriFieldTypeString",
      "SOURCE": "esriFieldTypeString",
      "ARCH_STYLE": "esriFieldTypeString",
      "DESCRIPTION": "esriFieldTypeString",
      "IN_DISTRCT": "esriFieldTypeString",
      "BYLAW": "esriFieldTypeString",
      "RPT_NO": "esriFieldTypeString"
    },
    "dates": [],
    "note": "Published heritage-building polygon inventory includes raw designated/listed/de-listed status. Construction date remains source text. Current register, designation and alteration permissions remain unverified.",
    "source": {
      "id": "waterloo-region:waterloo:heritageBuildings",
      "name": "Waterloo Heritage Buildings",
      "url": "https://www.arcgis.com/home/item.html?id=3822d7856d034f07a14e67e25c6ced4b",
      "licence": "City of Waterloo Open Data User Licence",
      "licenceUrl": "https://data.waterloo.ca/pages/open-data-licence",
      "attribution": "Contains information provided by the City of Waterloo under licence"
    }
  },
  {
    "market": "Waterloo",
    "publisher": "waterloo",
    "key": "culturalHeritageLandscapes",
    "group": "heritage",
    "item": "8a346f548ec04e58922e9352c7ae10a3",
    "rootUrl": "https://services.arcgis.com/ZpeBVw5o1kjit7LT/arcgis/rest/services/CulturalHeritageLandscapes/FeatureServer",
    "url": "https://services.arcgis.com/ZpeBVw5o1kjit7LT/arcgis/rest/services/CulturalHeritageLandscapes/FeatureServer/0",
    "owner": "OpenData_Waterloo",
    "org": "ZpeBVw5o1kjit7LT",
    "expectedItemTitle": "Cultural Heritage Landscapes",
    "expectedLayerName": "Cultural Heritage Landscapes",
    "expectedCopyright": "",
    "termsHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "oid": "OBJECTID",
    "geometry": "esriGeometryPolygon",
    "fields": {
      "OBJECTID": "recordId",
      "CHL_CODE": "publishedChlCode",
      "CHL_NAME": "publishedChlName",
      "CHL_THEME": "publishedChlTheme",
      "CHL_DESC": "publishedChlDesc",
      "AREA_M": "publishedAreaM"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "CHL_CODE": "esriFieldTypeString",
      "CHL_NAME": "esriFieldTypeString",
      "CHL_THEME": "esriFieldTypeString",
      "CHL_DESC": "esriFieldTypeString",
      "AREA_M": "esriFieldTypeDouble"
    },
    "dates": [],
    "note": "Published cultural-heritage landscape inventory polygons are reference evidence; they do not establish designation or alteration permission.",
    "source": {
      "id": "waterloo-region:waterloo:culturalHeritageLandscapes",
      "name": "Waterloo Cultural Heritage Landscapes",
      "url": "https://www.arcgis.com/home/item.html?id=8a346f548ec04e58922e9352c7ae10a3",
      "licence": "City of Waterloo Open Data User Licence",
      "licenceUrl": "https://data.waterloo.ca/pages/open-data-licence",
      "attribution": "Contains information provided by the City of Waterloo under licence"
    }
  },
  {
    "market": "Waterloo",
    "publisher": "waterloo",
    "key": "districtPlans",
    "group": "officialPlan",
    "item": "2fb4cc862830455eb02a8fdd2f03d2b8",
    "rootUrl": "https://services.arcgis.com/ZpeBVw5o1kjit7LT/arcgis/rest/services/DistrictPlans/FeatureServer",
    "url": "https://services.arcgis.com/ZpeBVw5o1kjit7LT/arcgis/rest/services/DistrictPlans/FeatureServer/0",
    "owner": "OpenData_Waterloo",
    "org": "ZpeBVw5o1kjit7LT",
    "expectedItemTitle": "City of Waterloo District Plans",
    "expectedLayerName": "District Plans",
    "expectedCopyright": "",
    "termsHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "oid": "OBJECTID",
    "geometry": "esriGeometryPolygon",
    "fields": {
      "OBJECTID": "recordId",
      "PLANNINGDI": "publishedPlanningdi",
      "DISTNAME": "publishedDistname",
      "CENDISTNAM": "publishedCendistnam",
      "LABEL": "publishedLabel",
      "PROFILE": "publishedProfile",
      "HECTARES": "publishedHectares"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "PLANNINGDI": "esriFieldTypeString",
      "DISTNAME": "esriFieldTypeString",
      "CENDISTNAM": "esriFieldTypeString",
      "LABEL": "esriFieldTypeString",
      "PROFILE": "esriFieldTypeString",
      "HECTARES": "esriFieldTypeDouble"
    },
    "dates": [],
    "note": "District planning reference polygons; current in-force policy, legal schedules, amendments and permissions remain unverified.",
    "source": {
      "id": "waterloo-region:waterloo:districtPlans",
      "name": "Waterloo District Plans",
      "url": "https://www.arcgis.com/home/item.html?id=2fb4cc862830455eb02a8fdd2f03d2b8",
      "licence": "City of Waterloo Open Data User Licence",
      "licenceUrl": "https://data.waterloo.ca/pages/open-data-licence",
      "attribution": "Contains information provided by the City of Waterloo under licence"
    }
  },
  {
    "market": "Waterloo",
    "publisher": "waterloo",
    "key": "waterPressureZone",
    "group": "waterPressureZone",
    "item": "d6af001d3d634f949a35a3c7eaba0c52",
    "rootUrl": "https://services.arcgis.com/ZpeBVw5o1kjit7LT/arcgis/rest/services/Water_PressureZones/FeatureServer",
    "url": "https://services.arcgis.com/ZpeBVw5o1kjit7LT/arcgis/rest/services/Water_PressureZones/FeatureServer/0",
    "owner": "OpenData_Waterloo",
    "org": "ZpeBVw5o1kjit7LT",
    "expectedItemTitle": "Water_PressureZones",
    "expectedLayerName": "WaterPressureZones_wgs84",
    "expectedCopyright": "",
    "termsHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "oid": "OBJECTID_1",
    "geometry": "esriGeometryPolygon",
    "fields": {
      "OBJECTID_1": "recordId",
      "MUNICIPALITY": "publishedMunicipality",
      "MODEL": "publishedModel",
      "HGL": "publishedHgl",
      "ZONE": "publishedZone",
      "ZONELABEL": "publishedZonelabel",
      "FUTUREHGL": "publishedFuturehgl",
      "FUTUREZONE": "publishedFuturezone",
      "FUTUREZONELABEL": "publishedFuturezonelabel"
    },
    "fieldTypes": {
      "OBJECTID_1": "esriFieldTypeOID",
      "MUNICIPALITY": "esriFieldTypeString",
      "MODEL": "esriFieldTypeString",
      "HGL": "esriFieldTypeDouble",
      "ZONE": "esriFieldTypeString",
      "ZONELABEL": "esriFieldTypeString",
      "FUTUREHGL": "esriFieldTypeDouble",
      "FUTUREZONE": "esriFieldTypeString",
      "FUTUREZONELABEL": "esriFieldTypeString"
    },
    "dates": [],
    "note": "Model pressure-zone reference polygon. Published HGL units/datum and model vintage are unverified. Future-zone fields stay separate. This does not measure pressure, establish a property connection, available water capacity, servicing eligibility or drinking-water safety.",
    "source": {
      "id": "waterloo-region:waterloo:waterPressureZone",
      "name": "Waterloo WaterPressureZones_wgs84",
      "url": "https://www.arcgis.com/home/item.html?id=d6af001d3d634f949a35a3c7eaba0c52",
      "licence": "City of Waterloo Open Data User Licence",
      "licenceUrl": "https://data.waterloo.ca/pages/open-data-licence",
      "attribution": "Contains information provided by the City of Waterloo under licence"
    }
  },
  {
    "market": "Cambridge",
    "publisher": "cambridge",
    "key": "addresses",
    "group": "addresses",
    "item": "c5ff664dd011426d96b7d782ce4e4b71",
    "rootUrl": "https://services5.arcgis.com/LTaPSxJTf948f8sm/arcgis/rest/services/AddressPoints/FeatureServer",
    "url": "https://services5.arcgis.com/LTaPSxJTf948f8sm/arcgis/rest/services/AddressPoints/FeatureServer/0",
    "owner": "fme_connection",
    "org": "LTaPSxJTf948f8sm",
    "expectedItemTitle": "Address Points",
    "expectedLayerName": "Address Points",
    "expectedCopyright": "",
    "termsHash": "4d400f02340379a5088c0c09e03650c3fc0017858a10b20be3d9f49779a13c5e",
    "oid": "OBJECTID0",
    "geometry": "esriGeometryPoint",
    "fields": {
      "OBJECTID0": "recordId",
      "ADDRESS_POINT_ID": "publishedAddressPointId",
      "WARD_ID": "publishedWardId",
      "HOUSE_NUMBER": "publishedHouseNumber",
      "UNIT_NUMBER": "publishedUnitNumber",
      "STREET_NAME": "publishedStreetName",
      "STATUS": "publishedStatus",
      "ADDRESS_LABEL": "publishedAddressLabel"
    },
    "fieldTypes": {
      "OBJECTID0": "esriFieldTypeOID",
      "ADDRESS_POINT_ID": "esriFieldTypeInteger",
      "WARD_ID": "esriFieldTypeInteger",
      "HOUSE_NUMBER": "esriFieldTypeInteger",
      "UNIT_NUMBER": "esriFieldTypeString",
      "STREET_NAME": "esriFieldTypeString",
      "STATUS": "esriFieldTypeString",
      "ADDRESS_LABEL": "esriFieldTypeString"
    },
    "dates": [],
    "note": "Municipal civic identity and location. Preserve the raw address status; neither unit existence/legality nor a building centroid is established.",
    "source": {
      "id": "waterloo-region:cambridge:addresses",
      "name": "Cambridge Address Points",
      "url": "https://www.arcgis.com/home/item.html?id=c5ff664dd011426d96b7d782ce4e4b71",
      "licence": "Open Government Licence – City of Cambridge 2.1",
      "licenceUrl": "https://www.cambridge.ca/mayor-city-council-government/open-data/",
      "attribution": "Contains information licensed under the Open Government Licence – City of Cambridge."
    }
  },
  {
    "market": "Cambridge",
    "publisher": "cambridge",
    "key": "municipality",
    "group": "municipality",
    "item": "277bacb2bd23422fa695651d6ca733ad",
    "rootUrl": "https://services5.arcgis.com/LTaPSxJTf948f8sm/arcgis/rest/services/MunicipalBoundary/FeatureServer",
    "url": "https://services5.arcgis.com/LTaPSxJTf948f8sm/arcgis/rest/services/MunicipalBoundary/FeatureServer/0",
    "owner": "fme_connection",
    "org": "LTaPSxJTf948f8sm",
    "expectedItemTitle": "Municipal Boundary",
    "expectedLayerName": "Municipal Boundary",
    "expectedCopyright": "",
    "termsHash": "4d400f02340379a5088c0c09e03650c3fc0017858a10b20be3d9f49779a13c5e",
    "oid": "OBJECTID",
    "geometry": "esriGeometryPolygon",
    "fields": {
      "OBJECTID": "recordId",
      "MUN_BOUNDARY_ID": "publishedMunBoundaryId",
      "LTIER": "publishedMunicipality",
      "UTIER": "publishedRegion"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "MUN_BOUNDARY_ID": "esriFieldTypeInteger",
      "LTIER": "esriFieldTypeString",
      "UTIER": "esriFieldTypeString"
    },
    "dates": [],
    "note": "Municipal boundary point confirmation; not a surveyed parcel or title record.",
    "source": {
      "id": "waterloo-region:cambridge:municipality",
      "name": "Cambridge Municipal Boundary",
      "url": "https://www.arcgis.com/home/item.html?id=277bacb2bd23422fa695651d6ca733ad",
      "licence": "Open Government Licence – City of Cambridge 2.1",
      "licenceUrl": "https://www.cambridge.ca/mayor-city-council-government/open-data/",
      "attribution": "Contains information licensed under the Open Government Licence – City of Cambridge."
    }
  },
  {
    "market": "Cambridge",
    "publisher": "cambridge",
    "key": "heritageParcels",
    "group": "heritage",
    "item": "6c3806c443a1418cbdbc7ec24123417b",
    "rootUrl": "https://services5.arcgis.com/LTaPSxJTf948f8sm/arcgis/rest/services/HeritageParcels/FeatureServer",
    "url": "https://services5.arcgis.com/LTaPSxJTf948f8sm/arcgis/rest/services/HeritageParcels/FeatureServer/0",
    "owner": "fme_connection",
    "org": "LTaPSxJTf948f8sm",
    "expectedItemTitle": "Heritage Parcels",
    "expectedLayerName": "Heritage Parcels",
    "expectedCopyright": "",
    "termsHash": "4d400f02340379a5088c0c09e03650c3fc0017858a10b20be3d9f49779a13c5e",
    "oid": "OBJECTID0",
    "geometry": "esriGeometryPolygon",
    "fields": {
      "OBJECTID0": "recordId",
      "HOUSE_NUMBER": "publishedHouseNumber",
      "STREET_NAME": "publishedStreetName",
      "HERITAGE_DESIGNATION": "publishedHeritageDesignation",
      "TYPE": "publishedType",
      "BYLAW_PART_IV": "publishedBylawPartIv",
      "BYLAW_PART_V": "publishedBylawPartV",
      "DESCRIPTION": "publishedDescription",
      "HERITAGE_DISTRICT": "publishedHeritageDistrict"
    },
    "fieldTypes": {
      "OBJECTID0": "esriFieldTypeOID",
      "HOUSE_NUMBER": "esriFieldTypeString",
      "STREET_NAME": "esriFieldTypeString",
      "HERITAGE_DESIGNATION": "esriFieldTypeString",
      "TYPE": "esriFieldTypeString",
      "BYLAW_PART_IV": "esriFieldTypeString",
      "BYLAW_PART_V": "esriFieldTypeString",
      "DESCRIPTION": "esriFieldTypeString",
      "HERITAGE_DISTRICT": "esriFieldTypeString"
    },
    "dates": [],
    "note": "Published heritage-parcel polygon intersects the subject point; raw Part IV/Part V fields remain separate. Current register, district boundaries and alteration permissions are unverified.",
    "source": {
      "id": "waterloo-region:cambridge:heritageParcels",
      "name": "Cambridge Heritage Parcels",
      "url": "https://www.arcgis.com/home/item.html?id=6c3806c443a1418cbdbc7ec24123417b",
      "licence": "Open Government Licence – City of Cambridge 2.1",
      "licenceUrl": "https://www.cambridge.ca/mayor-city-council-government/open-data/",
      "attribution": "Contains information licensed under the Open Government Licence – City of Cambridge."
    }
  },
  {
    "market": "Cambridge",
    "publisher": "cambridge",
    "key": "landUse2012",
    "group": "officialPlan",
    "item": "4a9eb041957f4326968ac1891a6fbe96",
    "rootUrl": "https://services5.arcgis.com/LTaPSxJTf948f8sm/arcgis/rest/services/Landuse_2012/FeatureServer",
    "url": "https://services5.arcgis.com/LTaPSxJTf948f8sm/arcgis/rest/services/Landuse_2012/FeatureServer/0",
    "owner": "fme_connection",
    "org": "LTaPSxJTf948f8sm",
    "expectedItemTitle": "Land Use (2012 Official Plan)",
    "expectedLayerName": "Land Use (2012 Official Plan)",
    "expectedCopyright": "",
    "termsHash": "4d400f02340379a5088c0c09e03650c3fc0017858a10b20be3d9f49779a13c5e",
    "oid": "OBJECTID0",
    "geometry": "esriGeometryPolygon",
    "fields": {
      "OBJECTID0": "recordId",
      "OP_LAND_USE_CATEGORY": "publishedOpLandUseCategory",
      "OP_LAND_USE_CLASS": "publishedOpLandUseClass",
      "FIGURE_NUMBER": "publishedFigureNumber",
      "SECONDARY_PLAN_BYLAW": "publishedSecondaryPlanBylaw"
    },
    "fieldTypes": {
      "OBJECTID0": "esriFieldTypeOID",
      "OP_LAND_USE_CATEGORY": "esriFieldTypeString",
      "OP_LAND_USE_CLASS": "esriFieldTypeString",
      "FIGURE_NUMBER": "esriFieldTypeString",
      "SECONDARY_PLAN_BYLAW": "esriFieldTypeString"
    },
    "dates": [],
    "note": "Published 2012 land-use reference polygons. The City publishes a 2026 consolidated plan; this feed does not establish current policy, amendments or permissions.",
    "source": {
      "id": "waterloo-region:cambridge:landUse2012",
      "name": "Cambridge Land Use (2012 Official Plan)",
      "url": "https://www.arcgis.com/home/item.html?id=4a9eb041957f4326968ac1891a6fbe96",
      "licence": "Open Government Licence – City of Cambridge 2.1",
      "licenceUrl": "https://www.cambridge.ca/mayor-city-council-government/open-data/",
      "attribution": "Contains information licensed under the Open Government Licence – City of Cambridge."
    }
  },
  {
    "market": "Cambridge",
    "publisher": "cambridge",
    "key": "secondaryPlans",
    "group": "officialPlan",
    "item": "28125f27f3af4ea8a1b86cdc61114215",
    "rootUrl": "https://services5.arcgis.com/LTaPSxJTf948f8sm/arcgis/rest/services/Secondary Plans/FeatureServer",
    "url": "https://services5.arcgis.com/LTaPSxJTf948f8sm/arcgis/rest/services/Secondary%20Plans/FeatureServer/0",
    "owner": "fme_connection",
    "org": "LTaPSxJTf948f8sm",
    "expectedItemTitle": "Secondary Plans",
    "expectedLayerName": "Secondary Plans",
    "expectedCopyright": "",
    "termsHash": "4d400f02340379a5088c0c09e03650c3fc0017858a10b20be3d9f49779a13c5e",
    "oid": "OBJECTID",
    "geometry": "esriGeometryPolygon",
    "fields": {
      "OBJECTID": "recordId",
      "NAME": "publishedName",
      "MAP_TITLE": "publishedMapTitle",
      "STATUS": "publishedStatus",
      "BYLAW_NUMBER": "publishedBylawNumber",
      "BYLAW_NUMBER2": "publishedBylawNumber2",
      "OPA_NUMBER": "publishedOpaNumber",
      "CHAPTER_NUMBER": "publishedChapterNumber"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "NAME": "esriFieldTypeString",
      "MAP_TITLE": "esriFieldTypeString",
      "STATUS": "esriFieldTypeString",
      "BYLAW_NUMBER": "esriFieldTypeString",
      "BYLAW_NUMBER2": "esriFieldTypeString",
      "OPA_NUMBER": "esriFieldTypeString",
      "CHAPTER_NUMBER": "esriFieldTypeString"
    },
    "dates": [],
    "note": "Published secondary-plan reference polygons and raw status; current in-force policies, amendments and appeal decisions remain unverified.",
    "source": {
      "id": "waterloo-region:cambridge:secondaryPlans",
      "name": "Cambridge Secondary Plans",
      "url": "https://www.arcgis.com/home/item.html?id=28125f27f3af4ea8a1b86cdc61114215",
      "licence": "Open Government Licence – City of Cambridge 2.1",
      "licenceUrl": "https://www.cambridge.ca/mayor-city-council-government/open-data/",
      "attribution": "Contains information licensed under the Open Government Licence – City of Cambridge."
    }
  },
  {
    "market": "Cambridge",
    "publisher": "cambridge",
    "key": "planAmendments",
    "group": "planningApplications",
    "item": "892df7cf4bf2487eab7cf68190554eb6",
    "rootUrl": "https://services5.arcgis.com/LTaPSxJTf948f8sm/arcgis/rest/services/OZ/FeatureServer",
    "url": "https://services5.arcgis.com/LTaPSxJTf948f8sm/arcgis/rest/services/OZ/FeatureServer/0",
    "owner": "fme_connection",
    "org": "LTaPSxJTf948f8sm",
    "expectedItemTitle": "Official Plan and Zoning Bylaw Amendments",
    "expectedLayerName": "Official Plan and Zoning Bylaw Amendments",
    "expectedCopyright": "",
    "termsHash": "4d400f02340379a5088c0c09e03650c3fc0017858a10b20be3d9f49779a13c5e",
    "oid": "OBJECTID",
    "geometry": "esriGeometryPolygon",
    "fields": {
      "OBJECTID": "recordId",
      "REFERENCEFILE": "publishedReferencefile",
      "CITY_WEB": "publishedCityWeb",
      "FOLDERRSN": "publishedFolderrsn",
      "STATUSDESC": "publishedStatus",
      "PROPHOUSE": "publishedProphouse",
      "PROPSTREET": "publishedPropstreet",
      "PROPSTREETTYPE": "publishedPropstreettype",
      "INDATE": "publishedIndate",
      "COUNCIL_MEETING_DATE": "publishedCouncilMeetingDate",
      "PLN_DEV_MEETING_DATE": "publishedPlnDevMeetingDate",
      "APP_DEEMED_COMPLETE": "publishedAppDeemedComplete",
      "ZB_APPEAL_END": "publishedZbAppealEnd",
      "ZB_PASSED_DATE": "publishedZbPassedDate",
      "OPA_APPEAL_END": "publishedOpaAppealEnd",
      "OPA_ADOPT_REFUSE_DATE": "publishedOpaAdoptRefuseDate",
      "PROP_OP_DESIGNATION": "publishedPropOpDesignation",
      "CURRENT_ZONING": "publishedCurrentZoning",
      "PROP_ZONING": "publishedPropZoning",
      "PROP_LAND_USE": "publishedPropLandUse"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "REFERENCEFILE": "esriFieldTypeString",
      "CITY_WEB": "esriFieldTypeString",
      "FOLDERRSN": "esriFieldTypeInteger",
      "STATUSDESC": "esriFieldTypeString",
      "PROPHOUSE": "esriFieldTypeString",
      "PROPSTREET": "esriFieldTypeString",
      "PROPSTREETTYPE": "esriFieldTypeString",
      "INDATE": "esriFieldTypeDate",
      "COUNCIL_MEETING_DATE": "esriFieldTypeDate",
      "PLN_DEV_MEETING_DATE": "esriFieldTypeDate",
      "APP_DEEMED_COMPLETE": "esriFieldTypeDate",
      "ZB_APPEAL_END": "esriFieldTypeDate",
      "ZB_PASSED_DATE": "esriFieldTypeDate",
      "OPA_APPEAL_END": "esriFieldTypeDate",
      "OPA_ADOPT_REFUSE_DATE": "esriFieldTypeDate",
      "PROP_OP_DESIGNATION": "esriFieldTypeString",
      "CURRENT_ZONING": "esriFieldTypeString",
      "PROP_ZONING": "esriFieldTypeString",
      "PROP_LAND_USE": "esriFieldTypeString"
    },
    "dates": [
      "INDATE",
      "COUNCIL_MEETING_DATE",
      "PLN_DEV_MEETING_DATE",
      "APP_DEEMED_COMPLETE",
      "ZB_APPEAL_END",
      "ZB_PASSED_DATE",
      "OPA_APPEAL_END",
      "OPA_ADOPT_REFUSE_DATE"
    ],
    "note": "Official-plan/zoning-amendment file polygons intersect the point. Raw status, proposed permissions and recorded dates do not establish current approval, conditions or appeal outcome. CURRENT_OP_DESINATION is excluded because the source declares it as a date, not designation text. Nearby proposals and full file history are unsearched.",
    "source": {
      "id": "waterloo-region:cambridge:planAmendments",
      "name": "Cambridge Official Plan and Zoning Bylaw Amendments",
      "url": "https://www.arcgis.com/home/item.html?id=892df7cf4bf2487eab7cf68190554eb6",
      "licence": "Open Government Licence – City of Cambridge 2.1",
      "licenceUrl": "https://www.cambridge.ca/mayor-city-council-government/open-data/",
      "attribution": "Contains information licensed under the Open Government Licence – City of Cambridge."
    }
  },
  {
    "market": "Cambridge",
    "publisher": "cambridge",
    "key": "sitePlans",
    "group": "planningApplications",
    "item": "a73c7cb57adc4384ad1b3765abfa00ff",
    "rootUrl": "https://services5.arcgis.com/LTaPSxJTf948f8sm/arcgis/rest/services/SitePlans/FeatureServer",
    "url": "https://services5.arcgis.com/LTaPSxJTf948f8sm/arcgis/rest/services/SitePlans/FeatureServer/0",
    "owner": "fme_connection",
    "org": "LTaPSxJTf948f8sm",
    "expectedItemTitle": "Site Plans",
    "expectedLayerName": "Site Plans",
    "expectedCopyright": "",
    "termsHash": "4d400f02340379a5088c0c09e03650c3fc0017858a10b20be3d9f49779a13c5e",
    "oid": "OBJECTID",
    "geometry": "esriGeometryPolygon",
    "fields": {
      "OBJECTID": "recordId",
      "REFERENCEFILE": "publishedReferencefile",
      "STATUSDESC": "publishedStatus",
      "PROPHOUSE": "publishedProphouse",
      "PROPSTREET": "publishedPropstreet",
      "PROPSTREETTYPE": "publishedPropstreettype",
      "CURRENT_OP_DESINATION": "publishedCurrentOpDesination",
      "CURRENT_ZONING": "publishedCurrentZoning",
      "PROP_LAND_USE": "publishedPropLandUse",
      "FOLDERDESCRIPTION": "publishedFolderdescription",
      "SUBDESC": "publishedSubdesc",
      "WORKDESC": "publishedWorkdesc",
      "INDATE": "publishedIndate"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "REFERENCEFILE": "esriFieldTypeString",
      "STATUSDESC": "esriFieldTypeString",
      "PROPHOUSE": "esriFieldTypeString",
      "PROPSTREET": "esriFieldTypeString",
      "PROPSTREETTYPE": "esriFieldTypeString",
      "CURRENT_OP_DESINATION": "esriFieldTypeString",
      "CURRENT_ZONING": "esriFieldTypeString",
      "PROP_LAND_USE": "esriFieldTypeString",
      "FOLDERDESCRIPTION": "esriFieldTypeString",
      "SUBDESC": "esriFieldTypeString",
      "WORKDESC": "esriFieldTypeString",
      "INDATE": "esriFieldTypeDate"
    },
    "dates": [
      "INDATE"
    ],
    "note": "Site-plan file polygons intersect the point. Raw use/zoning/status text does not establish a current approval, conditions, compliance or complete planning history.",
    "source": {
      "id": "waterloo-region:cambridge:sitePlans",
      "name": "Cambridge Site Plans",
      "url": "https://www.arcgis.com/home/item.html?id=a73c7cb57adc4384ad1b3765abfa00ff",
      "licence": "Open Government Licence – City of Cambridge 2.1",
      "licenceUrl": "https://www.cambridge.ca/mayor-city-council-government/open-data/",
      "attribution": "Contains information licensed under the Open Government Licence – City of Cambridge."
    }
  },
  {
    "market": "Region of Waterloo",
    "publisher": "region",
    "key": "addresses",
    "group": "addresses",
    "item": "d4d0c6dedec14e59930688f3830776c6",
    "rootUrl": "https://utility.arcgis.com/usrsvcs/servers/d4d0c6dedec14e59930688f3830776c6/rest/services/OpenData/OpenData/MapServer/1",
    "url": "https://utility.arcgis.com/usrsvcs/servers/d4d0c6dedec14e59930688f3830776c6/rest/services/OpenData/OpenData/MapServer/1",
    "owner": "RegionOfWaterloo",
    "org": "OmHQFOzJVFkeeZs8",
    "expectedItemTitle": "Addresses",
    "expectedLayerName": "Addresses",
    "expectedCopyright": "City of Cambridge - Planning Services Department, City of Kitchener - (GIS - Corporate Services Department and Department of Development and Technical Services, Township of North Dumfries, City of Waterloo GIS Department, Township of Wellesley, Township of Wilmot, Township of Woolwich - Engineering and Planning Services Department",
    "termsHash": "fd8bfa7de396659cf427a07e46d198711b04128afe0ed3c80cb6e8830edca5af",
    "oid": "OBJECTID",
    "geometry": "esriGeometryPoint",
    "fields": {
      "OBJECTID": "recordId",
      "FullAddress": "publishedAddress",
      "AddressPointType": "publishedAddressPointType",
      "FullStreetName": "publishedFullStreetName",
      "AddressNumber": "publishedAddressNumber",
      "UnitNumber": "publishedUnitNumber",
      "UnitType": "publishedUnitType",
      "Municipality": "publishedMunicipality",
      "Settlement": "publishedSettlement",
      "FullAddressWithSettlement": "publishedFullAddressWithSettlement",
      "CreatedDate": "publishedCreatedDate",
      "LastEditDate": "publishedLastEditDate",
      "IsPrimary": "publishedIsPrimary"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "FullAddress": "esriFieldTypeString",
      "AddressPointType": "esriFieldTypeString",
      "FullStreetName": "esriFieldTypeString",
      "AddressNumber": "esriFieldTypeString",
      "UnitNumber": "esriFieldTypeString",
      "UnitType": "esriFieldTypeString",
      "Municipality": "esriFieldTypeString",
      "Settlement": "esriFieldTypeString",
      "FullAddressWithSettlement": "esriFieldTypeString",
      "CreatedDate": "esriFieldTypeDate",
      "LastEditDate": "esriFieldTypeDate",
      "IsPrimary": "esriFieldTypeString"
    },
    "dates": [
      "CreatedDate",
      "LastEditDate"
    ],
    "note": "Regional civic identity and location, with contributing-municipality attribution. Address type and primary flag do not establish a building centroid, active address, legal dwelling or individual unit.",
    "source": {
      "id": "waterloo-region:region:addresses",
      "name": "Region of Waterloo Addresses",
      "url": "https://www.arcgis.com/home/item.html?id=d4d0c6dedec14e59930688f3830776c6",
      "licence": "Region of Waterloo Open Data Licence",
      "licenceUrl": "https://www.regionofwaterloo.ca/government-and-council/transparency-and-accountability/open-data/",
      "attribution": "Contains information provided by the Regional Municipality of Waterloo under licence · Source contributors: City of Cambridge - Planning Services Department, City of Kitchener - (GIS - Corporate Services Department and Department of Development and Technical Services, Township of North Dumfries, City of Waterloo GIS Department, Township of Wellesley, Township of Wilmot, Township of Woolwich - Engineering and Planning Services Department"
    }
  },
  {
    "market": "Region of Waterloo",
    "publisher": "region",
    "key": "regionalBoundary",
    "group": "regionalBoundary",
    "item": "259750cc5e8c44f78c56d27ac28b04ed",
    "rootUrl": "https://utility.arcgis.com/usrsvcs/servers/259750cc5e8c44f78c56d27ac28b04ed/rest/services/OpenData/OpenData/MapServer/16",
    "url": "https://utility.arcgis.com/usrsvcs/servers/259750cc5e8c44f78c56d27ac28b04ed/rest/services/OpenData/OpenData/MapServer/16",
    "owner": "RegionOfWaterloo",
    "org": "OmHQFOzJVFkeeZs8",
    "expectedItemTitle": "Regional Boundary",
    "expectedLayerName": "Regional Boundary",
    "expectedCopyright": "",
    "termsHash": "fd8bfa7de396659cf427a07e46d198711b04128afe0ed3c80cb6e8830edca5af",
    "oid": "OBJECTID",
    "geometry": "esriGeometryPolygon",
    "fields": {
      "OBJECTID": "recordId",
      "ShortName": "publishedShortName",
      "LongName": "publishedLongName"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "ShortName": "esriFieldTypeString",
      "LongName": "esriFieldTypeString"
    },
    "dates": [],
    "note": "Regional boundary point confirmation. A separate unique City boundary must also agree before property layers are queried.",
    "source": {
      "id": "waterloo-region:region:regionalBoundary",
      "name": "Region of Waterloo Regional Boundary",
      "url": "https://www.arcgis.com/home/item.html?id=259750cc5e8c44f78c56d27ac28b04ed",
      "licence": "Region of Waterloo Open Data Licence",
      "licenceUrl": "https://www.regionofwaterloo.ca/government-and-council/transparency-and-accountability/open-data/",
      "attribution": "Contains information provided by the Regional Municipality of Waterloo under licence"
    }
  },
  {
    "market": "Region of Waterloo",
    "publisher": "region",
    "key": "sensitiveLandscapes",
    "group": "regionalEnvironment",
    "item": "a79fd2eadcca451b83f55cd6c649d3a3",
    "rootUrl": "https://utility.arcgis.com/usrsvcs/servers/a79fd2eadcca451b83f55cd6c649d3a3/rest/services/OpenData/OpenData/MapServer/34",
    "url": "https://utility.arcgis.com/usrsvcs/servers/a79fd2eadcca451b83f55cd6c649d3a3/rest/services/OpenData/OpenData/MapServer/34",
    "owner": "RegionOfWaterloo",
    "org": "OmHQFOzJVFkeeZs8",
    "expectedItemTitle": "Environmentally Sensitive Landscapes",
    "expectedLayerName": "Environmentally Sensitive Landscapes",
    "expectedCopyright": "",
    "termsHash": "fd8bfa7de396659cf427a07e46d198711b04128afe0ed3c80cb6e8830edca5af",
    "oid": "OBJECTID",
    "geometry": "esriGeometryPolygon",
    "fields": {
      "OBJECTID": "recordId",
      "ID": "publishedId",
      "Name": "publishedName",
      "Area_Ha": "publishedAreaHa",
      "Status": "publishedStatus",
      "CreateDate": "publishedCreateDate",
      "EditDate": "publishedEditDate"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "ID": "esriFieldTypeDouble",
      "Name": "esriFieldTypeString",
      "Area_Ha": "esriFieldTypeDouble",
      "Status": "esriFieldTypeString",
      "CreateDate": "esriFieldTypeDate",
      "EditDate": "esriFieldTypeDate"
    },
    "dates": [
      "CreateDate",
      "EditDate"
    ],
    "note": "Regional environmentally sensitive landscape reference polygons derive from the published 2009 plan description. Raw status does not establish current legal policy, absence of environmental constraints or parcel-wide clearance.",
    "source": {
      "id": "waterloo-region:region:sensitiveLandscapes",
      "name": "Region of Waterloo Environmentally Sensitive Landscapes",
      "url": "https://www.arcgis.com/home/item.html?id=a79fd2eadcca451b83f55cd6c649d3a3",
      "licence": "Region of Waterloo Open Data Licence",
      "licenceUrl": "https://www.regionofwaterloo.ca/government-and-council/transparency-and-accountability/open-data/",
      "attribution": "Contains information provided by the Regional Municipality of Waterloo under licence"
    }
  },
  {
    "market": "Region of Waterloo",
    "publisher": "region",
    "key": "sensitivePolicyAreas",
    "group": "regionalEnvironment",
    "item": "d5da37b55cda47059b7f151e621dabc8",
    "rootUrl": "https://utility.arcgis.com/usrsvcs/servers/d5da37b55cda47059b7f151e621dabc8/rest/services/OpenData/OpenData/MapServer/29",
    "url": "https://utility.arcgis.com/usrsvcs/servers/d5da37b55cda47059b7f151e621dabc8/rest/services/OpenData/OpenData/MapServer/29",
    "owner": "RegionOfWaterloo",
    "org": "OmHQFOzJVFkeeZs8",
    "expectedItemTitle": "Environmentally Sensitive Policy Area (ESPA)",
    "expectedLayerName": "Environmentally Sensitive Policy Area (ESPA)",
    "expectedCopyright": "",
    "termsHash": "fd8bfa7de396659cf427a07e46d198711b04128afe0ed3c80cb6e8830edca5af",
    "oid": "OBJECTID",
    "geometry": "esriGeometryPolygon",
    "fields": {
      "OBJECTID": "recordId",
      "ESPA_Number": "publishedEspaNumber",
      "ESPA_Name": "publishedEspaName",
      "ESPA_Txt": "publishedEspaTxt",
      "Status": "publishedStatus",
      "Area_Ha": "publishedAreaHa",
      "CreateDate": "publishedCreateDate",
      "EditDate": "publishedEditDate"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "ESPA_Number": "esriFieldTypeSmallInteger",
      "ESPA_Name": "esriFieldTypeString",
      "ESPA_Txt": "esriFieldTypeString",
      "Status": "esriFieldTypeString",
      "Area_Ha": "esriFieldTypeDouble",
      "CreateDate": "esriFieldTypeDate",
      "EditDate": "esriFieldTypeDate"
    },
    "dates": [
      "CreateDate",
      "EditDate"
    ],
    "note": "Published regional sensitive-policy-area mapping refers to the 2009 plan and 2015 approval. Current municipal policy, later amendments and regulatory requirements remain unverified.",
    "source": {
      "id": "waterloo-region:region:sensitivePolicyAreas",
      "name": "Region of Waterloo Environmentally Sensitive Policy Area (ESPA)",
      "url": "https://www.arcgis.com/home/item.html?id=d5da37b55cda47059b7f151e621dabc8",
      "licence": "Region of Waterloo Open Data Licence",
      "licenceUrl": "https://www.regionofwaterloo.ca/government-and-council/transparency-and-accountability/open-data/",
      "attribution": "Contains information provided by the Regional Municipality of Waterloo under licence"
    }
  },
  {
    "market": "Region of Waterloo",
    "publisher": "region",
    "key": "significantWoodlands",
    "group": "regionalEnvironment",
    "item": "c0890acaef9d4e62ac14fc52c5ac9044",
    "rootUrl": "https://utility.arcgis.com/usrsvcs/servers/c0890acaef9d4e62ac14fc52c5ac9044/rest/services/OpenData/OpenData/MapServer/30",
    "url": "https://utility.arcgis.com/usrsvcs/servers/c0890acaef9d4e62ac14fc52c5ac9044/rest/services/OpenData/OpenData/MapServer/30",
    "owner": "RegionOfWaterloo",
    "org": "OmHQFOzJVFkeeZs8",
    "expectedItemTitle": "Significant Woodlands",
    "expectedLayerName": "Significant Woodlands ",
    "expectedCopyright": "",
    "termsHash": "fd8bfa7de396659cf427a07e46d198711b04128afe0ed3c80cb6e8830edca5af",
    "oid": "OBJECTID",
    "geometry": "esriGeometryPolygon",
    "fields": {
      "OBJECTID": "recordId",
      "Area_Ha": "publishedAreaHa",
      "CreateDate": "publishedCreateDate",
      "EditDate": "publishedEditDate"
    },
    "fieldTypes": {
      "OBJECTID": "esriFieldTypeOID",
      "Area_Ha": "esriFieldTypeDouble",
      "CreateDate": "esriFieldTypeDate",
      "EditDate": "esriFieldTypeDate"
    },
    "dates": [
      "CreateDate",
      "EditDate"
    ],
    "note": "Published regional significant-woodland reference inventory uses a greater-than-four-hectare source definition and excludes some wooded features. It is not a current complete tree/woodland, conservation-regulation or environmental clearance screen.",
    "source": {
      "id": "waterloo-region:region:significantWoodlands",
      "name": "Region of Waterloo Significant Woodlands",
      "url": "https://www.arcgis.com/home/item.html?id=c0890acaef9d4e62ac14fc52c5ac9044",
      "licence": "Region of Waterloo Open Data Licence",
      "licenceUrl": "https://www.regionofwaterloo.ca/government-and-council/transparency-and-accountability/open-data/",
      "attribution": "Contains information provided by the Regional Municipality of Waterloo under licence"
    }
  }
];
export const WATERLOO_WITHHELD=[
  {
    "market": "Kitchener",
    "layer": "zoning",
    "item": "771332f76961485098ac5b24d6ec9a5b",
    "reason": "The official Kitchener open-data portal explicitly excludes zoning, parcels and assessment from its open-data licence; a public viewer is not a reuse grant.",
    "url": "https://www.arcgis.com/home/item.html?id=771332f76961485098ac5b24d6ec9a5b"
  },
  {
    "market": "Kitchener",
    "layer": "zoning",
    "item": "119b393148dc4b30ae1094646c41b48a",
    "reason": "The zoning lookup carries viewer terms rather than a reusable open-data grant; Kitchener explicitly excludes zoning.",
    "url": "https://www.arcgis.com/home/item.html?id=119b393148dc4b30ae1094646c41b48a"
  },
  {
    "market": "Kitchener",
    "layer": "municipalAddresses",
    "item": "5ebf523eaf3d4cf2be250c5bd396423e",
    "reason": "No explicit per-item grant or City-specific catalogue/licence binding has been verified for this blank-terms item. Use the explicitly referred regional address feed.",
    "url": "https://www.arcgis.com/home/item.html?id=5ebf523eaf3d4cf2be250c5bd396423e"
  },
  {
    "market": "Waterloo",
    "layer": "heritageDistrict",
    "item": "10dc3ccfd32a49cc94a9e04bf1adebf2",
    "reason": "Blank item terms and absence from the City-curated open-data group prevent binding this feed to the City website licence.",
    "url": "https://www.arcgis.com/home/item.html?id=10dc3ccfd32a49cc94a9e04bf1adebf2"
  },
  {
    "market": "Waterloo",
    "layer": "planningApplications",
    "item": "7a1fdab5d73a46c48db229b1685b91f8",
    "reason": "The public major-development viewer does not supply a verified dataset-level reuse grant for its underlying files service.",
    "url": "https://www.arcgis.com/home/item.html?id=7a1fdab5d73a46c48db229b1685b91f8"
  },
  {
    "market": "Cambridge",
    "layer": "permits",
    "item": "9093dbbced88444fb61134187737c547",
    "reason": "The public building-permit item has blank terms; an explicit dataset-level grant or curated licence binding remains unverified.",
    "url": "https://www.arcgis.com/home/item.html?id=9093dbbced88444fb61134187737c547"
  },
  {
    "market": "Cambridge",
    "layer": "zoning",
    "item": "ab1a65de5f824ad6a1d3586a90cc1752",
    "reason": "Hybrid zoning item terms are blank; current 2026 bylaw applicability and reuse rights remain unverified.",
    "url": "https://www.arcgis.com/home/item.html?id=ab1a65de5f824ad6a1d3586a90cc1752"
  },
  {
    "market": "Cambridge",
    "layer": "heritageDistrict",
    "item": "c75c58806d384c96b7243785e588b67d",
    "reason": "The separate district item has blank terms and no verified dataset-level licence binding. Heritage parcels do not replace a full district screen.",
    "url": "https://www.arcgis.com/home/item.html?id=c75c58806d384c96b7243785e588b67d"
  },
  {
    "market": "Region of Waterloo",
    "layer": "floodZones",
    "item": "816b73ee544a44028abdc553a86135ec",
    "reason": "A blank-terms regional flood source includes Grand River Conservation Authority third-party mapping; regulatory coverage and reuse are unresolved.",
    "url": "https://www.arcgis.com/home/item.html?id=816b73ee544a44028abdc553a86135ec"
  },
  {
    "market": "Region of Waterloo",
    "layer": "wetlands",
    "item": "49fb9faa446945ca818b8524ba5c11ca",
    "reason": "Published provincial wetland classification is third-party-derived; authorization and current delineation remain unverified.",
    "url": "https://www.arcgis.com/home/item.html?id=49fb9faa446945ca818b8524ba5c11ca"
  }
];
