import { cityKey, layer, type Layer } from "./model";
import { provinceKey } from "./geocode";
import type { EvidenceQuestion } from "./brief";

const city = "https://www.cityofwoodstock.ca";
const county = "https://www.oxfordcounty.ca";
export const WOODSTOCK_PLANNING = `${county}/services-for-you/planning-and-development/development/woodstock/`;
export const OXFORD_CATALOGUE = "https://public-oxfordcounty.opendata.arcgis.com/";
export const OXFORD_TERMS = `${county}/general/terms-of-use`;
const requests = `${county}/services-for-you/mapping/data-requests/`;
const files = `${city}/your-government/freedom-of-information/`;
export const WOODSTOCK_RIGHTS = "The separate County open-data site describes the open-data idea, but no explicit compatible commercial merged-data redistribution grant was established for the selected County layers: most item grants are blank and parcel/footprint notices provide reference disclaimers. This is an unresolved grant, not a categorical ban on all open data. The contractor data-request licence separately prohibits commercial products without permission and external posting; the main County website terms separately restrict duplication. Those scoped terms are not automatically assigned to every catalogue dataset. Original provincial OGL sources are assessed independently. No County property feature/count/geometry queries or dataset integration were performed.";
const scope = (layer: string, url: string, reason: string, termsUrl = OXFORD_TERMS) => ({ layer, url, reason, termsUrl });
export const WOODSTOCK_WITHHELD = [
  scope("municipalAddresses", OXFORD_CATALOGUE, `${WOODSTOCK_RIGHTS} Civic metadata refers to 9-1-1/assessment origins and weekly export; it does not establish a precise building point or current parcel identity.`),
  scope("parcel", OXFORD_CATALOGUE, `${WOODSTOCK_RIGHTS} Parcel-line and zoning descriptions identify POLARIS/Teranet/MPAC lineage. Third-party commercial rights remain unverified; PIN, roll, ownership and legal boundaries are not reused.`),
  scope("catalogueZoningReference", OXFORD_CATALOGUE, `${WOODSTOCK_RIGHTS} The catalogue child is separate from GLIMR's CommunityPlanning/Zoning service; current service equivalence and written property permissions are unverified.`),
  scope("zoning", WOODSTOCK_PLANNING, "County guidance identifies Woodstock By-law 8626-10, a September 30, 2025 text consolidation, separately awaiting-consolidation Council amendments and a Q2 2026 zoning map. Confirm current written provisions, exceptions, holds, temporary-use/MZO/parking schedules, later amendments and appeals; separately dated text/maps do not prove present property permission."),
  scope("currentPlanningInstruments", WOODSTOCK_PLANNING, "Obtain the currently operative Woodstock zoning, Oxford Official Plan and relevant schedules, current amendments/appeals and property applicability. The site's current application notices/reports are a manual research route, not a complete decision or approval-history feed."),
  scope("officialPlan", `${county}/services-for-you/planning-and-development/official-plan/`, `${WOODSTOCK_RIGHTS} The catalogue describes a 1995 plan changed through amendments/orders. Current operative written policies, schedules, later amendments and appeals were not fully reviewed.`),
  ...["planningApplications", "variance", "consentToSever", "sitePlanDrawings"].map(name => scope(name, WOODSTOCK_PLANNING, `${WOODSTOCK_RIGHTS} Obtain the complete decision, cleared conditions, approved plans, registered agreements, expiry and appeal outcome. Notices, staff reports, draft agreements and process guidance do not establish final approval or current permission.`)),
  scope("sitePlanControl", `${city}/business-development/building-and-planning/site-plan-agreement-and-control/`, "City guidance names Site Plan Control By-law 8711-11 and Zoning By-law 8626-10, and directs applicants to confirm applicability with City/County staff. Current exemptions, amendments and property applicability were not independently verified; the general whole-City/process statement is not a legal determination for proposed work."),
  ...["permits", "inspectionResults", "occupancyDocuments"].map(name => scope(name, files, "The City offers owner/authorized-agent routine disclosure for building drawings/plans and directs permit/application, inspection-report and Building Code order access through a separate Legal Compliance Letter. Older/off-site files can be incomplete. Cloudpermit is an application workflow; published monthly reports are not complete property history, passed inspection results or verified occupancy. No request was submitted or paid.", `${city}/privacy-policy/`)),
  scope("woodstockBuildingReports", `${city}/your-government/plans-reports-and-studies/building-reports/`, "The City offers 2020–2025 annual reports and January–August 2026 monthly reports. These offers were audited; PDF contents, property observations, reusable publication rights and a complete current series are not integrated or counted. Annual/monthly activity cannot establish complete permit history or final inspections.", `${city}/privacy-policy/`),
  scope("additionalUnits", `${city}/business-development/building-and-planning/additional-residential-units/`, "City guidance says up to two ARUs may be permitted in R1/R2/R3/C3/HD, subject to restrictions and staff confirmation, with a building permit required. No current unit register or unit-specific approval is integrated. Confirm current exceptions, servicing, permit/final inspections and occupancy for each advertised unit; general eligibility or the County incentive program is not proof of legality.", `${city}/privacy-policy/`),
  ...["heritage", "heritageDistrict"].map(name => scope(name, `${city}/recreation-culture/history-and-heritage/`, "Current complete statutory register, listed/designated/district instruments and reusable rights are not integrated. A 2020 downtown plan and magazine counts are historical references. The City separately published April 2026 passage notice for 259–261 Park Row; final appeal outcome and present legal status were not verified. A Historical District zoning label is not itself Part V heritage designation.", `${city}/privacy-policy/`)),
  scope("propertySurveyRecords", files, "City guidance conflicts: the permit page says it does not provide survey copies, while routine-disclosure guidance offers surveys subject to authorization/availability and warns that older copies may be outdated. Confirm release eligibility directly with the City and obtain a current Ontario Land Surveyor/title review; do not choose one page silently or treat a GIS index as a survey.", `${city}/privacy-policy/`),
  scope("buildingFootprintReference", OXFORD_CATALOGUE, `${WOODSTOCK_RIGHTS} The footprint notice permits no accuracy/existence conclusion: shapes can derive aerial digitization or proposed site-plan envelopes. No geometry, measurements, current building identity or condition is inferred.`),
  scope("contourReference", OXFORD_CATALOGUE, "The County contours blend provincial terrain with City of Woodstock contours obtained March 2021. Provincial OGL attribution does not establish rights for the whole mixed source. No County contours are queried/counted; the original separately licensed Ontario lidar package index is integrated independently and does not sample elevation."),
  scope("woodstockConservationRegulation", "https://webmap.oxfordcounty.ca/Html5/?viewer=GLIMR", "City guidance offers GLIMR groundwater and development-constraint layers; these are separate from current original-authority regulation, floodplain and source-protection instruments. Originating rights, parcel-wide applicability and proposed-work requirements remain unverified. No map agreement was accepted and no regulatory clearance, flood-safety or insurance conclusion is available."),
];
export const WOODSTOCK_AUDIT = {
  city: "Woodstock", auditedAt: "2026-10-03", catalogue: OXFORD_CATALOGUE, terms: OXFORD_TERMS, rightsFinding: WOODSTOCK_RIGHTS,
  featureQueriesPerformed: false, countsQueried: false, geometryQueried: false, recordSearchRequested: false, complete: false,
  metadata: { catalogueEntries: 22, countMeaning: "Catalogue entries, not property records or integrated feeds.", siteItem: "1b8a5ca1bd3d41e0a9a5a332784e31b2", cityGIS: `${city}/business-development/maps-and-gis-information/`, cityHasPublicGISPortal: false, contractorTerms: requests, catalogueTermsScope: "Open-data definition, blank grants and selected reference notices reviewed separately from full contractor agreement and main website terms.", zoningTextConsolidation: "2025-09-30", offeredZoningMap: "Q2 2026", surveyGuidanceConflict: true, cityPrivacyPageScope: "Current offered page contains a heading/contact block without a reusable publication grant; no broad City commercial prohibition inferred.", annualReportOffers: "2020–2025", monthlyReportOffers: "January–August 2026", reportPDFsParsed: false, heritagePassageNotice: `${city}/news/posts/notice-of-passing-of-heritage-designation-bylaw-259-261-park-row/`, heritageAppealOutcomeVerified: false, countyContourScope: "Mixed original provincial/City contours; no full blended-source grant established.", independentProvinceIndex: "Original Ontario OGL lidar package index; no County layers or raster pixels counted." },
};
export function woodstockMarket(name: string | null | undefined, province: string | null | undefined): boolean { return provinceKey(province ?? "") === "ontario" && cityKey(name ?? "") === "woodstock"; }
export function woodstockLayers(name: string | null | undefined, province: string | null | undefined): Record<string, Layer> {
  return woodstockMarket(name, province) ? Object.fromEntries(WOODSTOCK_WITHHELD.map(g => [g.layer, layer("unavailable", { coverageComplete: false, screenPerformed: false, featureQueriesPerformed: false, countsQueried: false, geometryQueried: false, recordSearchRequested: false, withheld: g, audit: { city: WOODSTOCK_AUDIT.city, auditedAt: WOODSTOCK_AUDIT.auditedAt, terms: OXFORD_TERMS } }, null, g.reason)])) : {};
}
export function woodstockQuestions(name: string | null | undefined, province: string | null | undefined): EvidenceQuestion[] {
  return woodstockMarket(name, province) ? [
    { topic: "woodstock_current_planning", question: "Can City/County staff confirm current 8626-10 provisions, exceptions/holds, post-September2025 amendments, operative plan/MZO/parking/temporary schedules and appeals? Obtain final planning/Committee decisions, cleared conditions and approved/registered site-plan instruments; Q2 2026 mapping, application notices and draft agreements are separate evidence.", evidenceLayers: ["zoning", "currentPlanningInstruments", "officialPlan", "planningApplications", "variance", "consentToSever", "sitePlanDrawings", "sitePlanControl"] },
    { topic: "woodstock_building_units_and_surveys", question: "Can the seller authorize routine disclosure and the separate Legal Compliance Letter, and provide complete permit/inspection/order/occupancy and each advertised ARU's approvals? Confirm older-file gaps and reconcile the conflicting survey-release guidance with the City; obtain a current survey and actual servicing/capacity evidence.", evidenceLayers: ["permits", "inspectionResults", "occupancyDocuments", "additionalUnits", "propertySurveyRecords", "woodstockBuildingReports"] },
    { topic: "woodstock_heritage_and_constraints", question: "Can the Clerk provide current listed/designated/district instruments and appeal outcomes, and can the original authority confirm parcel-wide regulation/source protection and proposed-work requirements? Historical District zoning, proposed building envelopes, mixed contours and lidar package resolution do not establish these facts.", evidenceLayers: ["heritage", "heritageDistrict", "buildingFootprintReference", "contourReference", "woodstockConservationRegulation", "ontarioLidarCoverageReference"] },
  ] : [];
}
export function woodstockCoverage() { return { cities: [WOODSTOCK_AUDIT.city], auditDate: WOODSTOCK_AUDIT.auditedAt, delivery: "metadata_only_reuse_audit", datasets: [], withheld: WOODSTOCK_WITHHELD.map(g => ({ ...g, status: "withheld", records: null })), complete: false, audit: WOODSTOCK_AUDIT, note: "Woodstock/Oxford source-guidance audit with explicit gaps. Separate original Ontario reference feeds are counted once in their own coverage entries. No City/County property feed integrated or counted; other Oxford municipalities remain unaudited." }; }
