/**
 * Hosted agent result — /v/:token.
 *
 * When someone's AI agent (Claude, Codex, Grok, Cursor, a plain REST client…)
 * calls a Realist tool, the result includes a link to this page: the visual,
 * interactive version of what the agent just computed. The unguessable token
 * is the only credential — no sign-in wall, because the visitor is arriving
 * mid-conversation from another app.
 */
import { Link, useParams } from "wouter";
import { useQuery } from "@tanstack/react-query";
import { SearchX } from "lucide-react";
import { SEO } from "@/components/SEO";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { ViewFooter, ViewHeader } from "@/components/agent-views/ViewChrome";
import { UnderwritingView } from "@/components/agent-views/UnderwritingView";
import { ReportView } from "@/components/agent-views/ReportView";
import { AGENT_VIEW_DISCLAIMER, type ReportViewDocument, type UnderwritingViewDocument } from "@shared/agentViews";

interface ViewPayload {
  token: string;
  kind: "underwriting" | "report";
  title: string;
  createdAt: string;
  document: Omit<UnderwritingViewDocument, "analysisId"> | ReportViewDocument;
}

function Loading() {
  return (
    <div className="max-w-7xl mx-auto px-4 md:px-6 py-8 space-y-6" data-testid="view-loading">
      <Skeleton className="h-9 w-2/3 max-w-xl" />
      <div className="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-6 gap-3">
        {Array.from({ length: 6 }, (_, i) => <Skeleton key={i} className="h-24" />)}
      </div>
      <Skeleton className="h-96" />
    </div>
  );
}

function NotFound() {
  return (
    <div className="max-w-xl mx-auto px-4 py-24 text-center" data-testid="view-not-found">
      <SearchX className="h-10 w-10 mx-auto text-muted-foreground" />
      <h1 className="mt-4 text-2xl font-bold">This result isn't available</h1>
      <p className="mt-2 text-muted-foreground">
        The link may be incomplete, or the result was deleted by its owner. Ask your AI agent to run the analysis again for a fresh link.
      </p>
      <div className="mt-6 flex justify-center gap-2">
        <Button asChild><Link href="/tools/analyzer">Open the deal analyzer</Link></Button>
        <Button asChild variant="outline"><Link href="/developers">Connect an AI agent</Link></Button>
      </div>
    </div>
  );
}

export default function AgentResultView() {
  const { token = "" } = useParams<{ token: string }>();
  const { data, isLoading, isError } = useQuery<ViewPayload>({
    queryKey: [`/api/views/${token}`],
    enabled: !!token,
    retry: false,
  });
  const document = data?.document;

  return (
    <div className="min-h-screen bg-background flex flex-col">
      <SEO
        title={data?.title ? `${data.title} — Realist` : "Agent result — Realist"}
        description="An interactive result generated by an AI agent through the Realist API."
        noIndex
      />
      <ViewHeader />
      <div className="flex-1">
        {isLoading ? (
          <Loading />
        ) : isError || !document ? (
          <NotFound />
        ) : document.kind === "underwriting" ? (
          <UnderwritingView token={token} document={document} />
        ) : (
          <ReportView document={document} />
        )}
      </div>
      <ViewFooter
        disclaimer={document?.disclaimer ?? AGENT_VIEW_DISCLAIMER}
        generatedAt={document?.generatedAt ?? data?.createdAt ?? ""}
        tool={document?.tool ?? "the Realist API"}
      />
    </div>
  );
}
