/** Field map only — not the official OREA Form 100 PDF. */
import { field, FORM_COPYRIGHT_NOTE, type FormMap } from "../types";

export const orea100: FormMap = {
  formId: "orea-100",
  title: "Agreement of Purchase and Sale",
  board: "OREA",
  jurisdiction: "ON",
  mapVersion: "2026.09.1-draft",
  mapConfidence: "draft",
  copyrightNote: FORM_COPYRIGHT_NOTE,
  fields: [
    field({ key: "buyer_1_name", label: "Buyer name", type: "text", party: "buyer", required: true, pageHint: "p.1 parties", bind: ["parties.buyer.name"] }),
    field({ key: "buyer_1_email", label: "Buyer email", type: "text", party: "buyer", required: false, bind: ["parties.buyer.email"] }),
    field({ key: "buyer_1_phone", label: "Buyer phone", type: "text", party: "buyer", required: false, bind: ["parties.buyer.phone"] }),
    field({ key: "seller_1_name", label: "Seller name", type: "text", party: "seller", required: true, pageHint: "p.1 parties", bind: ["parties.seller.name"] }),
    field({ key: "seller_1_email", label: "Seller email", type: "text", party: "seller", required: false, bind: ["parties.seller.email"] }),
    field({ key: "seller_1_phone", label: "Seller phone", type: "text", party: "seller", required: false, bind: ["parties.seller.phone"] }),
    field({ key: "property_address", label: "Property address", type: "text", required: true, pageHint: "p.1 property", bind: ["property.address", "property.streetAddress"] }),
    field({ key: "property_city", label: "City", type: "text", required: false, bind: ["property.city"] }),
    field({ key: "property_province", label: "Province", type: "text", required: false, bind: ["property.province"] }),
    field({ key: "property_postal_code", label: "Postal code", type: "text", required: false, bind: ["property.postalCode"] }),
    field({ key: "mls_number", label: "MLS number", type: "text", required: false, bind: ["listing.mlsNumber", "deal.mlsNumber"] }),
    field({ key: "purchase_price", label: "Purchase price", type: "currency", required: true, pageHint: "p.1 price", bind: ["facts.purchasePrice"] }),
    field({ key: "deposit_amount", label: "Deposit", type: "currency", required: true, bind: ["facts.depositAmount"] }),
    field({ key: "deposit_held_by", label: "Deposit held by", type: "text", required: false, bind: ["facts.depositHeldBy"] }),
    field({ key: "offer_date", label: "Offer date", type: "date", required: false, bind: ["facts.offerDate"] }),
    field({ key: "irrevocable_date", label: "Irrevocable date", type: "date", required: false, bind: ["facts.irrevocableDate"] }),
    field({ key: "completion_date", label: "Completion date", type: "date", required: true, bind: ["facts.closingDate"] }),
    field({ key: "requisition_date", label: "Requisition date", type: "date", required: false, bind: ["facts.requisitionDate"] }),
    field({ key: "inclusions", label: "Inclusions", type: "text", required: false, bind: ["facts.inclusions"] }),
    field({ key: "exclusions", label: "Exclusions", type: "text", required: false, bind: ["facts.exclusions"] }),
    field({ key: "buyer_brokerage", label: "Buyer brokerage", type: "text", party: "buyer_broker", required: false, bind: ["parties.buyerBroker.brokerage", "parties.buyerBroker.name"] }),
    field({ key: "seller_brokerage", label: "Seller brokerage", type: "text", party: "seller_broker", required: false, bind: ["parties.sellerBroker.brokerage", "parties.sellerBroker.name"] }),
    field({ key: "buyer_1_initials", label: "Buyer initials", type: "initials", party: "buyer", required: true, pageHint: "each page" }),
    field({ key: "seller_1_initials", label: "Seller initials", type: "initials", party: "seller", required: true, pageHint: "each page" }),
    field({ key: "buyer_1_signature", label: "Buyer signature", type: "signature", party: "buyer", required: true, pageHint: "execution" }),
    field({ key: "seller_1_signature", label: "Seller signature", type: "signature", party: "seller", required: true, pageHint: "execution" }),
  ],
};
