import { DEFAULT_AUTHOR, type ReportContent } from "../reportContent";

const STATCAN_DAILY_URL =
  "https://www150.statcan.gc.ca/n1/daily-quotidien/260807/dq260807a-eng.htm";
const STATCAN_HEADLINE_TABLE_URL =
  "https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410028701";
const STATCAN_CLASS_TABLE_URL =
  "https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410028801";
const BOC_ARREARS_PAPER_URL =
  "https://www.bankofcanada.ca/2026/03/staff-analytical-paper-2026-12/";
const CMHC_MORTGAGE_REPORT_URL =
  "https://www.cmhc-schl.gc.ca/professionals/housing-markets-data-and-research/housing-research/research-reports/housing-finance/residential-mortgage-industry-report";
const REALIST_LABOUR_EXPLORER = "https://stats.realist.ca/labour";

export const canadaLabourForceSurveyJuly2026ConfigReport: ReportContent = {
  slug: "canada-labour-force-survey-july-2026-housing",
  title: "Canada Labour Force Survey July 2026: Jobs Improve, but Public-Sector Hiring Turns Negative",
  dek:
    "Canada added 75,100 jobs in July and unemployment fell to a two-year low of 6.4%. That is good news for buyer confidence and mortgage risk—but the public-to-private shift and still-elevated youth unemployment keep this from being an all-clear for housing.",
  author: DEFAULT_AUTHOR,
  publishDate: "2026-08-07",
  kind: "macro",
  tags: [
    "Canada jobs report",
    "Labour Force Survey",
    "unemployment rate Canada",
    "Canadian housing market",
    "mortgage delinquency",
    "public sector employment",
    "Statistics Canada",
    "Bank of Canada",
  ],
  metaTitle: "Canada Jobs Report July 2026: Housing & Mortgage Impact | Realist",
  metaDescription:
    "Canada added 75,100 jobs and unemployment fell to 6.4% in July 2026. Realist explains the housing, mortgage arrears, rate and public-sector implications.",
  ogImage: "/reports/canada-labour-force-survey-july-2026-housing/og.png",
  heroStat: {
    label: "Canada unemployment rate, July 2026",
    value: "6.4%",
    detail:
      "Down for a third straight month and the lowest since July 2024. Employment rose by 75,100 and the employment rate increased to 60.9%.",
  },
  sections: [
    {
      type: "statGrid",
      id: "july-jobs-report",
      heading: "Canada’s July 2026 jobs report",
      stats: [
        { label: "Employment change", value: "+75,100", detail: "+0.4% month over month", trend: "up" },
        { label: "Unemployment rate", value: "6.4%", detail: "Lowest in two years", trend: "down" },
        { label: "Employment rate", value: "60.9%", detail: "+0.1 percentage points", trend: "up" },
        { label: "Private-sector jobs", value: "+58,000", detail: "Month over month", trend: "up" },
        { label: "Public-sector jobs", value: "−27,000", detail: "Month over month", trend: "down" },
        { label: "Job-finding rate", value: "20.8%", detail: "18.5% one year earlier", trend: "up" },
      ],
    },
    {
      type: "narrative",
      id: "bottom-line",
      heading: "Bottom line: people do not buy homes when they are afraid of losing their jobs",
      body:
        "The July Labour Force Survey is the clearest improvement in Canada’s jobs story in months. Employment rose by **75,100**, the unemployment rate fell to **6.4%**, and a larger share of unemployed people found work than a year ago. Since April, Canada has added **181,000 jobs**, driven by a **193,000 increase in full-time work**.\n\nThat matters to housing because job security sits upstream of almost every purchase decision. Mortgage rates decide what a household can afford; confidence that the paycheque will continue decides whether the household is willing to act. Falling unemployment does not create an instant housing boom, but it removes one of the biggest reasons buyers stay on the sidelines.\n\nThe catch is composition. Private-sector employment and self-employment strengthened while public-sector employment fell. Youth unemployment remains high. The job-finding rate improved, but it is still below its pre-pandemic norm. The right read is **better, not perfect**.",
    },
    {
      type: "chart",
      chartType: "line",
      id: "unemployment-mortgage-arrears",
      title: "Why housing analysts watch the LFS: unemployment and mortgage arrears move together",
      caption:
        "Annual averages indexed to 100 in 1995 so the two differently scaled series can be compared on one axis. The monthly correlation from 1995 through the latest common observation is about 0.69. Correlation is descriptive, not proof of causation. The COVID shock is an important exception because payment deferrals and income supports interrupted the normal transmission into arrears. Sources: Statistics Canada LFS; Canadian Bankers Association via Bank of Canada. Explore the actual dual-axis monthly series at stats.realist.ca/labour.",
      xKey: "year",
      yAxisLabel: "Index (1995 = 100)",
      format: "number",
      referenceLine: { value: 100, label: "1995 baseline" },
      series: [
        { key: "unemployment", label: "Unemployment rate index", color: "#2563eb" },
        { key: "arrears", label: "Mortgage arrears index", color: "#dc2626" },
      ],
      data: [
        { year: "1995", unemployment: 100.0, arrears: 100.0 },
        { year: "1996", unemployment: 101.5, arrears: 112.9 },
        { year: "1997", unemployment: 96.0, arrears: 109.2 },
        { year: "1998", unemployment: 87.6, arrears: 91.3 },
        { year: "1999", unemployment: 79.9, arrears: 88.8 },
        { year: "2000", unemployment: 72.2, arrears: 78.5 },
        { year: "2001", unemployment: 76.3, arrears: 81.0 },
        { year: "2002", unemployment: 81.2, arrears: 75.5 },
        { year: "2003", unemployment: 80.2, arrears: 66.0 },
        { year: "2004", unemployment: 75.5, arrears: 54.3 },
        { year: "2005", unemployment: 71.3, arrears: 48.5 },
        { year: "2006", unemployment: 68.1, arrears: 46.5 },
        { year: "2007", unemployment: 65.1, arrears: 47.7 },
        { year: "2008", unemployment: 66.6, arrears: 52.7 },
        { year: "2009", unemployment: 89.5, arrears: 77.5 },
        { year: "2010", unemployment: 86.2, arrears: 80.2 },
        { year: "2011", unemployment: 80.5, arrears: 76.8 },
        { year: "2012", unemployment: 78.6, arrears: 64.0 },
        { year: "2013", unemployment: 76.1, arrears: 58.8 },
        { year: "2014", unemployment: 74.6, arrears: 54.9 },
        { year: "2015", unemployment: 73.9, arrears: 51.5 },
        { year: "2016", unemployment: 74.5, arrears: 52.4 },
        { year: "2017", unemployment: 67.8, arrears: 47.4 },
        { year: "2018", unemployment: 61.6, arrears: 44.3 },
        { year: "2019", unemployment: 60.0, arrears: 44.1 },
        { year: "2020", unemployment: 102.9, arrears: 45.9 },
        { year: "2021", unemployment: 79.0, arrears: 36.3 },
        { year: "2022", unemployment: 55.5, arrears: 27.9 },
        { year: "2023", unemployment: 57.0, arrears: 29.5 },
        { year: "2024", unemployment: 67.3, arrears: 36.8 },
        { year: "2025", unemployment: 72.4, arrears: 43.8 },
        { year: "2026", unemployment: 69.7, arrears: 51.5 },
      ],
    },
    {
      type: "callout",
      tone: "info",
      id: "explore-lfs-data",
      heading: "Explore the full dataset",
      body:
        "Use the [interactive Labour Force Survey dashboard](https://stats.realist.ca/labour) to inspect the actual monthly unemployment and mortgage-arrears rates on separate axes, zoom into any period, compare public/private/self-employed job growth, and download all 14 tables attached to this Statistics Canada release.",
    },
    {
      type: "narrative",
      id: "why-arrears-follow-jobs",
      heading: "The housing transmission: confidence first, mortgage stress later",
      body:
        "The relationship is intuitive. A household can absorb an unpleasant mortgage renewal if income continues. Losing a job removes that buffer. Mortgage arrears are also a late-stage indicator: borrowers generally cut spending, use savings, draw on revolving credit, miss other payments, seek a sale or modification, and only then fall 90 days behind on the mortgage.\n\nBank of Canada research identifies labour-market conditions as one of the key macro drivers of Canadian mortgage arrears. CMHC’s 2026 Residential Mortgage Industry Report likewise places unemployment beside mortgage arrears as closely linked housing-risk indicators. That is why the LFS matters even when you are not trading the bond market. It tells us something about **housing demand today** and **forced-sale risk later**.\n\nThe July signal is constructive. Unemployment has fallen for three straight months, and job finding improved. Mortgage arrears can still rise for a while because they lag earlier job weakness and payment shocks, but sustained labour improvement would limit how far that stress travels.",
    },
    {
      type: "chart",
      chartType: "composed",
      id: "employment-unemployment-rates",
      title: "The headline labour market has stabilized after a two-year deterioration",
      caption:
        "Selected Statistics Canada checkpoints from the July 2026 employment-rate and unemployment-rate infographics. The employment rate remains below its 2017–2019 average of 62.0%, while unemployment is now only 0.4 percentage points above its 2017–2019 average of 6.0%.",
      xKey: "month",
      yAxisLabel: "Percent",
      format: "percent",
      series: [
        { key: "employmentRate", label: "Employment rate", type: "line", color: "#2563eb" },
        { key: "unemploymentRate", label: "Unemployment rate", type: "bar", color: "#f97316" },
      ],
      data: [
        { month: "Jan 2023", employmentRate: 62.4, unemploymentRate: 5.1 },
        { month: "Jan 2024", employmentRate: 61.8, unemploymentRate: 5.7 },
        { month: "Jan 2025", employmentRate: 61.1, unemploymentRate: 6.7 },
        { month: "Jan 2026", employmentRate: 60.8, unemploymentRate: 6.5 },
        { month: "Jul 2026", employmentRate: 60.9, unemploymentRate: 6.4 },
      ],
    },
    {
      type: "narrative",
      id: "good-news-is-real",
      heading: "The good news is real—not just a statistical trick",
      body:
        "The strongest argument against dismissing July is breadth. The **75,100-job gain** was almost evenly divided between full-time work (**+38,600**) and part-time work (**+36,600**). Since April, however, the gain has been more durable: total employment is up **181,000**, led by **193,000 more full-time jobs**.\n\nThe job-finding rate rose to **20.8%**, from **18.5%** a year earlier. That means a higher share of unemployed people actually moved into work. It is still below the **26.6%** average for the same transition in 2017–2019, so the labour market is healing rather than tight.\n\nWages also support the soft-landing read. Average hourly wages rose **2.8% year over year to $37.17**. That is positive nominal income growth without the kind of acceleration that would automatically scream renewed wage inflation.",
    },
    {
      type: "chart",
      chartType: "bar",
      id: "public-sector-employment-growth",
      title: "Public-sector employment growth turned negative year over year",
      caption:
        "Year-over-year change in public-sector employees, monthly and seasonally adjusted. July 2026 was the first negative reading since August 2020. Public-sector employment fell by 27,000 in July and by 17,000 versus July 2025. Source: Statistics Canada Table 14-10-0288-01.",
      xKey: "month",
      yAxisLabel: "Jobs versus one year earlier",
      format: "number",
      referenceLine: { value: 0, label: "No growth" },
      series: [{ key: "public", label: "Public-sector YoY change", color: "#2563eb" }],
      data: [
        { month: "Jan 22", public: 221600 },
        { month: "Feb 22", public: 201100 },
        { month: "Mar 22", public: 160800 },
        { month: "Apr 22", public: 205800 },
        { month: "May 22", public: 237300 },
        { month: "Jun 22", public: 200300 },
        { month: "Jul 22", public: 180600 },
        { month: "Aug 22", public: 179900 },
        { month: "Sep 22", public: 118200 },
        { month: "Oct 22", public: 169800 },
        { month: "Nov 22", public: 123200 },
        { month: "Dec 22", public: 77200 },
        { month: "Jan 23", public: 106300 },
        { month: "Feb 23", public: 91100 },
        { month: "Mar 23", public: 100000 },
        { month: "Apr 23", public: 98500 },
        { month: "May 23", public: 50000 },
        { month: "Jun 23", public: 56200 },
        { month: "Jul 23", public: 89800 },
        { month: "Aug 23", public: 109800 },
        { month: "Sep 23", public: 107700 },
        { month: "Oct 23", public: 105700 },
        { month: "Nov 23", public: 101500 },
        { month: "Dec 23", public: 135800 },
        { month: "Jan 24", public: 167900 },
        { month: "Feb 24", public: 188100 },
        { month: "Mar 24", public: 181100 },
        { month: "Apr 24", public: 170000 },
        { month: "May 24", public: 177800 },
        { month: "Jun 24", public: 158800 },
        { month: "Jul 24", public: 192500 },
        { month: "Aug 24", public: 169900 },
        { month: "Sep 24", public: 109500 },
        { month: "Oct 24", public: 83800 },
        { month: "Nov 24", public: 139200 },
        { month: "Dec 24", public: 161100 },
        { month: "Jan 25", public: 110200 },
        { month: "Feb 25", public: 101500 },
        { month: "Mar 25", public: 90500 },
        { month: "Apr 25", public: 110200 },
        { month: "May 25", public: 81700 },
        { month: "Jun 25", public: 108800 },
        { month: "Jul 25", public: 64100 },
        { month: "Aug 25", public: 45400 },
        { month: "Sep 25", public: 102300 },
        { month: "Oct 25", public: 115300 },
        { month: "Nov 25", public: 84700 },
        { month: "Dec 25", public: 52400 },
        { month: "Jan 26", public: 74100 },
        { month: "Feb 26", public: 49900 },
        { month: "Mar 26", public: 55200 },
        { month: "Apr 26", public: 30600 },
        { month: "May 26", public: 66600 },
        { month: "Jun 26", public: 13800 },
        { month: "Jul 26", public: -17000 },
      ],
    },
    {
      type: "narrative",
      id: "public-private-pivot",
      heading: "The public-to-private handoff is the most important composition change",
      body:
        "For several years, public-sector hiring provided unusually persistent support to headline employment growth. That changed decisively in July. The number of public-sector employees fell **27,000 month over month** and **17,000 year over year**—the first annual decline since August 2020. Public administration employment itself fell by about **15,000** in July.\n\nMeanwhile, private-sector employment rose **58,000** in July and **171,600 year over year**. Self-employment rose **44,000** in the month and **42,000 year over year**. Since April, job growth has been concentrated in private-sector employees (**+146,000**) and self-employed workers (**+73,000**).\n\nThis is healthier if it persists. Private hiring is usually a better sign of market demand than governments expanding payrolls. But one month does not establish a durable handoff, and some public-sector weakness may reflect temporary staffing patterns. The next question is whether private firms continue hiring when the easy public-sector contribution is gone.",
    },
    {
      type: "chart",
      chartType: "bar",
      id: "industry-employment-change",
      title: "Employment gains reached housing-sensitive industries",
      caption:
        "Month-over-month change in thousands of jobs, July 2026, seasonally adjusted. Wholesale and retail led, while finance/real estate and construction both posted meaningful gains. Source: Statistics Canada, The Daily.",
      xKey: "industry",
      yAxisLabel: "Change in employment (thousands)",
      format: "number",
      referenceLine: { value: 0, label: "No change" },
      series: [{ key: "change", label: "Monthly change", color: "#2563eb" }],
      data: [
        { industry: "Wholesale & retail", change: 21.1 },
        { industry: "Finance, insurance & real estate", change: 18.0 },
        { industry: "Professional & technical", change: 16.6 },
        { industry: "Construction", change: 15.7 },
        { industry: "Manufacturing", change: 11.1 },
        { industry: "Business & building support", change: 9.4 },
        { industry: "Health & social assistance", change: 8.3 },
        { industry: "Transportation & warehousing", change: 7.6 },
        { industry: "Education", change: 6.7 },
        { industry: "Other services", change: 0.3 },
        { industry: "Utilities", change: -1.6 },
        { industry: "Accommodation & food", change: -4.4 },
        { industry: "Information, culture & recreation", change: -4.8 },
        { industry: "Natural resources", change: -4.9 },
        { industry: "Agriculture", change: -9.6 },
        { industry: "Public administration", change: -14.5 },
      ],
    },
    {
      type: "narrative",
      id: "housing-sensitive-industries",
      heading: "The industry mix is unusually relevant to real estate",
      body:
        "Two housing-sensitive categories were among July’s leaders. Employment rose by **18,000** in finance, insurance, real estate, rental and leasing, and by **16,000** in construction. Professional and technical services added another **17,000**.\n\nThat does not prove housing activity is about to surge—employment in all three industries was little changed year over year—but it does show the July gain was not confined to government or one low-wage service category. Construction employment is particularly useful to watch because it sits at the intersection of housing supply, renovation activity and development finance.\n\nWholesale and retail trade added **21,000** jobs in July, yet remained down **50,000 year over year**. That is a reminder to separate monthly momentum from the level of economic health. July improved the direction; it did not erase every weak trend.",
    },
    {
      type: "chart",
      chartType: "bar",
      id: "age-group-rates",
      title: "The labour market is strongest where most homebuyers are",
      caption:
        "Employment and unemployment rates by broad age group, July 2026, seasonally adjusted. Core-aged workers are 25 to 54. Source: Statistics Canada Table 14-10-0287-01.",
      xKey: "group",
      yAxisLabel: "Percent",
      format: "percent",
      series: [
        { key: "employmentRate", label: "Employment rate", color: "#2563eb" },
        { key: "unemploymentRate", label: "Unemployment rate", color: "#f97316" },
      ],
      data: [
        { group: "Total 15+", employmentRate: 60.9, unemploymentRate: 6.4 },
        { group: "Youth 15–24", employmentRate: 55.4, unemploymentRate: 12.6 },
        { group: "Core age 25–54", employmentRate: 83.9, unemploymentRate: 5.5 },
        { group: "Age 55+", employmentRate: 33.4, unemploymentRate: 5.2 },
      ],
    },
    {
      type: "narrative",
      id: "core-age-vs-youth",
      heading: "Core-aged households are doing better than the national headline suggests",
      body:
        "Housing demand is most sensitive to the 25-to-54 age group because that is where household formation, move-up purchases and most mortgage qualification happen. Core-aged employment rose **51,000** in July, with women accounting for **33,000** of the gain. The unemployment rate for core-aged women fell to **5.2%**, and their employment rate reached **81.2%**—above the **79.1%** pre-pandemic average.\n\nYouth remain the weak spot. The youth unemployment rate held at **12.6%**, below April’s 14.3% peak but still above the **10.8%** pre-pandemic average. Black youth unemployment was **22.6%**, versus **15.4%** for Chinese youth, **13.9%** for South Asian youth and **11.6%** for non-racialized, non-Indigenous youth.\n\nFor housing, this creates a split. Existing core-aged owners and buyers have a more supportive employment backdrop. Younger first-time buyers still face a difficult entry labour market on top of affordability and down-payment constraints.",
    },
    {
      type: "chart",
      chartType: "line",
      id: "returning-student-unemployment",
      title: "The summer job market improved, but remains weaker than before the pandemic",
      caption:
        "Unemployment rate for returning students aged 15 to 24 in the month of July, not seasonally adjusted. July 2026 was 15.1%, down from 17.5% in 2025 but above the 12.6% average for July 2017–2019. Source: Statistics Canada Table 14-10-0286-01.",
      xKey: "year",
      yAxisLabel: "Unemployment rate",
      format: "percent",
      referenceLine: { value: 12.6, label: "2017–2019 average" },
      series: [{ key: "rate", label: "Returning students", color: "#2563eb" }],
      data: [
        { year: "1977", rate: 14.7 }, { year: "1978", rate: 15.3 },
        { year: "1979", rate: 11.7 }, { year: "1980", rate: 13.2 },
        { year: "1981", rate: 11.3 }, { year: "1982", rate: 19.0 },
        { year: "1983", rate: 18.1 }, { year: "1984", rate: 14.7 },
        { year: "1985", rate: 14.2 }, { year: "1986", rate: 12.9 },
        { year: "1987", rate: 12.2 }, { year: "1988", rate: 10.6 },
        { year: "1989", rate: 9.9 }, { year: "1990", rate: 11.5 },
        { year: "1991", rate: 15.9 }, { year: "1992", rate: 18.5 },
        { year: "1993", rate: 19.0 }, { year: "1994", rate: 17.3 },
        { year: "1995", rate: 18.0 }, { year: "1996", rate: 17.9 },
        { year: "1997", rate: 19.6 }, { year: "1998", rate: 17.2 },
        { year: "1999", rate: 16.8 }, { year: "2000", rate: 15.5 },
        { year: "2001", rate: 15.4 }, { year: "2002", rate: 16.1 },
        { year: "2003", rate: 15.7 }, { year: "2004", rate: 16.7 },
        { year: "2005", rate: 16.0 }, { year: "2006", rate: 14.7 },
        { year: "2007", rate: 13.2 }, { year: "2008", rate: 13.1 },
        { year: "2009", rate: 19.3 }, { year: "2010", rate: 16.3 },
        { year: "2011", rate: 17.2 }, { year: "2012", rate: 16.6 },
        { year: "2013", rate: 16.3 }, { year: "2014", rate: 15.1 },
        { year: "2015", rate: 15.3 }, { year: "2016", rate: 16.1 },
        { year: "2017", rate: 13.0 }, { year: "2018", rate: 12.0 },
        { year: "2019", rate: 12.9 }, { year: "2020", rate: 28.1 },
        { year: "2021", rate: 14.7 }, { year: "2022", rate: 11.2 },
        { year: "2023", rate: 12.3 }, { year: "2024", rate: 17.1 },
        { year: "2025", rate: 17.5 }, { year: "2026", rate: 15.1 },
      ],
    },
    {
      type: "chart",
      chartType: "bar",
      id: "provincial-unemployment",
      title: "Provincial unemployment rates are converging—but local stories still differ",
      caption:
        "July 2026 unemployment rate by province and territory. Territorial figures are three-month moving averages and are not directly comparable with provincial monthly estimates. Canada: 6.4%. Source: Statistics Canada tables 14-10-0287-02 and 14-10-0292-02.",
      xKey: "region",
      yAxisLabel: "Unemployment rate",
      format: "percent",
      referenceLine: { value: 6.4, label: "Canada" },
      series: [{ key: "rate", label: "July 2026", color: "#2563eb" }],
      data: [
        { region: "N.L.", rate: 9.3 },
        { region: "P.E.I.", rate: 6.8 },
        { region: "N.S.", rate: 6.2 },
        { region: "N.B.", rate: 7.0 },
        { region: "Quebec", rate: 5.6 },
        { region: "Ontario", rate: 6.8 },
        { region: "Manitoba", rate: 5.0 },
        { region: "Sask.", rate: 6.0 },
        { region: "Alberta", rate: 7.0 },
        { region: "B.C.", rate: 6.2 },
        { region: "Yukon", rate: 6.6 },
        { region: "N.W.T.", rate: 8.0 },
        { region: "Nunavut", rate: 11.3 },
      ],
    },
    {
      type: "narrative",
      id: "regional-housing-read",
      heading: "Ontario’s improvement matters most to national housing sentiment",
      body:
        "Ontario added **52,000 jobs** in July and its unemployment rate fell to **6.8%**, down from 7.9% in December 2025. Toronto’s unemployment rate was **6.7%**, little changed in July but dramatically below the **9.0%** recorded a year earlier. For the country’s largest and most stressed resale market, that year-over-year improvement is meaningful.\n\nBritish Columbia added **18,000 jobs**, and unemployment fell to **6.2%** from 6.8% in May. Vancouver’s rate fell to **6.0%**. Manitoba and Nova Scotia also added jobs, while Quebec was flat.\n\nAlberta is the interesting contrast: employment is up **91,000 or 3.5% year over year**, the fastest provincial growth, yet unemployment remains **7.0%**. That can happen when labour-force and population growth are strong. For housing, job creation supports demand, but the unemployment rate reminds us that supply of workers—and therefore competition for work—has also grown.",
    },
    {
      type: "callout",
      tone: "warning",
      id: "rates-vs-housing",
      heading: "Better jobs are good for housing credit—but may slow the rate-cut story",
      body:
        "The same report that reduces fear of job loss can reduce urgency for Bank of Canada cuts. A stronger labour market supports income and mortgage performance, but it can also keep bond yields and fixed mortgage rates from falling as quickly as buyers hope. Underwrite the improved employment backdrop; do not automatically underwrite immediate rate relief.",
    },
    {
      type: "narrative",
      id: "housing-outlook",
      heading: "What this means for buyers, sellers and investors",
      body:
        "## Buyers\n\nThe employment backdrop is less frightening than it was in the spring. If your hesitation was job security, July is genuinely reassuring. But qualification still depends on today’s payment, not a hoped-for cut. Buy only if the deal works at the mortgage rate you can actually lock.\n\n## Sellers\n\nBetter employment can improve showing traffic and conversion, especially in Ontario and British Columbia. It does not erase excess listings or local condo supply. Job confidence helps demand at the margin; price, condition and competition still decide the sale.\n\n## Investors\n\nThe most attractive signal is the combination of stronger private-sector hiring and gains in finance/real estate and construction. The risk signal is the first annual decline in public-sector employment since 2020. Stress-test tenants and exits against a labour market that is stabilizing but no longer receiving the same public-payroll tailwind.\n\n## Mortgage risk\n\nNational bank mortgage arrears remain low by historical standards, even after rising from the 2022–2023 trough. Improving employment should cap the tail risk if it persists. Watch non-mortgage delinquency and revolving-credit use as earlier warnings; mortgages are usually the last payment households miss.",
    },
    {
      type: "narrative",
      id: "what-to-watch",
      heading: "Five signals to watch before the September 4 LFS",
      body:
        "- **Private-sector follow-through:** one strong month becomes a regime change only if firms keep hiring.\n- **Public-sector contraction:** July’s −17,000 year-over-year reading was the first negative print since August 2020. Watch whether it deepens.\n- **Core-aged unemployment:** this is the most housing-relevant labour cohort and currently looks stable.\n- **Youth unemployment:** 12.6% is improving but still historically uncomfortable.\n- **Job finding versus participation:** July’s job-finding rate improved, while participation rose slightly to 65.1%. That is a better combination than unemployment falling because people simply stopped looking.",
    },
    {
      type: "callout",
      tone: "success",
      id: "realist-verdict",
      heading: "Realist verdict",
      body:
        "Canada’s labour market is doing better. That should reduce buyer fear and limit the mortgage-arrears tail risk. The strongest part of the report is the private-sector handoff; the weakest is youth employment. For housing, July is demand-supportive and credit-supportive, but not automatically rate-cut-supportive.",
    },
    {
      type: "narrative",
      id: "methodology",
      heading: "Methodology and data quality",
      body:
        "The Labour Force Survey is a monthly household survey of approximately **65,000 households and more than 100,000 respondents**. July estimates describe conditions during the reference week of July 12–18, 2026. Statistics Canada’s national estimates exclude the territories. Unless noted otherwise, values in this report are seasonally adjusted.\n\nMonthly LFS estimates are sample-based and can be volatile. Statistics Canada focuses its Daily analysis on changes that are statistically significant at the 68% confidence level. Longer trends should carry more weight than a single print. Public-sector year-over-year growth in this report is calculated from the seasonally adjusted employment levels in Table 14-10-0288-01.\n\nThe unemployment/mortgage-arrears chart uses annual averages of monthly series and rebases each to 1995 = 100. The approximate 0.69 correlation is calculated over common monthly observations from January 1995 onward. It is not a causal estimate and should not be used as a mortgage-default forecast.",
    },
  ],
  sources: [
    {
      label: "Labour Force Survey, July 2026",
      url: STATCAN_DAILY_URL,
      publisher: "Statistics Canada, The Daily, August 7, 2026",
    },
    {
      label: "Labour force characteristics, monthly, seasonally adjusted and trend-cycle",
      url: STATCAN_HEADLINE_TABLE_URL,
      publisher: "Statistics Canada Table 14-10-0287-01",
    },
    {
      label: "Employment by class of worker, monthly, seasonally adjusted and unadjusted",
      url: STATCAN_CLASS_TABLE_URL,
      publisher: "Statistics Canada Table 14-10-0288-01",
    },
    {
      label: "Examining the macro drivers of mortgage arrears in Canada",
      url: BOC_ARREARS_PAPER_URL,
      publisher: "Bank of Canada Staff Analytical Paper 2026-12",
    },
    {
      label: "Residential Mortgage Industry Report",
      url: CMHC_MORTGAGE_REPORT_URL,
      publisher: "Canada Mortgage and Housing Corporation, 2026",
    },
    {
      label: "Interactive Canada jobs market and housing-risk explorer",
      url: REALIST_LABOUR_EXPLORER,
      publisher: "stats.realist.ca",
    },
  ],
  cta: {
    toolUrl: "/tools/analyzer",
    headline: "Turn the macro signal into a deal-level decision",
    body:
      "Better employment reduces one housing risk; it does not make every property work. Stress-test income, financing, vacancy and exit assumptions before you buy.",
  },
};
