import { DEFAULT_AUTHOR, type ChartBlock, type ReportContent } from "../reportContent";

const GSC_URL =
  "https://search.google.com/search-console/performance/search-analytics?resource_id=sc-domain%3Arealist.ca";
const GOOGLE_TRENDS_URL = "https://trends.google.com/trends/explore?date=all&geo=CA";
const NOTION_EPISODE_URL =
  "https://app.notion.com/p/The-9-Most-Googled-Real-Estate-Questions-of-2026-39577b52a03d80448b09f66d61945539";
const REALIST_REPORT_ROUTE = "/insights/reports/canada-real-estate-search-questions-2026";

const housePricesTrend = [
  { year: 2004, interest: 35 },
  { year: 2005, interest: 38 },
  { year: 2006, interest: 41 },
  { year: 2007, interest: 46 },
  { year: 2008, interest: 52 },
  { year: 2009, interest: 38 },
  { year: 2010, interest: 37 },
  { year: 2011, interest: 39 },
  { year: 2012, interest: 44 },
  { year: 2013, interest: 43 },
  { year: 2014, interest: 47 },
  { year: 2015, interest: 59 },
  { year: 2016, interest: 74 },
  { year: 2017, interest: 77 },
  { year: 2018, interest: 67 },
  { year: 2019, interest: 63 },
  { year: 2020, interest: 70 },
  { year: 2021, interest: 81 },
  { year: 2022, interest: 98 },
  { year: 2023, interest: 71 },
  { year: 2024, interest: 57 },
  { year: 2025, interest: 65 },
  { year: 2026, interest: 100 },
];

const rentVsBuyTrend = [
  { year: 2004, interest: 7 },
  { year: 2005, interest: 6 },
  { year: 2006, interest: 10 },
  { year: 2007, interest: 8 },
  { year: 2008, interest: 8 },
  { year: 2009, interest: 8 },
  { year: 2010, interest: 12 },
  { year: 2011, interest: 13 },
  { year: 2012, interest: 11 },
  { year: 2013, interest: 14 },
  { year: 2014, interest: 17 },
  { year: 2015, interest: 18 },
  { year: 2016, interest: 14 },
  { year: 2017, interest: 15 },
  { year: 2018, interest: 14 },
  { year: 2019, interest: 15 },
  { year: 2020, interest: 14 },
  { year: 2021, interest: 13 },
  { year: 2022, interest: 12 },
  { year: 2023, interest: 14 },
  { year: 2024, interest: 16 },
  { year: 2025, interest: 26 },
  { year: 2026, interest: 100 },
];

const capRateTrend = [
  { year: 2004, interest: 9 },
  { year: 2005, interest: 8 },
  { year: 2006, interest: 9 },
  { year: 2007, interest: 12 },
  { year: 2008, interest: 13 },
  { year: 2009, interest: 13 },
  { year: 2010, interest: 14 },
  { year: 2011, interest: 15 },
  { year: 2012, interest: 16 },
  { year: 2013, interest: 19 },
  { year: 2014, interest: 20 },
  { year: 2015, interest: 22 },
  { year: 2016, interest: 21 },
  { year: 2017, interest: 22 },
  { year: 2018, interest: 23 },
  { year: 2019, interest: 23 },
  { year: 2020, interest: 20 },
  { year: 2021, interest: 24 },
  { year: 2022, interest: 31 },
  { year: 2023, interest: 29 },
  { year: 2024, interest: 31 },
  { year: 2025, interest: 44 },
  { year: 2026, interest: 100 },
];

const mortgageRenewalTrend = [
  { year: 2004, interest: 3 },
  { year: 2005, interest: 3 },
  { year: 2006, interest: 3 },
  { year: 2007, interest: 5 },
  { year: 2008, interest: 6 },
  { year: 2009, interest: 8 },
  { year: 2010, interest: 6 },
  { year: 2011, interest: 7 },
  { year: 2012, interest: 10 },
  { year: 2013, interest: 11 },
  { year: 2014, interest: 11 },
  { year: 2015, interest: 15 },
  { year: 2016, interest: 14 },
  { year: 2017, interest: 16 },
  { year: 2018, interest: 23 },
  { year: 2019, interest: 23 },
  { year: 2020, interest: 28 },
  { year: 2021, interest: 24 },
  { year: 2022, interest: 25 },
  { year: 2023, interest: 42 },
  { year: 2024, interest: 59 },
  { year: 2025, interest: 82 },
  { year: 2026, interest: 100 },
];

const principalResidenceExemptionTrend = [
  { year: 2004, interest: 0 },
  { year: 2005, interest: 0 },
  { year: 2006, interest: 20 },
  { year: 2007, interest: 14 },
  { year: 2008, interest: 12 },
  { year: 2009, interest: 16 },
  { year: 2010, interest: 20 },
  { year: 2011, interest: 27 },
  { year: 2012, interest: 29 },
  { year: 2013, interest: 36 },
  { year: 2014, interest: 41 },
  { year: 2015, interest: 50 },
  { year: 2016, interest: 55 },
  { year: 2017, interest: 79 },
  { year: 2018, interest: 67 },
  { year: 2019, interest: 64 },
  { year: 2020, interest: 61 },
  { year: 2021, interest: 76 },
  { year: 2022, interest: 84 },
  { year: 2023, interest: 75 },
  { year: 2024, interest: 93 },
  { year: 2025, interest: 75 },
  { year: 2026, interest: 100 },
];

const airbnbRulesTrend = [
  { year: 2004, interest: 0 },
  { year: 2005, interest: 0 },
  { year: 2006, interest: 0 },
  { year: 2007, interest: 0 },
  { year: 2008, interest: 0 },
  { year: 2009, interest: 0 },
  { year: 2010, interest: 0 },
  { year: 2011, interest: 0 },
  { year: 2012, interest: 0 },
  { year: 2013, interest: 0 },
  { year: 2014, interest: 2 },
  { year: 2015, interest: 5 },
  { year: 2016, interest: 10 },
  { year: 2017, interest: 20 },
  { year: 2018, interest: 34 },
  { year: 2019, interest: 48 },
  { year: 2020, interest: 47 },
  { year: 2021, interest: 46 },
  { year: 2022, interest: 59 },
  { year: 2023, interest: 87 },
  { year: 2024, interest: 100 },
  { year: 2025, interest: 69 },
  { year: 2026, interest: 95 },
];

const rentalPropertyCorporationTrend = [
  { year: 2004, interest: 0 },
  { year: 2005, interest: 0 },
  { year: 2006, interest: 0 },
  { year: 2007, interest: 0 },
  { year: 2008, interest: 0 },
  { year: 2009, interest: 0 },
  { year: 2010, interest: 0 },
  { year: 2011, interest: 16 },
  { year: 2012, interest: 22 },
  { year: 2013, interest: 29 },
  { year: 2014, interest: 33 },
  { year: 2015, interest: 43 },
  { year: 2016, interest: 28 },
  { year: 2017, interest: 36 },
  { year: 2018, interest: 33 },
  { year: 2019, interest: 33 },
  { year: 2020, interest: 36 },
  { year: 2021, interest: 49 },
  { year: 2022, interest: 56 },
  { year: 2023, interest: 60 },
  { year: 2024, interest: 61 },
  { year: 2025, interest: 63 },
  { year: 2026, interest: 100 },
];

const thirtyYearAmortizationTrend = [
  { year: 2004, interest: 0 },
  { year: 2005, interest: 0 },
  { year: 2006, interest: 26 },
  { year: 2007, interest: 0 },
  { year: 2008, interest: 0 },
  { year: 2009, interest: 0 },
  { year: 2010, interest: 6 },
  { year: 2011, interest: 8 },
  { year: 2012, interest: 18 },
  { year: 2013, interest: 23 },
  { year: 2014, interest: 17 },
  { year: 2015, interest: 18 },
  { year: 2016, interest: 18 },
  { year: 2017, interest: 18 },
  { year: 2018, interest: 16 },
  { year: 2019, interest: 23 },
  { year: 2020, interest: 25 },
  { year: 2021, interest: 26 },
  { year: 2022, interest: 24 },
  { year: 2023, interest: 25 },
  { year: 2024, interest: 100 },
  { year: 2025, interest: 73 },
  { year: 2026, interest: 98 },
];

const fixedOrVariableMortgageTrend = [
  { year: 2004, interest: 0 },
  { year: 2005, interest: 16 },
  { year: 2006, interest: 0 },
  { year: 2007, interest: 14 },
  { year: 2008, interest: 25 },
  { year: 2009, interest: 27 },
  { year: 2010, interest: 44 },
  { year: 2011, interest: 34 },
  { year: 2012, interest: 18 },
  { year: 2013, interest: 25 },
  { year: 2014, interest: 27 },
  { year: 2015, interest: 38 },
  { year: 2016, interest: 28 },
  { year: 2017, interest: 30 },
  { year: 2018, interest: 46 },
  { year: 2019, interest: 24 },
  { year: 2020, interest: 42 },
  { year: 2021, interest: 53 },
  { year: 2022, interest: 87 },
  { year: 2023, interest: 41 },
  { year: 2024, interest: 48 },
  { year: 2025, interest: 76 },
  { year: 2026, interest: 100 },
];

function trendChart(id: string, title: string, query: string, data: Array<{ year: number; interest: number }>, caption: string): ChartBlock {
  return {
    type: "chart",
    chartType: "line",
    id,
    title,
    caption: `Google Trends Canada, 2004-present, annual average search-interest index for "${query}" where 100 is the peak year in this pull. ${caption}`,
    xKey: "year",
    xAxisLabel: "Year",
    yAxisLabel: "Search interest index",
    format: "number",
    referenceLine: { value: 50, label: "Half of peak" },
    series: [{ key: "interest", label: query, color: "#800000" }],
    data,
  };
}

export const canadaRealEstateSearchQuestions2026ConfigReport: ReportContent = {
  slug: "canada-real-estate-search-questions-2026",
  title: "The Real Estate Questions Canadians Are Googling in 2026",
  dek:
    "A Google Trends and Search Console companion to the Realist podcast episode on the nine real estate questions buyers, owners, and investors keep asking. The long-run charts show which questions are becoming more important, not just where Realist already ranks.",
  author: DEFAULT_AUTHOR,
  publishDate: "2026-07-09",
  kind: "research",
  tags: [
    "google-trends",
    "google-search-console",
    "seo",
    "canadian-real-estate",
    "mortgage-renewals",
    "rent-vs-buy",
    "real-estate-investing",
  ],
  ogImage: "/og-image.png",
  metaTitle: "The Real Estate Questions Canadians Are Googling in 2026 | Realist",
  metaDescription:
    "Realist report mapping Canada's long-run Google Trends interest in real estate questions since 2004, plus Realist Search Console data for current SEO opportunity.",
  heroStat: {
    label: "Long-run search window",
    value: "2004-2026",
    detail:
      "Google Trends Canada data pulled for the episode's major real estate questions, with Realist Search Console layered in separately.",
  },
  sections: [
    {
      type: "statGrid",
      id: "headline-stats",
      heading: "The corrected search read",
      stats: [
        {
          label: "Trends window",
          value: "23 years",
          detail: "Annual Google Trends Canada series from 2004 through partial-year 2026.",
          trend: "up",
        },
        {
          label: "Trend queries",
          value: "9",
          detail: "One long-run line chart for each episode search theme.",
          trend: "up",
        },
        {
          label: "Realist.ca clicks from Canada",
          value: "95%",
          detail: "543 of 570 Google Search Console clicks came from Canada in the Apr. 21 to Jul. 6, 2026 export window.",
          trend: "up",
        },
        {
          label: "Realist.ca impressions from Canada",
          value: "64%",
          detail: "Canada generated 8,748 of 13,738 impressions in the same Search Console export.",
          trend: "up",
        },
      ],
    },
    {
      type: "callout",
      tone: "warning",
      id: "method-note",
      heading: "Method note",
      body:
        "This report uses **two different Google datasets**. Google Trends is the long-run national demand layer and goes back to 2004. Search Console is Realist.ca's own site-performance layer and only shows how realist.ca appeared in Google for the exported window. The prior version leaned too hard on Search Console. This version uses Trends for the historical question charts and Search Console only for Realist-specific visibility.",
    },
    {
      type: "narrative",
      id: "bottom-line",
      heading: "Bottom line",
      body:
        "The real signal is not that Canadians asked one housing question in 2026. It is that several question families are peaking at the same time: home prices, renewal stress, rent-vs-buy math, cap rates, principal-residence tax, short-term-rental rules, incorporation, 30-year amortization, and fixed-versus-variable mortgage decisions.\n\nThat is a useful editorial map. People are not just casually browsing. They are trying to decide whether to buy, rent, renew, sell, incorporate, Airbnb, or underwrite an investment. Realist should answer those questions with tools, not just articles.",
    },
    trendChart(
      "trend-house-prices",
      "1. Will house prices go down?",
      "house prices",
      housePricesTrend,
      "Home-price search interest rose into the 2021-2022 boom, pulled back, then re-accelerated in 2026 as buyers and sellers tried to reprice the market."
    ),
    trendChart(
      "trend-rent-vs-buy",
      "2. Is it cheaper to rent or buy?",
      "rent vs buy",
      rentVsBuyTrend,
      "This is the tool opportunity. The term was sleepy for years, then became much more relevant as ownership costs detached from rent and income."
    ),
    trendChart(
      "trend-cap-rate",
      "3. What cap rate or cash flow makes sense?",
      "cap rate",
      capRateTrend,
      "Investor search interest has moved from generic property enthusiasm toward actual yield math. That is Realist's lane."
    ),
    trendChart(
      "trend-mortgage-renewal",
      "4. What happens at mortgage renewal?",
      "mortgage renewal",
      mortgageRenewalTrend,
      "Renewal stress is now a mainstream housing question. This is where payment-shock explainers should become calculators and triage workflows."
    ),
    trendChart(
      "trend-principal-residence-exemption",
      "5. How does the principal residence exemption work?",
      "principal residence exemption",
      principalResidenceExemptionTrend,
      "The tax question keeps getting more important as more household wealth sits inside owner-occupied housing."
    ),
    trendChart(
      "trend-airbnb-rules",
      "6. Can I Airbnb or short-term-rent this property?",
      "airbnb rules",
      airbnbRulesTrend,
      "Search interest only became meaningful after Airbnb itself became a real housing-market issue. The useful page is local and rules-driven."
    ),
    trendChart(
      "trend-rental-property-corporation",
      "7. Should rental property go inside a corporation?",
      "rental property corporation",
      rentalPropertyCorporationTrend,
      "This is not a beginner question. It is a scale, tax, financing, accounting, and liability question for investors who are getting more serious."
    ),
    trendChart(
      "trend-30-year-amortization",
      "8. What is the deal with 30-year amortization?",
      "30 year amortization",
      thirtyYearAmortizationTrend,
      "The policy cycle shows up clearly: long amortization becomes interesting when affordability breaks and governments reach for payment relief."
    ),
    trendChart(
      "trend-fixed-variable",
      "9. Fixed or variable mortgage?",
      "fixed or variable mortgage",
      fixedOrVariableMortgageTrend,
      "The rate-decision question spiked with the post-2021 rate shock. It should be answered with scenario math, not rate-prediction theatre."
    ),
    {
      type: "chart",
      chartType: "bar",
      id: "country-mix",
      title: "Realist's organic search traffic is already mostly Canadian",
      caption:
        "Google Search Console country tab for realist.ca, Apr. 21 to Jul. 6, 2026. This is Realist site-performance data, not national search demand.",
      xKey: "country",
      yAxisLabel: "Search Console count",
      format: "number",
      series: [
        { key: "clicks", label: "Clicks", color: "#800000" },
        { key: "impressions", label: "Impressions", color: "#55565b" },
      ],
      data: [
        { country: "Canada", clicks: 543, impressions: 8748 },
        { country: "United States", clicks: 13, impressions: 3325 },
        { country: "India", clicks: 2, impressions: 130 },
        { country: "Italy", clicks: 2, impressions: 31 },
        { country: "Rest of world", clicks: 10, impressions: 1504 },
      ],
    },
    {
      type: "chart",
      chartType: "bar",
      id: "realist-current-visibility",
      title: "Realist current visibility: strong brand/tool base, weak question capture",
      caption:
        "Queries grouped manually from the 650 exported Search Console rows. This shows what Realist currently captures, not total national demand.",
      xKey: "theme",
      yAxisLabel: "Impressions",
      format: "number",
      series: [
        { key: "impressions", label: "Impressions", color: "#800000" },
        { key: "clicks", label: "Clicks", color: "#d04a06" },
      ],
      data: [
        { theme: "Realist / deal tools", impressions: 3941, clicks: 277 },
        { theme: "Home prices", impressions: 185, clicks: 0 },
        { theme: "Cash flow / cap rates", impressions: 48, clicks: 0 },
        { theme: "Rent vs buy", impressions: 33, clicks: 0 },
        { theme: "Rates / renewals", impressions: 4, clicks: 0 },
        { theme: "PRE / capital gains", impressions: 4, clicks: 0 },
        { theme: "Rental incorporation", impressions: 0, clicks: 0 },
        { theme: "Airbnb / STR rules", impressions: 0, clicks: 0 },
        { theme: "30-year amortization", impressions: 0, clicks: 0 },
      ],
    },
    {
      type: "narrative",
      id: "content-plan",
      heading: "What Realist should build from this",
      body:
        "The corrected roadmap is straightforward.\n\n- Build one permanent hub for the nine questions.\n- Turn rent-vs-buy into a tool-first page, not a blog post.\n- Attach cap-rate and cash-flow questions to the analyzer, market data, and Deal of the Day.\n- Build a renewal triage workflow that starts with payment shock.\n- Make Airbnb rules local by city, because national answers are useless.\n- Make PRE and incorporation pages plain-English but referral-aware, because tax questions need expert handoff.\n- Treat 30-year amortization as a payment-relief page, not a policy-news page.\n\nThat is the point: podcast creates demand, Trends shows the long-run question curve, Search Console shows where Realist is undercapturing it, and the product turns the question into a decision.",
    },
    {
      type: "callout",
      tone: "info",
      id: "realist-read",
      heading: "The Realist read",
      body:
        "The winning companion report is not a keyword dump. It is a decision map. If someone searches the question, Realist should help them finish the next step: underwrite, compare, triage, ask a professional, or submit a deal.",
    },
  ],
  sources: [
    {
      label: "Google Trends Canada, 2004-present annual interest-over-time pulls for the nine search terms",
      url: GOOGLE_TRENDS_URL,
      publisher: "Google Trends",
    },
    {
      label: "Google Search Console export for realist.ca, Apr. 21 to Jul. 6, 2026",
      url: GSC_URL,
      publisher: "Google Search Console",
    },
    {
      label: "The 9 Most Googled Real Estate Questions of 2026",
      url: NOTION_EPISODE_URL,
      publisher: "Realist podcast draft",
    },
    {
      label: "Realist report route",
      url: REALIST_REPORT_ROUTE,
      publisher: "Realist.ca",
    },
  ],
  cta: {
    toolUrl: "/tools/analyzer",
    headline: "Turn the question into an underwriting decision.",
    body:
      "Use Realist to test the deal, compare the rent-vs-buy math, pressure-check cash flow, and route the question to the right expert before making a real estate decision.",
  },
};
